### ISSUE TITLE
[Climedo] Cannot register new contacts/cases in Climedo

### ISSUE THREAD

**Issue by dragosb-vg** [hzi-braunschweig/SORMAS-Project#10674]
### Bug Description

New contacts or cases cannot be registered to Climedo. Accessing the Register to Climedo EDiary generates an error message.
### Steps to Reproduce

1. Access and login (as admin/NatUser) to [ga1.sormas-oegd.de](https://ga1.sormas-oegd.de/)
2. Create new contact / case.
3. Add contact info (valid email).
4. Access the 'Register to Climedo EDiary' button.
5. Observe result.

### Actual  Behavior

'Error has occured' message is displayed. No email is received on the provided email.

### Expected Behavior

'Person added' message is displayed. Email is received on the provided email

### Screenshots

![pop-up](https://user-images.githubusercontent.com/111864167/196610157-34352655-ceb6-426c-9c88-af65168cc4c6.gif)

### System Details

* Device: Chrome (Version 106.0.5249.119)
* SORMAS version: 1.76.0-SNAPSHOT ([f34a7c8](https://github.com/hzi-braunschweig/SORMAS-Project/commits/f34a7c851f8fa799497e6037ba1ad6b7e6b33243))
* Android version/Browser: -
* Server URL: [ga1.sormas-oegd.de](https://ga1.sormas-oegd.de/)
* User Role: admin/NatUser

### Additional Information

Log:
`2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.getSystemExceptionReply(MessageMediatorImpl.java:610)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.ReplyMessage_1_2.getSystemException(ReplyMessage_1_2.java:131)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.MessageBase.getSystemException(MessageBase.java:813)
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2330)
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2357)
2022-10-18 13:07:19	
	at org.glassfish.enterprise.iiop.impl.POAProtocolMgr.mapException(POAProtocolMgr.java:356)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:277)
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2330)
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2357)
2022-10-18 13:07:19	
	at org.glassfish.enterprise.iiop.impl.POAProtocolMgr.mapException(POAProtocolMgr.java:356)
2022-10-18 13:07:19	
Caused by: javax.transaction.TransactionRolledbackException: CORBA TRANSACTION_ROLLEDBACK 9998 Maybe; nested exception is: 
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: null
2022-10-18 13:07:19	
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in de.symeda.sormas.ui.utils.ExternalJournalUtil$$Lambda$3212/0x0000000802897440 failed.
2022-10-18 13:07:19	
Caused by: java.lang.reflect.InvocationTargetException: null
2022-10-18 13:07:19	
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
2022-10-18 13:07:19	
  E130719.730|     > java.lang.NullPointerException (de.symeda.sormas.ui.SormasErrorHandler.java:85)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.getSystemExceptionReply(MessageMediatorImpl.java:610)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.ReplyMessage_1_2.getSystemException(ReplyMessage_1_2.java:131)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.protocol.giopmsgheaders.MessageBase.getSystemException(MessageBase.java:813)
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2330)
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2357)
2022-10-18 13:07:19	
	at org.glassfish.enterprise.iiop.impl.POAProtocolMgr.mapException(POAProtocolMgr.java:356)
2022-10-18 13:07:19	
	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:277)
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2330)
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2357)
2022-10-18 13:07:19	
	at org.glassfish.enterprise.iiop.impl.POAProtocolMgr.mapException(POAProtocolMgr.java:356)
2022-10-18 13:07:19	
Caused by: javax.transaction.TransactionRolledbackException: CORBA TRANSACTION_ROLLEDBACK 9998 Maybe; nested exception is: 
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException
2022-10-18 13:07:19	
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in de.symeda.sormas.ui.utils.ExternalJournalUtil$$Lambda$3212/0x0000000802897440 failed.
2022-10-18 13:07:19	
Caused by: java.lang.reflect.InvocationTargetException
2022-10-18 13:07:19	
  com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
13:07:19,688 DEBUG [org.keycloak.events] (default task-48) type=LOGIN, realmId=SORMAS, clientId=sormas-rest, userId=db3f0b13-6db8-43f9-9388-4b3b7207da3e, ipAddress=10.210.11.124, auth_method=openid-connect, token_id=c73cba30-32a4-4dc1-b092-379a00308eb5, grant_type=password, refresh_token_type=Refresh, scope='profile email', refresh_token_id=ddb46e62-ad29-497b-9d57-6320e5fa31cf, client_auth_method=client-secret, username=ClimTest, authSessionParentId=47d0a35a-77f0-46c7-a3be-c0d08a9c3b7b, authSessionTabId=599VRYHp1vA
2022-10-18 13:07:19	
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
2022-10-18 13:07:19	
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
2022-10-18 13:07:19	
Caused by: java.lang.NullPointerException
2022-10-18 13:07:19	
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
2022-10-18 13:07:19	
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException`

**Comment by FredrikSchaeferVitagroup** [comment]
The log excerpt provided is incomplete. Here's a more useful one:
[error-ga1.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/9817968/error-ga1.log)
The complete error message indicates that it's again the same phenomenom as described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8640. For some reason, climedo replies with `success = false` when trying to register a person, but does not provide a `message` explaining why. This causes a NPE [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/5d5824e6697cbd8132e1c2a7d19797246299871e/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/PatientDiaryClient.java#L98).
Maybe @DraganMileski can tell what's going wrong on the climedo side?

**Comment by FredrikSchaeferVitagroup** [comment]
The problem seems to occur on [test](https://test1402.sormas.netzlink.com/) as well.

**Comment by FredrikSchaeferVitagroup** [comment]
This came out not to be a bug in SORMAS, but a configuration issue on climedo side. 
Registering patients works again on [ga1.sormas-oegd.de](https://ga1.sormas-oegd.de/) and [test1402](https://test1402.sormas.netzlink.com/).

**Comment by KernB** [comment]
@FredrikSchaeferVitagroup  
Did somebody informed Climedo about this configuration issue or do we have to do it? 
Did Climedo already fixed it?
When can we expect the solution?

**Comment by FredrikSchaeferVitagroup** [comment]
@KernB This issue was solved in cooperation with Climedo. As I [stated](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10674#issuecomment-1290028551), the issue is solved. The only thing that needed to be done was to revert some config changes on climedo side for [ga1.sormas-oegd.de](https://ga1.sormas-oegd.de/) and [test1402](https://test1402.sormas.netzlink.com/).
