### ISSUE TITLE
Automatic case deletion fails with Survnet enabled

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#10820]
### Bug Description
Automatic deletion fails with Survnet enabled. During case deletion `CaseService.deleteCaseInExternalSurveillanceTool` is called which in turn tries to evaluate `CaseJurisdictionPredicateValidator.isInJurisdictionOrOwned`. This fails as both `user` and `userPath` are null.

Whether a similar behaviour occurs for entities subject to automatic deletion other than Case should be checked

```
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: java.lang.NullPointerException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2386)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2183)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy614.deleteCaseInExternalSurveillanceTool(Unknown Source)
	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.deleteCaseInExternalSurveillanceTool(Unknown Source)
	at de.symeda.sormas.backend.caze.CaseService.deleteCaseInExternalSurveillanceTool(CaseService.java:1123)
	at de.symeda.sormas.backend.caze.CaseService.deletePermanent(CaseService.java:1045)
	at de.symeda.sormas.backend.caze.CaseService.deletePermanent(CaseService.java:171)
...
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseJurisdictionPredicateValidator.isInJurisdictionOrOwned(CaseJurisdictionPredicateValidator.java:87)
	at de.symeda.sormas.backend.caze.CaseJurisdictionPredicateValidator.isInJurisdictionOrOwned(CaseJurisdictionPredicateValidator.java:40)
	at de.symeda.sormas.api.utils.jurisdiction.JurisdictionValidator.inJurisdictionOrOwned(JurisdictionValidator.java:42)
	at de.symeda.sormas.backend.caze.CaseService.inJurisdictionOrOwned(CaseService.java:1625)
	at de.symeda.sormas.backend.caze.CaseService.inJurisdictionOrOwned(CaseService.java:1621)
	at de.symeda.sormas.backend.caze.CaseService.inJurisdictionOrOwned(CaseService.java:1617)
	at de.symeda.sormas.backend.common.AbstractCoreAdoService.lambda$inJurisdictionOrOwned$94ccb43f$1(AbstractCoreAdoService.java:200)
	at de.symeda.sormas.backend.common.BaseAdoService.fulfillsCondition(BaseAdoService.java:214)
	at de.symeda.sormas.backend.common.AbstractCoreAdoService.inJurisdictionOrOwned(AbstractCoreAdoService.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor244.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at de.symeda.sormas.backend.util.RightsAllowedInterceptor.checkRightsAllowed(RightsAllowedInterceptor.java:111)
	at jdk.internal.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at de.symeda.sormas.backend.audit.AuditLoggerInterceptor.logAudit(AuditLoggerInterceptor.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor241.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 354 more
```

### Steps to Reproduce

1. make sure property `survnet.url` is configured and non-blank
2. configure automated deletion for cases
3. wait for automated deletion to be performed (for test purposes, scheduled time can be adapted in `CronService.deleteExpiredEntities`)

### Expected Behavior
Jurisdiction check should be omitted for user System.

### System Details

* Device: local PC
* SORMAS version: 1.77.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL:
* User Role:

**Comment by syntakker** [comment]
> @syntakker is this also relevant for other versions like 1.76?
@JaquM-HZI I have only tested in 1.77.0-SNAPSHOT. However, last code changes I found at a glance are from September, so the bug might be present in 1.76.0. (from Oct. 14).

**Comment by syntakker** [comment]
An potentially easy fix would be in `CaseJurisdictionPredicateValidator`, l.81ff, where the `NullPointerException` is thrown. Here it is assumed that either `user` or `userPath` is not null. In automatic deletion, however, both are null.

```java
	@Override
	protected Predicate isInJurisdictionOrOwned() {
		final Predicate reportedByCurrentUser = cb.and(
			cb.isNotNull(joins.getRoot().get(Case.REPORTING_USER)),
			user != null
				? cb.equal(joins.getRoot().get(Case.REPORTING_USER).get(User.ID), user.getId())
				: cb.equal(joins.getRoot().get(Case.REPORTING_USER).get(User.ID), userPath.get(User.ID)));

		return cb.or(reportedByCurrentUser, isInJurisdiction());
	}
```
At first glance, possible implications are that cases are returned in pseudonyimzed form. It should be analyzed whether this doeas any harm here.

**Comment by StefanKock** [comment]
I digged through the code and found that #9708 with commit 7dc91f3d0a2a1e38480be169f4efce76117ace25 changed that `CaseFacadeEjb.getByExternalId` (line 4186) now takes a pseudonymized DTO. This was changed in the last days, so currently only on `development`.

**Comment by StefanKock** [comment]
#9708 needs to fix this problem, this ticket is then a duplicate.

**Comment by JonasCir** [comment]
@StefanKock I can take a look, but the change from `convertToDto` -> `toPseudonymizedDto` was just a name change, so pseudonymization was there before.

**Comment by JonasCir** [comment]
Maybe the null-check that @syntakker would do the trick

**Comment by StefanKock** [comment]
> @StefanKock I can take a look, but the change from `convertToDto` -> `toPseudonymizedDto` was just a name change, so pseudonymization was there before.

Ahh, okay now I understand the refactoring. So I don't know where this problem came from, but it's likely at least in 1.76.x

**Comment by JonasCir** [comment]
So I looked a the code I'm certain this problem is older:

```java
	public Predicate inJurisdictionOrOwned(CaseQueryContext qc, User user) {
		return CaseJurisdictionPredicateValidator.of(qc, user).inJurisdictionOrOwned();
	}
``` 
this creates a `CaseJurisdictionPredicateValidator` where ` userPath` is explicitly nulled in the used `CaseJurisdictionPredicateValidator` constructor.

```java
	public Predicate inJurisdictionOrOwned(CaseQueryContext qc) {
		return inJurisdictionOrOwned(qc, userService.getCurrentUser());
	}
``` 
As automatic deletion is driven by the `SYSTEM` user, `userService.getCurrentUser()` will return `null`.

Adjusting `getCurrentUser` is delicate and out of scope for a hotfix I would say, so I suggest to make sure that `CaseJurisdictionPredicateValidator.isInJurisdictionOrOwned` can handle the nulls.

**Comment by JonasCir** [comment]
@StefanKock Easy fix, I take it :)

**Comment by StefanKock** [comment]
The problematic pseudonymization is pointless here (it's only checking the list size), so maybe this approach helps here for now:

```java
	public void deleteCaseInExternalSurveillanceTool(Case caze) throws ExternalSurveillanceToolException {

		if (externalSurveillanceToolGatewayFacade.isFeatureEnabled() && caze.getExternalID() != null && !caze.getExternalID().isEmpty()) {
//			List<CaseDataDto> casesWithSameExternalId = getByExternalId(caze.getExternalID());
			List<Case> casesWithSameExternalId = service.getByExternalId(caze.getExternalID());
			if (casesWithSameExternalId != null && casesWithSameExternalId.size() == 1) {
				externalSurveillanceToolGatewayFacade.deleteCases(Collections.singletonList(toDto(caze)));
			}
		}
	}
```
