### ISSUE TITLE
Local Machine does not start after the latest pull from development

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10959]
### Problem Description

After pulling the latest changes from development, the local machines no longer start.

Logs:
[local.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10039849/local.txt)

![image](https://user-images.githubusercontent.com/96909231/202664294-74e69db2-f8e0-4243-9b53-b4327a969178.png)

**Comment by StefanKock** [comment]
Linked to #10214. Solution: Update serverlibs (Ant -> sormas-base -> deploy-serverlibs)

```
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.cache.ehcache.internal.SingletonEhcacheRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:156)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:239)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:192)
	at org.hibernate.cache.internal.RegionFactoryInitiator.resolveRegionFactory(RegionFactoryInitiator.java:93)
	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:47)
	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:32)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	... 63 more
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [org.hibernate.cache.ehcache.internal.SingletonEhcacheRegionFactory]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:133)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:152)
	... 70 more
Caused by: java.lang.ClassNotFoundException: Could not load requested class : org.hibernate.cache.ehcache.internal.SingletonEhcacheRegionFactory
	at org.hibernate.boot.registry.classloading.internal.AggregatedClassLoader.findClass(AggregatedClassLoader.java:210)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)
	... 71 more
```

**Comment by adinaflorea9** [comment]
Tried the steps with @sergiupacurariu in a call, but unfortunately for me it does not work - I use the docker for my local machine.

**Comment by JonasCir** [comment]
@adinaflorea9 probably due to caching. Not certain where it is located exactly, but you can try `docker system prune` and then rebuild. Be aware that this removes everything that docker has currently cached, so do not execute it if there are any images/containers etc which you cannot replace.

**Comment by adinaflorea9** [comment]
Thanks for lookin into this as well @JonasCir. @sergiupacurariu managed to fix it in the meantime - I needed a new file created in sormas-base for build.properties as it was missing for me somehow and I only had the build.properties.example file.
