### ISSUE TITLE
@NotNull adnotation not working in some environments

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#11834]
### Bug Description

Ticket #4959 is intended to replace the @Required with @NotNull annotation. The implementation of this ticket conducted to different behaviors on different systems. The purpose of this ticket is to identify why we experience these uneven outcomes.

### Reproduction Steps

The ticket #4959 implementation contains a change on CaseDataDto on the field "healthFacility". The old "@Required" annotation was replaced with "@NotNull". This implementation triggered bug #11812. The main issue of it was that creating a new case with POINT_OF_ENTRY origin was not possible anymore because of the new "@NotNull" annotation on healthFacility field. However, there are some systems where the users with the same configuration were able to save the same type of case.
Also, on the systems where cases saved from UI have been blocked the case creation tests (same case structure as on UI) ran against the same system passed without any problem.

Systems where @NotNull annotation was triggered:
- https://test-auto.sormas.netzlink.com/
- https://test-de1.sormas.netzlink.com/
- https://test-de2.sormas.netzlink.com/
- local systems with Azul zulu JDK 11.0.10, 11.0.16, Open JDK 11.0.2

Systems where @NotNull annotation was **NOT** triggered:
- local systems with OpenJDK 11.0.15 and Azul Zulu 11.0.9

The case creation tests did not trigger the @NotNull check on any system no matter whether on UI it did or didn't.

### Affected Area(s)

Web app, ReST API

### SORMAS Version

SORMAS 1.83.0

### Android version/Browser

not important

### User Role(s)

National User

**Comment by MartinWahnschaffe** [comment]
On my local system with zulu-11.18 it also works and I have never noticed any unregular behaviour. 
Trying to downgrade to zulu-11.09 didn't work. I went as far as replacing the complete JAVA_HOME JDK on my system, rebuilding the whole project and clearing all generated/cached files from the domain (applications, autodeploy, generated and osgi-cache/felix folders). Unfortunately I wasn't able to check whether it's working, because there still seems to be some part build with 11.18 remaining in the server and thus I received the following exception:

> java.lang.IllegalStateException: java.io.IOException: Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

<details>
> 	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initStores(SecuritySupportImpl.java:483)
> 	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initStores(SecuritySupportImpl.java:419)
> 	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initJKS(SecuritySupportImpl.java:381)
> 	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:153)
> 	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.<init>(SecuritySupportImpl.java:148)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1356)
> 	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:248)
> 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:342)
> 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
> 	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
> 	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
> 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
> 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
> 	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:680)
> 	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
> 	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
> 	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
> 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
> 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
> 	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
> 	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
> 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
> 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
> 	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:680)
> 	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
> 	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
> 	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
> 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
> 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
> 	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
> 	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
> 	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
> 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
> 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
> 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
> 	at com.sun.enterprise.security.ee.SecuritySniffer.setup(SecuritySniffer.java:121)
> 	at com.sun.enterprise.v3.server.ContainerStarter.startContainer(ContainerStarter.java:98)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainer(ApplicationLifecycle.java:1195)
> 	at com.sun.enterprise.v3.server.ApplicationLifecycle.startEngine(ApplicationLifecycle.java:958)
</details>

I'm putting this investigation on hold, since the sometimes not working bean validation is not blocking our further development, as we have another level of validation within the backend that checks the most important things.

We should continue with this, once #10499 has updated the payare version.
