### ISSUE TITLE
Analyse slow deployment of sormas-ear [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#11902]
### Problem Description

It's often felt by developers that the deployment of `sormas-ear` in the Payara domain takes a lot of time (~60s to several minutes).

This slows down deployment cycles and is therefore a burden when coding and testing. It would also be nice if the deployment on hosted instances would be faster.

### Proposed Solution

1. Gather information how long the deployment takes on DEV and hosted instances.
2. Identify phases and duration in the log.
3. Debug/Add log entries to check which startup code of `sormas-backend` (presumable all in `StartupShutdownService`) costs time.

**Comment by StefanKock** [comment]
I started the analysis on my DEV system. For now I identified 3 phases when deploying `sormas-ear` on a running Payara domain. It's only the first deployment, a redeployment is not 

| Phase           | Time run 1 | Time run 2 | Comment     |
| ------------- | -----------:| -----------:| ------------- |
| 1                  |            41s |            40s | No log entries |
| 2                  |            13s |            13s | First log entry until `WELD-000900` | 
| 3                  |            36s |            33s | End of phase 2 until `sormas-ear was successfully deployed` |
| Success time |            81s |            77s | Reported in `sormas-ear was successfully deployed` message  |
| Total time     |            90s |            86s | Total time of all phases   |

Findings:
- I have a lot of warnings concerning expired SSL certificates, takes 2s
- Constant overhead of 9s that is not reported in the `sormas-ear was successfully deployed` message
- StartupShutdownService.startup takes 5s

Versions:
- Eclipse 2022-12
- Payara 5.2021.10
- Zulu 11.45.27-ca-jdk11.0.10
- SORMAS 1.84.0-SNAPSHOT, commit e4ab722

<details>
<summary>Log Extract</summary>

```bash
2B 2023-05-04T11:28:59.825+0200|SCHWERWIEGEND: @Lock is only permitted for singleton session beans
...
2E 2023-05-04T11:29:12.365+0200|INFORMATION: WELD-000900: 3.1.8 (Final)

3B 2023-05-04T11:29:25.386+0200|INFORMATION: Portable JNDI names for EJB SormasToSormasOriginInfoService: ...
3  2023-05-04T11:29:25.429+0200|INFORMATION: Portable JNDI names for EJB CaseShareDataBuilder: ...
3  2023-05-04T11:29:25.758+0200|WARNUNG: The SSL certificate has expired: [
...
3  2023-05-04T11:29:27.695+0200|INFORMATION: JTS5014: Recoverable JTS instance, serverId=[9037]
3  2023-05-04T11:29:28.129+0200|INFORMATION: Portable JNDI names for EJB CampaignFormMetaFacade: ...
...
3  2023-05-04T11:29:39.052+0200|INFORMATION: WELD-001125: Illegal bean type de.symeda.auditlog.api.value.format.ValueFormatter<java.lang.Enum<?>> ignored on [EnhancedAnnotatedTypeImpl] public  class de.symeda.auditlog.api.value.format.EnumFormatter
3  2023-05-04T11:29:42.622+0200|INFORMATION: Clustered CDI Event bus initialized

### StartupShutdownService.startup
3  2023-05-04T11:29:44.493+0200|INFORMATION: W112944.490|     > audit.source.site is empty! Please configure it for more expedient audit trail analysis. (de.symeda.sormas.backend.audit.AuditLoggerEjb.java:143)
...
3  2023-05-04T11:29:48.798+0200|INFORMATION: I112948.798|     > Skipping synchronization with central as feature is disabled. (de.symeda.sormas.backend.infrastructure.central.CentralInfraSyncFacade.java:118)
###

3E 2023-05-04T11:29:49.012+0200|INFORMATION: sormas-ear was successfully deployed in 80.910 milliseconds.

```

</details>

<details>
<summary>Exception when redeployment fails</summary>

2nd deployment runs into error (redeployment problem)
```
Caused by: org.apache.xerces.impl.dv.DVFactoryException: DTD factory class org.apache.xerces.impl.dv.dtd.DTDDVFactoryImpl does not extend from DTDDVFactory.
	at org.apache.xerces.impl.dv.DTDDVFactory.getInstance(Unknown Source)
	at org.apache.xerces.impl.dv.DTDDVFactory.getInstance(Unknown Source)
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.<init>(Unknown Source)
	at org.apache.xerces.jaxp.validation.XMLSchemaValidatorComponentManager.<init>(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorHandlerImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.validation.AbstractXMLSchema.newValidatorHandler(Unknown Source)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.<init>(ValidatingUnmarshaller.java:43)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshallerHandler(UnmarshallerImpl.java:167)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:426)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:405)
	at org.hibernate.boot.jaxb.internal.AbstractBinder.jaxb(AbstractBinder.java:172)
	at org.hibernate.boot.jaxb.internal.MappingBinder.doBind(MappingBinder.java:61)
	at org.hibernate.boot.jaxb.internal.AbstractBinder.doBind(AbstractBinder.java:103)
	at org.hibernate.boot.jaxb.internal.AbstractBinder.bind(AbstractBinder.java:58)
	at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:43)
	... 63 more
```

</details>

Unfortunately most of the time is spend in general deployment, nothing specific to workload in our code.

**Comment by StefanKock** [comment]
I tried to deploy sormas-ear via autodeploy without all jars except sormas-api (copied all other jars into lib/ext/). The deployment failed due to classloading problems when executing the startup but almost succeeded.

```
2023-05-04T17:51:08.084+0200|INFORMATION: Selecting file C:\srv\payara-domains\sormas_de\autodeploy\sormas-ear.ear for autodeployment
2023-05-04T17:51:36.631+0200|WARNUNG: [AutoDeploy] Autodeploy failed : C:\srv\payara-domains\sormas_de\autodeploy\sormas-ear.ear.
```
The total time was 28s (7s, 13s, 8s per phase). Looks like reducing the class footprint will help.

Another problem I found is that my sormas-ear.ear contains several dependencies in more than one version. `Maven -> Update Project` (with `Clean projects` checked) does not clean the `target/lib` folder, but `Run as -> 4 Maven clean` does. The Ant target install also does not clean, so dirty target folders are then part of the exploded deployment.

209 jars would be correct, but I had 293 jars packaged. The exploded deployment only contains the jars with the currently relevant versions.

**Comment by StefanKock** [comment]
Next steps:
1. Follow up ticket: Push most dependencies from the apps to the payara domain libs (except vaadin and sormas-api), remove dependencies provided by Payara modules or not in deployment needed swagger tools
2. Check if mvn clean helps to avoid duplicate dependencies.
