### ISSUE TITLE
Error sending logback emails

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1243]
> ERROR in ch.qos.logback.classic.net.SMTPAppender[EMAIL_ERROR] - Error occurred while sending e-mail notification. javax.mail.MessagingException: IOException while sending message;
>   nested exception is:
>         javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;
>         boundary="----=_Part_1049_2055300542.1564476301766"
>         at javax.mail.MessagingException: IOException while sending message
>         at      at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1365)
>         at      at javax.mail.Transport.send0(Transport.java:255)
>         at      at javax.mail.Transport.send(Transport.java:124)
>         at      at ch.qos.logback.core.net.SMTPAppenderBase.sendBuffer(SMTPAppenderBase.java:389)
>         at      at ch.qos.logback.core.net.SMTPAppenderBase$SenderRunnable.run(SMTPAppenderBase.java:671)
>         at      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at      at java.lang.Thread.run(Thread.java:748)
> Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;
>         boundary="----=_Part_1049_2055300542.1564476301766"
>         at      at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:896)
>         at      at javax.activation.DataHandler.writeTo(DataHandler.java:317)
>         at      at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1694)
>         at      at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1913)
>         at      at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1315)
>         at      ... 11 common frames omitted
>

**Comment by MartinWahnschaffeSymeda** [comment]
Could not reproduce this problem on my dev system and the test server.
sormas.org.ng was not running on zuu though. This may have caused the problem.
I have changed this and updated the server. We need to check the server.log again tomorrow to this if the issues is resolved now.

**Comment by MartinWahnschaffeSymeda** [comment]
Problem is resolved
