### ISSUE TITLE
EntityNotFoundException when trying to get active tasks

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1255]
```
Caused by: javax.persistence.EntityNotFoundException: Unable to find de.symeda.sormas.backend.contact.Contact with id 500822
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:162)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:209)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:260)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:103)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:71)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1286)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1163)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:687)
	at org.hibernate.type.EntityType.resolve(EntityType.java:464)
	at org.hibernate.type.ManyToOneType.resolve(ManyToOneType.java:239)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:185)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:129)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1150)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:1009)
	at org.hibernate.loader.Loader.doQuery(Loader.java:947)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:339)
	at org.hibernate.loader.Loader.doList(Loader.java:2693)
	at org.hibernate.loader.Loader.doList(Loader.java:2676)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2510)
	at org.hibernate.loader.Loader.list(Loader.java:2505)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1561)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
	at de.symeda.sormas.backend.task.TaskService.getAllActiveTasksAfter(TaskService.java:84)
	at sun.reflect.GeneratedMethodAccessor1992.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 146 more
```

**Comment by MateStrysewskeSym** [comment]
This originates from a REST call, so could actually be the reason for some of our synchronization problems:

`at de.symeda.sormas.rest.TaskResource.getAll(TaskResource.java:59)`

**Comment by MateStrysewskeSym** [comment]
The source of this problem could be that the Contact.contactOfficer field is set to nullable=false in Java, while there is no actual Not-Null-Constraint in the database; the contact specified in the error message above does not have a contactofficer_id set.

According to this comment: https://stackoverflow.com/a/42544883
... this could lead to the entity not being fetched when using @ManyToOne which produces this exception. I'll verify this with other affected entities.

**Comment by MateStrysewskeSym** [comment]
All contacts I checked did not have a contactofficer_id. This is probably the problem, but I'll leave this issue open for now to check whether this happens again after the next server update.
