### ISSUE TITLE
HibernateException concerning the cascade type of weekly reports

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1285]
HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: de.symeda.sormas.backend.report.WeeklyReport.reportEntries

at de.symeda.sormas.backend.report.WeeklyReportFacadeEjb.saveWeeklyReport(WeeklyReportFacadeEjb.java:132)

at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:31)
at de.symeda.sormas.rest.WeeklyReportResource.postWeeklyReports(WeeklyReportResource.java:68)

**Comment by MateStrysewskeSym** [comment]
Didn't occur again in the newest release.
