### ISSUE TITLE
Error when setting task form to read-only

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1327]
`Caused by: java.lang.IllegalStateException: This component does not support the read-only
mode, since state is of type VerticalLayoutState and does not inherit AbstractFieldState
at com.vaadin.ui.AbstractComponent.setReadOnly(AbstractComponent.java:1055)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.setReadOnly(CommitDiscardWrapperComponent.java:532)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.setWrappedComponent(CommitDiscardWrapperComponent.java:156)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.<init>(CommitDiscardWrapperComponent.java:103)
at de.symeda.sormas.ui.task.TaskController.edit(TaskController.java:100)
at de.symeda.sormas.ui.task.TaskGrid.itemClick(TaskGrid.java:185)`

**Comment by mvarchdev** [comment]
Hello. I have same problem in Vaadin compatibility version 8
`This component does not support the read-only mode, since state is of type VerticalLayoutState and does not inherit AbstractFieldState`

**Comment by MateStrysewske** [comment]
@mvarchdev As you can see in the commit that closed this issue, we've solved it by catching the exception and using `setEnabled` as a fallback.
