### ISSUE TITLE
Fix bugs reported by Firebase/OTRS in 1.28.1

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1351]

**Comment by MateStrysewskeSym** [comment]
`java.lang.NullPointerException: null
at de.symeda.sormas.ui.caze.CasesView.lambda$createFilterBar$1a34c76c$6(CasesView.java:511)
at sun.reflect.GeneratedMethodAccessor468.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)`
