### ISSUE TITLE
NullPointer error in CasesView and Dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1369]
Taken from log on sormas.org.ng:

- [ ] **java.lang.NullPointerException: null
	at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.fillCaseLists(DashboardMapComponent.java:915)**
	at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.refreshMap(DashboardMapComponent.java:214)
	at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.refreshDashboard(ContactsDashboardView.java:160)
	at de.symeda.sormas.ui.dashboard.AbstractDashboardView.enter(AbstractDashboardView.java:103)
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:726)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)

- [ ] **Caused by: java.lang.NullPointerException: null
	at de.symeda.sormas.ui.caze.CasesView.lambda$createFilterBar$1a34c76c$7(CasesView.java:528)**
	at sun.reflect.GeneratedMethodAccessor2407.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
	... 85 common frames omitted

**Comment by MartinWahnschaffeSymeda** [comment]
I looked into the wrong part of the log. These seem to stem from the old version.
