### ISSUE TITLE
Merge duplicate error

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1377]
This error occurs when trying to merge duplicates

**Comment by bernardsilenou** [comment]
@Iheanacho2027  This error might be due to un-synchronized changes in one of the cases. Does this happen to all the duplicate pairs ?. Can you contact the reporting users to resynch their tablets to validate if this is the cause?

**Comment by Iheanacho2027** [comment]
Happens in majority of the potential duplicates for measles. I had to look
into them one after the other

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 What's the problem exactly? What kind of error do you get and when?

**Comment by Iheanacho2027** [comment]
Sorry i thought i put up the image initially
![merge error](https://user-images.githubusercontent.com/50739609/69809177-7c60eb00-11e9-11ea-9328-09144254ca67.JPG)

**Comment by MateStrysewskeSym** [comment]
I've found this error log that is very likely the cause of this issue:

``Caused by: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at de.symeda.sormas.backend.util.DtoHelper.fillDto(DtoHelper.java:68)
	at de.symeda.sormas.backend.util.DtoHelper.fillDto(DtoHelper.java:78)
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.mergeCase(CaseFacadeEjb.java:2767)
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.mergeCase(CaseFacadeEjb.java:2761)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
	... 111 more``
