### ISSUE TITLE
PSQLException: duplicate key value violates unique constraint "weeklyreport_uuid_key"

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1455]
2020-01-13 05:06:16,557 ERROR OKITIPUPA_SO
	at de.symeda.sormas.api.report._WeeklyReportFacade_Wrapper.saveWeeklyReport(de/symeda/sormas/api/report/_WeeklyReportFacade_Wrapper.java)
	at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:31)
	at de.symeda.sormas.rest.WeeklyReportResource.postWeeklyReports(WeeklyReportResource.java:65)
	at de.symeda.sormas.api.report.__WeeklyReportFacade_Remote_DynamicStub.saveWeeklyReport(de/symeda/sormas/api/report/__WeeklyReportFacade_Remote_DynamicStub.java)
	at de.symeda.sormas.api.report._WeeklyReportFacade_Wrapper.saveWeeklyReport(de/symeda/sormas/api/report/_WeeklyReportFacade_Wrapper.java)
	at de.symeda.sormas.rest.TransactionWrapper.execute(TransactionWrapper.java:36)
	at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:31)
	at de.symeda.sormas.rest.WeeklyReportResource.postWeeklyReports(WeeklyReportResource.java:65)
	at de.symeda.sormas.backend.report.__EJB31_Generated__WeeklyReportService__Intf____Bean__.ensurePersisted(Unknown Source)
	at de.symeda.sormas.backend.report.WeeklyReportFacadeEjb.saveWeeklyReport(WeeklyReportFacadeEjb.java:132)
	Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "weeklyreport_uuid_key"   Detail: Key (uuid)=(W57QU2-MN45Q6-AYKJ64-NBZMKBRA) already exists.

	2020-01-13 03:41:46,100 ERROR ETCHE_SO  de.symeda.sormas.rest.CaseResource - CaseDataDto VBA2ID-PMJM3I-7OYOYK-MCUWSMLA 01/01/1970 00:00
	at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:31)
	at de.symeda.sormas.rest.CaseResource.postCases(CaseResource.java:65)
	at de.symeda.sormas.api.caze.__CaseFacade_Remote_DynamicStub.saveCase(de/symeda/sormas/api/caze/__CaseFacade_Remote_DynamicStub.java)
	at de.symeda.sormas.api.caze._CaseFacade_Wrapper.saveCase(de/symeda/sormas/api/caze/_CaseFacade_Wrapper.java)
	at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:31)
	at de.symeda.sormas.rest.CaseResource.postCases(CaseResource.java:65)
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1187)
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1169)
	Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "healthconditions_uuid_key"  Detail: Key (uuid)=(UWYLWG-XW7REI-55L42H-6TW3KE7Q) already exists.

**Comment by MartinWahnschaffeSymeda** [comment]
Idea: Maybe the app sends the weekly report twice with the same push. 

- [ ] try to reproduce this with a rest call

**Comment by MartinWahnschaffeSymeda** [comment]
There are indeed two parallel sync processes from the same device:

> 2020-01-24 17:08:18,529 DEBUG   http-thread-pool::http-listener-1(4) d.s.s.r.l.RequestResponseLogger - requestUri = /sormas-rest/cases/all/1579885083573
> 2020-01-24 17:08:18,711 DEBUG   http-thread-pool::http-listener-1(1) d.s.s.r.l.RequestResponseLogger - requestUri = /sormas-rest/cases/all/1579885083573
> 2020-01-24 17:08:19,417 DEBUG   http-thread-pool::http-listener-1(5) d.s.s.r.l.RequestResponseLogger - requestUri = /sormas-rest/cases/push
> 2020-01-24 17:08:19,513 DEBUG   http-thread-pool::http-listener-1(3) d.s.s.r.l.RequestResponseLogger - requestUri = /sormas-rest/cases/push

Looks like this is what happens:

When the user logs in the first time the automatic background sync is started. At this point it's likely that the user also manually syncs. The sync process is started by initializing the RetroProvider which can take 2 seconds or more, because "checkCompatibility" is called. The current logic to check for existing sync processes does not take this into account.

- [ ] Adjust the sync process to make sure only one sync can take place at a time
