### ISSUE TITLE
Error in DataImporter

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1456]
2020-01-14 08:46:01,623 ERROR   d.s.sormas.ui.importer.DataImporter - -1
	java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at de.symeda.sormas.ui.caze.importer.CaseImporter$1.apply(CaseImporter.java:142)
	at de.symeda.sormas.ui.caze.importer.CaseImporter$1.apply(CaseImporter.java:125)
	at de.symeda.sormas.ui.importer.DataImporter.insertRowIntoData(DataImporter.java:370)
	at de.symeda.sormas.ui.caze.importer.CaseImporter.importDataFromCsvLine(CaseImporter.java:125)
	at de.symeda.sormas.ui.importer.DataImporter.runImport(DataImporter.java:209)
	at de.symeda.sormas.ui.importer.DataImporter$2.run(DataImporter.java:101)

	2020-01-17 12:17:23,448 ERROR   d.s.sormas.ui.importer.DataImporter - null
	java.lang.ArrayIndexOutOfBoundsException: null

**Comment by ChristopherRiedelSymeda** [comment]
Stacktrace suggests that the read out samples are null, but still the .size() method is used. (Actually, the samples should not be zero at this point.) This is probably due to an incorrectly formatted import file. But this is not an error source. You could add an additional query (samples != null) to avoid this error.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I was able to reproduce it using the attached csv file (had to change it to txt to upload here).
Looks like the logic to detect the first sample field is not working correctly when there are empty values in the first data row.
[sormas_import_case_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4098497/sormas_import_case_template.txt)

**Comment by MateStrysewskeSym** [comment]
Check whether it's easily possible to only try to import every cell for the first line and ignore empty cells for all consecutive lines.
