### ISSUE TITLE
Error saving sample

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1457]
com.vaadin.v7.data.fieldgroup.FieldGroup$FieldGroupInvalidValueException: null
	at com.vaadin.v7.data.fieldgroup.FieldGroup.commit(FieldGroup.java:507)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:328)
	at de.symeda.sormas.ui.samples.SampleController$10.buttonClick(SampleController.java:260)
	at sun.reflect.GeneratedMethodAccessor1540.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
	... 86 common frames omitted

**Comment by ChristopherRiedelSymeda** [comment]
The error cannot be reproduced by me without further context.
