### ISSUE TITLE
IndexOutOfBoundsException in GeoShapeProvider

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1494]
Only seems to happen on the Nigerian server after updating to 1.32.0:

```
		for (int i=0; i<polygons.size(); i++) {
			for (int j=0; j<polygons.size(); j++) {
				if (i==j)
					continue;
				if (polygons.get(i).touches(polygons.get(j))) { // touch
					polygons.set(i, (Polygon)polygons.get(i).union(polygons.get(j))); // union
					polygons.remove(j);
					j--;
				}
			}
		}
```

**Comment by StefanKock** [comment]
Corresponding StackTrace:
```
Caused by: javax.ejb.CreateException: Could not create stateless EJB
at com.sun.ejb.containers.StatelessSessionContainer.createStatelessEJB(StatelessSessionContainer.java:518)
at com.sun.ejb.containers.StatelessSessionContainer.access$000(StatelessSessionContainer.java:92)
at com.sun.ejb.containers.StatelessSessionContainer$SessionContextFactory.create(StatelessSessionContainer.java:706)
... 126 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at de.symeda.sormas.backend.region.GeoShapeProviderEjb.buildCountryShape(GeoShapeProviderEjb.java:389)
at de.symeda.sormas.backend.region.GeoShapeProviderEjb.loadData(GeoShapeProviderEjb.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```
