### ISSUE TITLE
ERROR: column user0_.active 

### ISSUE THREAD

**Issue by shallam** [hzi-braunschweig/SORMAS-Project#1672]
### Bug Description
When deploying Sormas using the server-setup & server-deploy scripts I am receiving an error in the logs
 `Caused by: org.postgresql.util.PSQLException: ERROR: column user0_.active does not exist
  Hint: Perhaps you meant to reference the column "user0_.aktiv".
  Position: 130`
This is error happens when navigating to localhost:6080/sormas-ui/login
### Steps to Reproduce
1. run ./server-setup.sh 
2. run ./server-deploy.sh
3. Monitor the deployment in payara server and server logs
4. Navigating to localhost:6080/sormas-ui/login throws the error in the log file

### Expected Behavior
sormas app to launch in the browser, database schema to be updated to english
### Screenshots

![user](https://user-images.githubusercontent.com/956809/77674948-8e5d5b00-6f49-11ea-987b-ee69507d9f7d.png)
![deploy](https://user-images.githubusercontent.com/956809/77675008-a3d28500-6f49-11ea-8b10-328b9e3320cc.PNG)

### System Details
* Device: Ubuntu 18.04
* SORMAS version: 1.36.2
* Android version/Browser: Firefox

**Comment by MateStrysewskeSym** [comment]
@shallam Your issue looks like the update script didn't run successfully. Could you try to run it again and see whether there are any errors? Also, please have a look into your database and tell us what the latest entry in the schema_version table is.

**Comment by shallam** [comment]
Hello @MateStrysewskeSym  we were able to manually add a user into the data base and run the update script. 
The latest entry in the schema_version is 191 | 2020-03-27 01:23:58.05799  | Add quarantine information to contact #1608
We were able to launch the app but unable to log in.

**Comment by hzi-old** [comment]
@shallam 
Default Logins These are the default users for demo systems. Make sure to deactivate them or change the passwords on productive systems:

Admin name: admin pw: sadmin

Surveillance Supervisor (web UI) name: SunkSesa pw: Sunkanmi

Surveillance Officer (mobile app) name: SanaObas pw: Sanaa

https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_UPDATE.md

**Comment by shallam** [comment]
@MateStrysewskeSym 
That is not working, logs show
`List of constraint violations:[
        ConstraintViolationImpl{interpolatedMessage='size must be between 20 and 36', propertyPath=uuid, rootBeanClass=class de.symeda.sormas.backend.user.User, messageTemplate='{javax.validation.constraints.Size.message}'}
]
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreUpdate(BeanValidationEventListener.java:88)
        at org.hibernate.action.internal.EntityUpdateAction.preUpdate(EntityUpdateAction.java:248)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:119)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1483)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:514)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3353)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2525)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:352)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.sun.enterprise.transaction.JavaEETransactionImpl.commit(JavaEETransactionImpl.java:443)
        at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:904)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:721)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:505)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2117)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy533.doFilter(Unknown Source)
        at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
        at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
        at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:579)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by shallam** [comment]
@MateStrysewskeSym 
On a clean deploy, running the server update script we see the last schema_version entry as:
50 other health facility description for cases #238

Thanks
Steve

**Comment by MateStrysewskeSym** [comment]
Could you please verify that your software stack matches the one required for SORMAS? For example, any PostgreSQL version above 10 is not supported. Did you do everything exactly as described in the Installing a SORMAS Server guide?

**Comment by MateStrysewskeSym** [comment]
The error you were getting before doing a clean deploy is likely due to a malformed UUID in the user you'd manually created. Also, you should not be required to do so. SORMAS comes with some default users that you can use to log in.

**Comment by shallam** [comment]
PostgreSQL is 10.12, Running on Ubuntu 18.04.4
Instructions were followed from this page:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md

Steve

**Comment by MateStrysewskeSym** [comment]
@StefanKock @HolgerReiseVSys Any chance that you encountered a similar error when you tried to set up your environments?

**Comment by StefanKock** [comment]
I did not ran into this issue when setting up SORMAS 1.35.0

**Comment by shallam** [comment]
Looking at the setup log I see this on the first server update run 
`[2020-03-27T16:03:08.488+0000] [Payara 5.192] [WARNING] [] [javax.enterprise.system.core.transaction.com.sun.jts.jtsxa] [tid: _ThreadID=103 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1585324988488] [levelValue: 900] [[
  JTS5068: Unexpected error occurred in rollback
org.postgresql.xa.PGXAException: Error rolling back prepared transaction. rollback xid=(Available at FINE log level), preparedXid=(Available at FINE log level), currentXid={2}
        at org.postgresql.xa.PGXAConnection.rollback(PGXAConnection.java:480)
        at com.sun.gjc.spi.XAResourceImpl.rollback(XAResourceImpl.java:204)
        at com.sun.jts.jta.TransactionState._rollback(TransactionState.java:202)
        at com.sun.jts.jta.TransactionState.rollback(TransactionState.java:180)
`

**Comment by MartinWahnschaffeSymeda** [comment]
Hi. When deploying the sormas ear, the system will check the latest schema_version entry and run the parts of sormas_schema.sql that follow.
For schema_version 50 the next entry is:

> UPDATE public.district SET name=replace(name,' LGA', '') WHERE name ~ ' LGA$';
> INSERT INTO schema_version (version_number, comment) VALUES (51, 'Fix Oyo LGA names #230');

Can you try to manually execute this on your database an see what happens?

**Comment by shallam** [comment]
sormas_db=# UPDATE public.district SET name=replace(name,' LGA', '') WHERE name ~ ' LGA$';
UPDATE 0
sormas_db=# INSERT INTO schema_version (version_number, comment) VALUES (51, 'Fix Oyo LGA names #230');
INSERT 0 1

Steve

**Comment by MartinWahnschaffeSymeda** [comment]
Sounds like the max_prepared_transactions in the postgres config are not set.
Make sure to set it to at least 64 (see https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md#postgres-database).
Afterwards restart the postgres and then try to update again.

**Comment by StefanKock** [comment]
I agree with @MartinWahnschaffeSymeda. Make sure you removed the # at the start of the line to make the config active.

**Comment by sovello** [comment]
I encountered same error and tried executing all suggestions put here to no avail.
Looking at the columns in the table, I only found column aktiv.
Then I did `grep -ri aktiv` and got this back
```
sormas-backend/src/main/resources/sql/sormas_schema.sql:    aktiv boolean NOT NULL,
sormas-backend/src/main/resources/sql/sormas_schema.sql:-- 2019-04-23 Rename "aktiv" to "active" in user table
sormas-backend/src/main/resources/sql/sormas_schema.sql:ALTER TABLE users RENAME COLUMN aktiv TO active;
sormas-backend/src/main/resources/sql/sormas_schema.sql:ALTER TABLE users_history RENAME COLUMN aktiv TO active;
sormas-backend/src/main/resources/sql/sormas_schema.sql:INSERT INTO schema_version (version_number, comment) VALUES (144, 'Rename aktiv to active in user table');
```
I ran `ALTER TABLE users RENAME COLUMN aktiv TO active;` successfully.
Running `ALTER TABLE users_history RENAME COLUMN aktiv TO active;` **was unsuccessful** and the INSERT statement didn't work because pkey 144 already exists.
When I did `SELECT * FROM schema_version WHERE version_number = 144` returned 
```
 version_number |         changedate         |               comment                | upgradeneeded 
----------------+----------------------------+--------------------------------------+---------------
            144 | 2020-03-31 02:10:23.580643 | Rename aktiv to active in user table | f
```

This suggests that `sormas-backend/src/main/resources/sql/sormas_schema.sql` was executed successfully except the RENAME didn't happen.
I will try update set max_prepared_transactions = 96 instead of the 64 that's suggested hoping that will help

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda @HolgerReiseVSys Is there any update to this issue?

**Comment by MateStrysewskeSym** [comment]
@shallam @sovello Do you still have problems with this or has it been resolved in the meantime?

**Comment by sovello** [comment]
I was successful after making those tweaks. So no problem for now.
Thanks

**Comment by MateStrysewskeSym** [comment]
@sovello Great, thanks for the feedback!

**Comment by StefanKock** [comment]
Problems seemed to be the missing max_prepared_statements, what breaks automatic db update.

**Comment by nmeri17** [comment]
why not just export schema definition as standalone sql file or leave the db seeding as a library that can run unhindered? i'm stuck on a variation of this error. i found this thread https://github.com/SORMAS-Foundation/SORMAS-Project/issues/230 from here and realised none of those lga, states or countries are part of my seeded data or schema, despite having 100+ tables. how do i debug this? i have the following sql file before deployment
```sql
DROP DATABASE IF EXISTS sormas;
DROP USER IF EXISTS sormas_user;
CREATE USER sormas_user WITH PASSWORD '12345' CREATEDB;
CREATE DATABASE sormas WITH OWNER = sormas_user ENCODING = 'UTF8';
\connect sormas;
CREATE OR REPLACE PROCEDURAL LANGUAGE plpgsql;
ALTER PROCEDURAL LANGUAGE plpgsql OWNER TO sormas_user;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS unaccent;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO sormas_user;
ALTER SYSTEM SET max_prepared_transactions = 64;
SELECT pg_reload_conf();
```
it would seem the seeding breaks but there's no clearcut method to debug or fix, whereas a sql dump from your end would take that headache away. i'm currently facing

> at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
> 	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:212)
> 	at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
> 	at com.sun.proxy.$Proxy489.getUserRoles(Unknown Source)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
> 	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
> 	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
> 	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
> 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)
> 	at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:128)
> 	at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:259)
> 	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:189)
> 	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
> 	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
> 	at de.symeda.sormas.api.user.__UserFacade_Remote_DynamicStub.getUserRoles(de/symeda/sormas/api/user/__UserFacade_Remote_DynamicStub.java)
> 	at de.symeda.sormas.api.user._UserFacade_Wrapper.getUserRoles(de/symeda/sormas/api/user/_UserFacade_Wrapper.java)
> 	at de.symeda.sormas.ui.UserProvider.getUserRoles(UserProvider.java:71)
> 	at de.symeda.sormas.ui.UserProvider.getUserRights(UserProvider.java:64)
> 	at de.symeda.sormas.ui.UserProvider.hasUserRight(UserProvider.java:95)
> 	at de.symeda.sormas.ui.UiUtil.permitted(UiUtil.java:111)
> 	at de.symeda.sormas.ui.UiUtil.permitted(UiUtil.java:99)

on sormas-ui/login, which is absurd cuz why is it trying to fetch user roles when i haven't even submitted login form? something is wrong somewhere
