### ISSUE TITLE
Deployment of sormas-ear fails with Payara 5.201

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#1682]
### Bug Description
When deploying _sormas-ear_ on Payara 5.201, I get the following exception:

-----

2020-03-27T15:40:01.754+0100|INFORMATION: I154001.753|     > Starting automatic database update... (de.symeda.sormas.backend.common.StartupShutdownService.java:404)

2020-03-27T15:40:01.888+0100|SCHWERWIEGEND: Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:689)
...
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:542)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:687)
	... 46 more
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.common.StartupShutdownService.updateDatabase(StartupShutdownService.java:413)
	at de.symeda.sormas.backend.common.StartupShutdownService.startup(StartupShutdownService.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:529)
	... 48 more

-----

Debugging of the line `File schemaFile = new File(getClass().getClassLoader().getResource(schemaFileName).getFile());` showed, that `getClass().getClassLoader().getResource(schemaFileName)` does return `null`.

### Steps to Reproduce
1. Set up a new domain with _Payara 5.201_ by script
2. Deploy _sormas-ear_

### System Details
* Device: Windows
* SORMAS version: 1.35.0, 1.37.0-SNAPSHOT (= HEAD)
* Payara version: 5.201
* Java version: zulu8.44.0.9-jdk8.0.242

### Additional Information
* Deployment with Eclipse and as autodeploy/sormas-ear fails
* I used the setup script of 1.35.0 with Payara 5.192 and 5.201, and it is only running with 5.192

**Comment by HolgerReiseVSys** [comment]
Fixed as side effect of #1683 
With the old payara it _is_ a refactoring...
