### ISSUE TITLE
ContactVisitsView: NullPointerException

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1745]
### Bug Description

> Caused by: java.lang.NullPointerException: null
> at de.symeda.sormas.ui.utils.AbstractView.navigateTo(AbstractView.java:113)
> at de.symeda.sormas.ui.contact.ContactVisitsView.lambda$null$0(ContactVisitsView.java:120)
> at de.symeda.sormas.ui.visit.VisitController$3.onCommit(VisitController.java:111)
> at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:477)
> at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:345)
> at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:367)
> at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:241)
> at sun.reflect.GeneratedMethodAccessor1288.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
> ... 86 common frames omitted

### Steps to Reproduce
Unknown. Received via server error reporting.

### System Details
* SORMAS version: 1.37.1, 1.39.x

**Comment by ChristopherRiedelSymeda** [comment]
I can't find anything wrong here.

**Comment by MateStrysewskeSym** [comment]
Still happening on the Nigerian server.

**Comment by StefanKock** [comment]
Recent StackTrace on 1.39.x of 2020-05-07:
```
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.utils.AbstractView.navigateTo(AbstractView.java:125)
at de.symeda.sormas.ui.contact.ContactVisitsView.lambda$null$2(ContactVisitsView.java:157)
at de.symeda.sormas.ui.visit.VisitController$3.onCommit(VisitController.java:111)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:477)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:345)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:367)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:241)
at sun.reflect.GeneratedMethodAccessor1811.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
