### ISSUE TITLE
Unable to run Android App - checkcompatibilty issue

### ISSUE THREAD

**Issue by greyashes** [hzi-braunschweig/SORMAS-Project#1767]
We have installed the backend & everything s working fine..we are unable to get the app to work:-

![image](https://user-images.githubusercontent.com/5275620/78682460-a3ec6080-790b-11ea-9b39-bca9dbce424c.png)

Error message:
2020-04-07 13:57:29.578 30768-30878/de.symeda.sormas.app.debug E/de.symeda.sormas.app.rest.RetroProvider$1: Error executing an async task
    de.symeda.sormas.app.rest.ServerCommunicationException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at de.symeda.sormas.app.rest.RetroProvider.throwException(RetroProvider.java:759)
        at de.symeda.sormas.app.rest.RetroProvider.checkCompatibility(RetroProvider.java:255)

**Comment by MartinWahnschaffeSymeda** [comment]
@greyashes Looks like you have to change the url. I guess https://idms.life/sormas-rest/ should work.

**Comment by VitaliHZI** [comment]
Hey @greyashes  do you still have this problem? Or can we close this issue? :)
