### ISSUE TITLE
Server configuration and deploy

### ISSUE THREAD

**Issue by aleshchik** [hzi-braunschweig/SORMAS-Project#1901]
### Description
Currently, I'm installing SORMAS server locally and had the same issues as in #1876
I was able to install the server with some script modification - I created DB manually and ran SQL from files.
After that, I ran the server-update script but got a lot of errors during the deploy.

### Screenshots
I had this error earlier, but now it's gone and I just see the 404
![ui_class_not_found](https://user-images.githubusercontent.com/26214521/80072393-da9eb980-854e-11ea-8dd3-500691f12ad4.png)

### System Details
* Ubuntu 20.04:
* SORMAS version: v1.38.0 (also tried to build from development branch - the result is the same)
* Java version: OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-linux64) (build 25.202-b05, mixed mode)

### Deploy logs

[2020-04-23T11:03:39.819+0300] [Payara 5.192] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=157 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1587629019819] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:736)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:438)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	... 
	... 
Caused by: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:564)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:78)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:734)
	... 36 more
Caused by: java.lang.RuntimeException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
	at de.symeda.sormas.api.FacadeProvider.lookupEjbRemote(FacadeProvider.java:261)
	at de.symeda.sormas.api.FacadeProvider.getConfigFacade(FacadeProvider.java:181)
	at de.symeda.sormas.ui.StartupShutdownService.startup(StartupShutdownService.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1047)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:206)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:206)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:998)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:417)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:380)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2087)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:555)
	... 38 more
Caused by: javax.naming.NamingException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: ConfigFacade not found]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at de.symeda.sormas.api.FacadeProvider.lookupEjbRemote(FacadeProvider.java:259)
	... 68 more
## Caused by: javax.naming.NameNotFoundException: ConfigFacade not found
	at com.sun.enterprise.naming.impl.TransientContext.doLookup(TransientContext.java:237)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:204)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:70)
	at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
	... 72 more
]]

[2020-04-23T11:22:05.193+0300] [Payara 5.192] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=47 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1587630125193] [levelValue: 1000] [[
  Exception during lifecycle processing
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:736)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:438)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:169)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:294)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:357)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:535)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:542)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:149)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:532)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:437)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:371)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:362)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:564)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:78)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:734)
	... 36 more
Caused by: javax.ejb.EJBTransactionRolledbackException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2414)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2196)	
	... 38 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
	... 72 more
### Caused by: java.lang.IllegalArgumentException: No enum constant de.symeda.sormas.api.feature.FeatureType.TASK_GENERATION_GENERAL
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.fromName(EnumJavaTypeDescriptor.java:84)
	at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.wrap(EnumJavaTypeDescriptor.java:54)
	at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.wrap(EnumJavaTypeDescriptor.java:16)
	at org.hibernate.type.descriptor.sql.VarcharTypeDescriptor$2.doExtract(VarcharTypeDescriptor.java:62)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	...
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 70 more
]]

Thanks in advance,
Alex

**Comment by HolgerReiseVSys** [comment]
>  Initialization failed for Singleton StartupShutdownService
This usually happens when the war file is deployed and the ear failed to deploy.

**Comment by HolgerReiseVSys** [comment]
> "No enum constant de.symeda.sormas.api.feature.FeatureType.TASK_GENERATION_GENERAL"

Deploying the ear also updates the database to the current version, which is not backwards compatible.
`FeatureType.TASK_GENERATION_GENERAL` has just been introduces to the development branch, so the old version of the ear gets stuck.

**Comment by HolgerReiseVSys** [comment]
Wen cannot see a clear cause for the `ClassNotFoundException` from the screenshot.
Please make sure that, after the `sormas-ui.war` has been deployed, `/opt/domains/sormas/applications/sormas-ui/WEB-INF/lib/vaadin-server.jar` is present.
Maybe you could provide the corresponding stack trace from the server logs.

**Comment by Crankuphigh** [comment]
@aleshchik were you able to deploy without any modifications?
I'm facing the same errors trying to deploy even without doing any modifications. (same java version but on ubuntu 18.04)

**Comment by aleshchik** [comment]
a few days ago I tried to deploy the server again and found a problem in java version.
https://bugs.openjdk.java.net/browse/JDK-8213936
I installed 1.8.0_181 and it works now!!!
