### ISSUE TITLE
Contacts Dashboard: SQL Syntax Exception when only Contacts without Case

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1916]
### Bug Description
When filtering the ContactsDashboard for a period with only Contacts without Case, a PSQLException occurs because in `updateCaseCountsAndSourceCasesLabels::updateCaseCountsAndSourceCasesLabels` the `caseIds` list, is used for filtering with `in()` despite being empty.

See <https://hibernate.atlassian.net/browse/HHH-8091>

This is probably due to the Contacts-without-Case feature.

### Steps to Reproduce
1. Open Contacts Dashboard
2. Select a period with only Contacts without Case

### System Details
* SORMAS version: 1.39.0-SNAPSHOT

### Additional Information
<details><summary>Trimmed Stacktrace</summary>

``` java
Invocation of method valueChange in de.symeda.sormas.ui.dashboard.DashboardFilterLayout$$Lambda$910/0x0000000801a8bc40 failed. (de.symeda.sormas.ui.SormasErrorHandler.java:78)
com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in de.symeda.sormas.ui.dashboard.DashboardFilterLayout$$Lambda$910/0x0000000801a8bc40 failed.
	[...]
	at com.vaadin.v7.ui.AbstractField.fireValueChange(AbstractField.java:1134)
	[...]
	at com.vaadin.v7.ui.ComboBox.changeVariables(ComboBox.java:743)
	[...]
Caused by: javax.ejb.EJBTransactionRolledbackException: null
	at de.symeda.sormas.api.contact._ContactFacade_Wrapper.getContactCountsByCasesForDashboard(de/symeda/sormas/api/contact/_ContactFacade_Wrapper.java)
	at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.updateCaseCountsAndSourceCasesLabels(ContactsDashboardView.java:174)
	at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.refreshDashboard(ContactsDashboardView.java:362)
	at de.symeda.sormas.ui.dashboard.DashboardFilterLayout.lambda$2(DashboardFilterLayout.java:155)
	[...]
Caused by: javax.transaction.TransactionRolledbackException: CORBA TRANSACTION_ROLLEDBACK 9998 Maybe; nested exception is: 
	org.omg.CORBA.TRANSACTION_ROLLEDBACK: ----------BEGIN server-side stack trace----------
org.omg.CORBA.TRANSACTION_ROLLEDBACK:   vmcid: 0x2000  minor code: 1806 completed: Maybe
	[...]
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	[...]
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1538)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
	at de.symeda.sormas.backend.contact.ContactFacadeEjb.getContactCountsByCasesForDashboard(ContactFacadeEjb.java:597)
	[...]
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2171)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1934)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896)
	at org.hibernate.loader.Loader.doQuery(Loader.java:936)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:339)
	at org.hibernate.loader.Loader.doList(Loader.java:2693)
	at org.hibernate.loader.Loader.doList(Loader.java:2676)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2510)
	at org.hibernate.loader.Loader.list(Loader.java:2505)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1561)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
	... 143 more
Caused by: org.postgresql.util.PSQLException: FEHLER: Syntaxfehler bei �)�
  Position: 91
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	[...]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	... 158 more
```

</details>

**Comment by StefanKock** [comment]
Reviewed, added a small unit test when no data is present
