### ISSUE TITLE
Deployment of sormas-ear fails with 1.39.0 and PostgreSQL 9.5

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#1952]
### Steps to Reproduce
1. Deploy 1.39.0 on a system with 1.38.0 and wait for autodeploy of sormas-ear failing.

### StackTrace

[2020-04-29T17:08:31.298+0200] [Payara 5.192] [SCHWERWIEGEND] [] [javax.enterprise.system.core] [tid: _ThreadID=68 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1588172911298] [levelValue: 1000] [[
  Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
        at 
...
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "NOT"
  Position: 35
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
        at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:428)
        at com.sun.proxy.$Proxy555.executeUpdate(Unknown Source)
        at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:127)
        at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:437)
        at com.sun.proxy.$Proxy556.executeUpdate(Unknown Source)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
        ... 72 more
]]

### System Details
* Device:
* SORMAS version: 1.39.0
* Android version/Browser:
* PostgreSQL: 9.5

### Additional Information
Run command manually.

**Comment by StefanKock** [comment]
Workaround: Run database commands of `sormas_schema.sql` from the last schema_version present on your system up to numer 201. If the `contact.quarantineto` fields are present, you only need to insert the schema_version, if not please run these alter command before:
`ALTER TABLE contact ADD COLUMN quarantineto timestamp;`
`ALTER TABLE contact_history ADD COLUMN quarantineto timestamp;`

**Comment by MartinWahnschaffeSymeda** [comment]
@StefanKock Please review

**Comment by StefanKock** [comment]
Looks okay for me, that the deletion and restore of `COLUMN quarantineto` is commented out. Since it is dokumented that version 1.39.x had problems with PostgreSQL 9.5, it is good workaround.
