### ISSUE TITLE
Still errors in server-update.sh

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#1996]
### Bug Description
More hours and days trying to install Sormas. I think I am almost there. I could run the whole server-setup.sh script without errors. 
However, during server-update.sh I get many error messages, that I don't know what to do with. 
server.log file is attached. 
I hope someone could help me out, so I can finally finish this installation and get my hands dirty on sormas. 

Autodeploy failed : /opt/domains/sormas/autodeploy/sormas-ui.war.]]

### System Details
* Device: ubuntu 20.20
* SORMAS version: 1.39.2
### Additional Information
postgresql 10

**Comment by RafaelKluender** [comment]
[setup.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/4593040/setup.log)

**Comment by RafaelKluender** [comment]
[server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/4593052/server.log)

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Which Java version and Payara version are you using exactly (including the build number, not only the major version number)?

**Comment by RafaelKluender** [comment]
Dear Mate, 
My Java is: 
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-linux64) (build 25.252-b14, mixed mode)

My Payara is: 
Payara 5.192.0
Running Payara Version: Payara Server  5.192 #badassfish (build 115)]]

Is this the information you need? Is there some incompatibility?

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Is Zulu the only Java instance that's running on your system? Or do you also have an Oracle Java instance installed?

**Comment by RafaelKluender** [comment]
> 
> 
> @RafaelKluender Is Zulu the only Java instance that's running on your system? Or do you also have an Oracle Java instance installed?

No, I did not install Oracle Java. I have installed a fresh Ubuntu 20.20 server, barebone with nothing else then Sormas. The only things installed are what was required for Sormas.

**Comment by MateStrysewskeSym** [comment]
Okay, we'll look into this. Your Java and Payara versions seem fine for me.

@HolgerReiseVSys @StefanKock Does one of you two have any idea what this could be about? The error seems to be this one:

```
java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V
	at sun.security.ssl.SSLSocketImpl.initHandshaker(SSLSocketImpl.java:1350)
	at sun.security.ssl.SSLSocketImpl.doneConnect(SSLSocketImpl.java:708)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:583)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:110)
	at org.postgresql.ssl.WrappedFactory.createSocket(WrappedFactory.java:42)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:36)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:441)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:97)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:82)
	at org.postgresql.ds.PGConnectionPoolDataSource.getPooledConnection(PGConnectionPoolDataSource.java:58)
	at com.sun.gjc.spi.CPManagedConnectionFactory.createManagedConnection(CPManagedConnectionFactory.java:136)
	at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:87)
	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:920)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1209)
	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
	at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:287)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1532)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:957)
	at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:235)
	at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:528)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:386)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:175)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:900)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:931)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
	at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:207)
	at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:114)
	at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:225)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
	at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:240)
	at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:170)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
	at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:309)
	at org.glassfish.javaee.full.deployment.EarDeployer.access$200(EarDeployer.java:88)
	at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:155)
	at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:152)
	at org.glassfish.javaee.full.deployment.EarDeployer.doOnBundles(EarDeployer.java:232)
	at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllTypedBundles(EarDeployer.java:241)
	at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:267)
	at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:152)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:432)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:540)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:557)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:553)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:552)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:583)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:575)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:574)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1483)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:119)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1865)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:149)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:532)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:437)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:371)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:362)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]
```

**Comment by StefanKock** [comment]
The Java version 8u252 is the problem, see #1765. It is working with 8u202.
