### ISSUE TITLE
EventFacade.saveEvent: PSQLException: value too long for type character varying(512)

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2018]
### Bug Description
512 characters are probably not enough for some of the details fields. We need to think about generally increasing these limits for all fields.

This issue occurs when persisting an `Event`:
```
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 148 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.DataException:
could not execute statement
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1489)
at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1469)
at com.sun.enterprise.container.common.impl.EntityManagerWrapper.flush(EntityManagerWrapper.java:437)
at de.symeda.sormas.backend.common.AbstractAdoService.ensurePersisted(AbstractAdoService.java:309)
at sun.reflect.GeneratedMethodAccessor2179.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 146 more
Caused by: org.hibernate.exception.DataException: could not execute statement
at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
...
at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1483)
... 177 more
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character
varying(512)
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
...
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
... 185 more
```
### Steps to Reproduce
Typing or pasting long text into a `TextField` or `TextArea` when creating or editing an event.

### Expected Behavior
```
TextArea field;
// define as constant:
int maxLength = 512; 
field.addValidator(new StringLengthValidator("meaningfulValidationMessage", 0, maxLength, true));
```
This avoids sending too long Strings to the backend and tells the user when saving what is the problem. It is a better idea than `field.setMaxLength(maxLength)` because this automatically trims copy-paste content without user notification.
Even if there will be more characters allowed, this validation will stay useful.

### System Details
* SORMAS version: 1.39.x and earlier

### To be reviewed
@StefanKock

**Comment by markusmann-vg** [comment]
Think of a solution, where we allow: 32.767 chars for a text-field as this is the maximum number that can be shown within an Excel cell (considering Export)

**Comment by StefanKock** [comment]
> Think of a solution, where we allow: 32.767 chars for a text-field as this is the maximum number that can be shown within an Excel cell (considering Export)

This could be considered for #580 or a new feature, but not for this bugfix to avoid exceptions.
