### ISSUE TITLE
VisitController$3.onCommit: NullPointerException

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2020]
### Bug Description
Stack Trace:
```
...
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.GeneratedMethodAccessor1132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
... 77 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
buttonClick in de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
...
at com.vaadin.ui.Button$1.click(Button.java:57)
... 81 common frames omitted
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.utils.AbstractView.navigateTo(AbstractView.java:125)
at de.symeda.sormas.ui.contact.ContactVisitsView.lambda$null$2(ContactVisitsView.java:157)
at de.symeda.sormas.ui.visit.VisitController$3.onCommit(VisitController.java:111)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:477)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:345)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:367)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:241)
at sun.reflect.GeneratedMethodAccessor1811.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
### Steps to Reproduce
unknown

### System Details
* SORMAS version: 1.39.x

**Comment by StefanKock** [comment]
Duplicate to #1745
