### ISSUE TITLE
FeatureConfigurationFacadeEjb.saveFeatureConfiguration: ConstraintViolationException: AbstractAdoService.getByUuid: uuid is null 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2064]
### Bug Description
Fount in Log:
```
2020-05-11 14:03:10,239 ERROR USER http-thread-pool::http-listener-1(45) d.s.sormas.ui.SormasErrorHandler - Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
...
Caused by: javax.ejb.EJBTransactionRolledbackException: null
        at de.symeda.sormas.api.feature._FeatureConfigurationFacade_Wrapper.saveFeatureConfigurations(de/symeda/sormas/api/feature/_FeatureConfigurationFacade_Wrapper.java)
        at de.symeda.sormas.ui.configuration.linelisting.LineListingConfigurationEditLayout.lambda$buildButtonLayout$b4b594c5$2(LineListingConfigurationEditLayout.java:122)
        at sun.reflect.GeneratedMethodAccessor56354.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
...
        at de.symeda.sormas.backend.feature.FeatureConfigurationFacadeEjb.saveFeatureConfiguration(FeatureConfigurationFacadeEjb.java:165)
        at de.symeda.sormas.backend.feature.FeatureConfigurationFacadeEjb.saveFeatureConfigurations(FeatureConfigurationFacadeEjb.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor55323.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor55319.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
        at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
        ... 109 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
        at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
        ... 145 more
...
Caused by: javax.validation.ConstraintViolationException: 1 constraint violation(s) occurred during method validation.
Constructor or Method: public de.symeda.sormas.backend.common.AbstractDomainObject de.symeda.sormas.backend.common.AbstractAdoService.getByUuid(java.lang.String)
Argument values: [null]
Constraint violations:
 (1) Kind: PARAMETER
 parameter index: 0
 message: darf nicht null sein
 root bean: de.symeda.sormas.backend.feature.FeatureConfigurationService@3184c904
 property path: getByUuid.arg0
 constraint: @javax.validation.constraints.NotNull(message={javax.validation.constraints.NotNull.message}, payload=[], groups=[])
        at org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:74)
        at sun.reflect.GeneratedMethodAccessor55982.invoke(Unknown Source)
```
### Steps to Reproduce
1.
2.

### System Details
* SORMAS version: 1.39.2

### Additional Information
DEMO instance sormas.symeda.de
Seems to be overlooked by #1867.

**Comment by StefanKock** [comment]
With @MateStrysewskeSym discussed that we should fix this before release

**Comment by StefanKock** [comment]
Reviewed
