### ISSUE TITLE
Avoid exceptions when opening views without correct identifier

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2065]
### Problem Description
NullPointerExceptions (NPE) occur when calling a view without the proper uuid.
Examples (not complete):
- SampleDataView -> AbstractSampleView
- SampleDataView.enter -> SampleController.getSampleEditComponent
- SampleEditForm.lambda$addFields (around line 221)
- AbstractEventView?
- AbstractContactView.refreshMenu:52
- PortHealthInfoView.enter -> CaseController.getPortHealthInfoComponent

### Proposed Change
Like with views inherited of `AbstractCaseView` (see #2017), avoid NPEs and fall back to a useful listing view.

### Additional Information
Example StackTrace:
```
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
... 77 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
uriFragmentChanged in
com.vaadin.navigator.Navigator$UriFragmentManager$$Lambda$495/1142449985 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.Page.fireEvent(Page.java:699)
at com.vaadin.server.Page.updateLocation(Page.java:1123)
at com.vaadin.ui.UI$1.popstate(UI.java:206)
... 82 common frames omitted
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.samples.AbstractSampleView.refreshMenu(AbstractSampleView.java:51)
at de.symeda.sormas.ui.utils.AbstractSubNavigationView.enter(AbstractSubNavigationView.java:72)
at de.symeda.sormas.ui.samples.SampleDataView.enter(SampleDataView.java:58)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
at com.vaadin.navigator.View.beforeLeave(View.java:79)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
at com.vaadin.navigator.Navigator$UriFragmentManager.lambda$setNavigator$567eee34$1(Navigator.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 87 common frames omitted
```

### Review
@StefanKock

**Comment by StefanKock** [comment]
@BarnaBartha and I talked about this today what I brought up in the pull request.

> I have some concerns how you did it:
>
> 1. You removed the `redirectSimpleModeToCaseDataView` from case-dependent views without explanation.
> 2. You altered views that do not use UUIDs as parameters (`AbstractConfigurationView`, `AbstractStatisticsView` and their subclasses).
> 3. It feels still quite smelly how often uuids are read out of the parameters.

After clarifying with @MateStrysewskeSym the SimpleMode shall not to be removed. 

I will take over this ticket since @BarnaBartha needs to take care for other tickets.

**Comment by StefanKock** [comment]
Reviewed by @BarnaBartha, integrated in development by me.
