### ISSUE TITLE
Forms throw ReadOnlyException when trying to update calculated fields

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2072]
### Bug Description
There are at least some forms that throw ReadOnlyException, possibly because calculated or dependent fields are tried to be updated after the form is set to readOnly:
1. `PersonEditForm.updateListOfDays`
2. `ContactDataForm.updateDiseaseConfiguration`
3. `CaseDataForm.lambda$addFields`
4. `SymptomsForm$2.buttonClick` (around line 440 on older code)
5. `SampleEditForm.updateRequestedTestFields`

### Steps to Reproduce
not reproduced yet

### Expected Behavior
Show the respective form with the same data as in edit mode.
It seems that there is an architectual / timing problem when handling with readOnly forms.

### System Details
* SORMAS version: 1.39.x and older versions since months

### Additional Information
StackTraces:
```
2020-05-11 21:02:19,186 ERROR ...
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
valueChange in de.symeda.sormas.ui.person.PersonEditForm$$Lambda$939/397190702 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.v7.ui.AbstractField.fireValueChange(AbstractField.java:1134)
at com.vaadin.v7.ui.AbstractField.setPropertyDataSource(AbstractField.java:662)
at com.vaadin.v7.data.fieldgroup.FieldGroup.bind(FieldGroup.java:277)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.bind(BeanFieldGroup.java:163)
at com.vaadin.v7.data.fieldgroup.FieldGroup.bindFields(FieldGroup.java:117)
at com.vaadin.v7.data.fieldgroup.FieldGroup.setItemDataSource(FieldGroup.java:107)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.setItemDataSource(BeanFieldGroup.java:134)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.setItemDataSource(BeanFieldGroup.java:127)
at de.symeda.sormas.ui.utils.AbstractEditForm.setInternalValue(AbstractEditForm.java:174)
at de.symeda.sormas.ui.utils.AbstractEditForm.setInternalValue(AbstractEditForm.java:54)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:500)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:427)
at de.symeda.sormas.ui.utils.AbstractEditForm.setValue(AbstractEditForm.java:157)
at de.symeda.sormas.ui.person.PersonController.getPersonEditComponent(PersonController.java:93)
at de.symeda.sormas.ui.caze.CasePersonView.enter(CasePersonView.java:49)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
...
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
Caused by: com.vaadin.v7.data.Property$ReadOnlyException: null
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:467)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:705)
at com.vaadin.v7.ui.AbstractSelect.removeAllItems(AbstractSelect.java:871)
at de.symeda.sormas.ui.person.PersonEditForm.updateListOfDays(PersonEditForm.java:393)
at de.symeda.sormas.ui.person.PersonEditForm.lambda$addFields$fce7796d$1(PersonEditForm.java:355)
at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 117 common frames omitted
```
```
2020-05-11 17:23:55,506 d.s.sormas.ui.SormasErrorHandler - Invocation of
method valueChange in de.symeda.sormas.ui.contact.ContactDataForm$$Lambda$988/1747875216
failed.
com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in
de.symeda.sormas.ui.contact.ContactDataForm$$Lambda$988/1747875216 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.v7.ui.AbstractField.fireValueChange(AbstractField.java:1134)
at com.vaadin.v7.ui.AbstractField.setPropertyDataSource(AbstractField.java:662)
at com.vaadin.v7.data.fieldgroup.FieldGroup.bind(FieldGroup.java:277)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.bind(BeanFieldGroup.java:163)
at com.vaadin.v7.data.fieldgroup.FieldGroup.bindFields(FieldGroup.java:117)
at com.vaadin.v7.data.fieldgroup.FieldGroup.setItemDataSource(FieldGroup.java:107)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.setItemDataSource(BeanFieldGroup.java:134)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.setItemDataSource(BeanFieldGroup.java:127)
at de.symeda.sormas.ui.utils.AbstractEditForm.setInternalValue(AbstractEditForm.java:174)
at de.symeda.sormas.ui.utils.AbstractEditForm.setInternalValue(AbstractEditForm.java:54)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:500)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:427)
at de.symeda.sormas.ui.utils.AbstractEditForm.setValue(AbstractEditForm.java:157)
at de.symeda.sormas.ui.contact.ContactController.getContactDataEditComponent(ContactController.java:234)
at de.symeda.sormas.ui.contact.ContactDataView.enter(ContactDataView.java:88)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:726)
...
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.vaadin.v7.data.Property$ReadOnlyException: null
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:467)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.OptionGroup.setValue(OptionGroup.java:163)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:705)
at com.vaadin.v7.ui.AbstractSelect.removeAllItems(AbstractSelect.java:871)
at de.symeda.sormas.ui.utils.FieldHelper.updateEnumData(FieldHelper.java:359)
at de.symeda.sormas.ui.contact.ContactDataForm.updateDiseaseConfiguration(ContactDataForm.java:444)
at de.symeda.sormas.ui.contact.ContactDataForm.lambda$addFields$12ede5da$3(ContactDataForm.java:226)
at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 99 common frames omitted
```
```
2020-05-05 18:12:30,895  d.s.sormas.ui.SormasErrorHandler - Unable to
invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
...
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
... 77 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
buttonClick in de.symeda.sormas.ui.caze.CaseDataForm$$Lambda$766/723003149 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.ui.Button.fireClick(Button.java:384)
at com.vaadin.ui.Button$1.click(Button.java:57)
... 81 common frames omitted
Caused by: com.vaadin.v7.data.Property$ReadOnlyException: null
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:467)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:427)
at com.vaadin.v7.ui.AbstractTextField.setValue(AbstractTextField.java:458)
at de.symeda.sormas.ui.caze.CaseDataForm.lambda$addFields$79e2e76$1(CaseDataForm.java:205)
at sun.reflect.GeneratedMethodAccessor1905.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
```
2020-04-10 10:24:16,855 ERROR d.s.sormas.ui.SormasErrorHandler - Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
...
Caused by: com.vaadin.v7.data.Property$ReadOnlyException: null
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:467)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.OptionGroup.setValue(OptionGroup.java:163)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:705)
at de.symeda.sormas.ui.symptoms.SymptomsForm$2.buttonClick(SymptomsForm.java:440)
at sun.reflect.GeneratedMethodAccessor1965.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
```
2020-03-11 12:19:39,675 ERROR ...
Caused by: com.vaadin.v7.data.Property$ReadOnlyException: null
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:467)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
at com.vaadin.v7.ui.OptionGroup.setValue(OptionGroup.java:163)
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:705)
at com.vaadin.v7.ui.AbstractField.clear(AbstractField.java:1493)
at de.symeda.sormas.ui.samples.SampleEditForm.updateRequestedTestFields(SampleEditForm.java:252)
at de.symeda.sormas.ui.samples.SampleEditForm.lambda$initializeRequestedTestFields$12ede5da$1(SampleEditForm.java:316)
at sun.reflect.GeneratedMethodAccessor1095.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 99 common frames omitted
```

**Comment by StefanKock** [comment]
There happen quite a lot of these exceptions, I would like to get rid of that asasp.

**Comment by MateStrysewskeSym** [comment]
This happens when the user who opens the view does not have the necessary user right to edit the page. An example would be National Observers who by default don't have the right to edit any data. It does not effect the new feature to set the form to read-only if it's outside the jurisdiction of the user because that happens after the form has been initialised.
