### ISSUE TITLE
DashboardMapComponent.showContactMarkers: NPE

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2074]
### Bug Description
Some NullPointerExceptions happened when `DashboardMapComponent` is used.

### Steps to Reproduce
unknown

### System Details
* SORMAS version: 1.39.x

### Additional Information
contact is null or contact.getCaseReportDate() is null

StackTrace:
```
2020-05-06 20:03:18,042 ERROR d.s.sormas.ui.SormasErrorHandler - Invocation
of method valueChange in
de.symeda.sormas.ui.dashboard.map.DashboardMapComponent$$Lambda$748/2106623609 failed.
com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in
de.symeda.sormas.ui.dashboard.map.DashboardMapComponent$$Lambda$748/2106623609 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
...
at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:705)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.updatePeriodFilters(DashboardMapComponent.java:678)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.lambda$createPeriodFilters$f9952e38$1(DashboardMapComponent.java:514)
at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 85 common frames omitted
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.showContactMarkers(DashboardMapComponent.java:1212)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.refreshMap(DashboardMapComponent.java:245)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.lambda$createPeriodFilters$8d34cc34$1(DashboardMapComponent.java:563)
at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 99 common frames omitted
```

**Comment by MartinWahnschaffeSymeda** [comment]
Reviewed. Having a fallback to the contact report date when no case is associated to the contact seems to make sense.
