### ISSUE TITLE
Error when trying to create a new case from a positive lab result

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2089]
### Bug Description
Create a new positive lab result for a disease different from that of the initial case
### Steps to Reproduce
1.
2.

### System Details
* Device:1.39.2
* Android version/Browser:

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/81809136-24147000-9521-11ea-81bc-8924650ec19b.png)

**Comment by StefanKock** [comment]
It seems that a person Entity is not set for a contact to persist.
Corresponding StackTrace:
```
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.caze.__CaseFacade_Remote_DynamicStub.cloneCase(de/symeda/sormas/api/caze/__CaseFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.caze._CaseFacade_Wrapper.cloneCase(de/symeda/sormas/api/caze/_CaseFacade_Wrapper.java)
at de.symeda.sormas.ui.samples.PathogenTestController.lambda$showCaseCloningWithNewDiseaseDialog$3(PathogenTestController.java:165)
at de.symeda.sormas.ui.utils.VaadinUiUtil$3.onConfirm(VaadinUiUtil.java:162)
at de.symeda.sormas.ui.utils.ConfirmationComponent$1.buttonClick(ConfirmationComponent.java:72)
at sun.reflect.GeneratedMethodAccessor7712.invoke(Unknown Source)
...
at com.sun.proxy.$Proxy687.saveContact(Unknown Source)
at de.symeda.sormas.backend.contact.__EJB31_Generated__ContactFacadeEjb$ContactFacadeEjbLocal__Intf____Bean__.saveContact(Unknown
Source)
at de.symeda.sormas.backend.caze.CaseFacadeEjb.mergeCase(CaseFacadeEjb.java:2131)
at de.symeda.sormas.backend.caze.CaseFacadeEjb.cloneCase(CaseFacadeEjb.java:2230)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
at com.sun.proxy.$Proxy721.ensurePersisted(Unknown Source)
at de.symeda.sormas.backend.contact.__EJB31_Generated__ContactService__Intf____Bean__.ensurePersisted(Unknown
Source)
at de.symeda.sormas.backend.contact.ContactFacadeEjb.saveContact(ContactFacadeEjb.java:241)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
at de.symeda.sormas.backend.common.AbstractAdoService.ensurePersisted(AbstractAdoService.java:307)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1483)
... 210 more
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "person_id"
violates not-null constraint
  Detail: Failing row contains (178949, 2020-05-14 00:41:58.08, CLOTHES_OR_OTHER,
2020-05-14 00:41:58.08, 2020-05-11 00:00:00, 2020-05-12 17:02:19.581,
S55PSH-YCXGQJ-S4PEF7-HGHWKEGQ, 178940, null, 140208, null, null, CONFIRMED, LOST,
2020-05-25 00:00:00, null, ["2020-05-14 00:41:57.857734+02",), null, null, blabla, null,
DROPPED, null, null, f, null, null, 92893, 92947, f, null, null, null, null, null,
CORONAVIRUS, null, null, null, null, null, t, null, null, f, f, null, null, null, null,
null, null, null).
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
...
```

**Comment by StefanKock** [comment]
Reviewed
