### ISSUE TITLE
AbstractAdoService.getUser returns null: NPE in *Service.createUserFilter

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2103]
### Bug Description
There happen sometimes (very rarely) NPEs when `createUserFilter` is called.

Problem: `User currentUser = getCurrentUser()` returns `null`, but in the log is a username present.
It happened on:
- `EventService.createUserFilter(EventService.java:262)` (1.39.x)
- `TaskService.createUserFilter(TaskService.java:113)` (1.38.x)
- `UserProvider.getUserName(UserProvider.java:86)`(1.38.x)
- `DiseaseConfigurationFacadeEjb.getAllDiseases(DiseaseConfigurationFacadeEjb.java:81)` (1.38.x)
- `LoginHelper.login(LoginHelper.java:65)` (1.38.x, 1.40.x)

The user caching was introduced in #1597.

```
2020-05-13 13:42:59,261 ERROR USERNAME  d.s.sormas.ui.SormasErrorHandler - Unable to
invoke method poll in com.vaadin.shared.ui.ui.UIServerRpc
... 81 common frames omitted
Caused by: javax.ejb.EJBTransactionRolledbackException: null
at de.symeda.sormas.api.event._EventFacade_Wrapper.getNewEventsForDashboard(de/symeda/sormas/api/event/_EventFacade_Wrapper.java)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.refreshDataForSelectedDisease(DashboardDataProvider.java:119)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.setDisease(DashboardDataProvider.java:263)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.changeSelectedDisease(SurveillanceDiseaseCarouselLayout.java:183)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.setActiveDisease(SurveillanceDiseaseCarouselLayout.java:179)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.lambda$changeAutoSlideOption$971318fd$1(SurveillanceDiseaseCarouselLayout.java:214)
at sun.reflect.GeneratedMethodAccessor3416.invoke(Unknown Source)
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.event.__EventFacade_Remote_DynamicStub.getNewEventsForDashboard(de/symeda/sormas/api/event/__EventFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.event._EventFacade_Wrapper.getNewEventsForDashboard(de/symeda/sormas/api/event/_EventFacade_Wrapper.java)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.refreshDataForSelectedDisease(DashboardDataProvider.java:119)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.setDisease(DashboardDataProvider.java:263)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.changeSelectedDisease(SurveillanceDiseaseCarouselLayout.java:183)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.setActiveDisease(SurveillanceDiseaseCarouselLayout.java:179)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.lambda$changeAutoSlideOption$971318fd$1(SurveillanceDiseaseCarouselLayout.java:214)
at sun.reflect.GeneratedMethodAccessor3416.invoke(Unknown Source)
...
Caused by: javax.ejb.EJBTransactionRolledbackException
at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2414)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2196)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2117)
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
at com.sun.proxy.$Proxy449.getNewEventsForDashboard(Unknown Source)
at de.symeda.sormas.backend.event.__EJB31_Generated__EventService__Intf____Bean__.getNewEventsForDashboard(Unknown
Source)
at de.symeda.sormas.backend.event.EventFacadeEjb.getNewEventsForDashboard(EventFacadeEjb.java:136)
at sun.reflect.GeneratedMethodAccessor1500.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 112 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 146 more
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.event.EventService.createUserFilter(EventService.java:262)
at de.symeda.sormas.backend.event.EventService.getNewEventsForDashboard(EventService.java:125)
at sun.reflect.GeneratedMethodAccessor1501.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 144 more
```
```
2020-04-23 16:41:32,162 ERROR USERNAME
...
at de.symeda.sormas.backend.task.__EJB31_Generated__TaskService__Intf____Bean__.createUserFilter(Unknown
Source)
at de.symeda.sormas.backend.task.TaskFacadeEjb.count(TaskFacadeEjb.java:287)
at sun.reflect.GeneratedMethodAccessor3670.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 134 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 168 more
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.task.TaskService.createUserFilter(TaskService.java:113)
at sun.reflect.GeneratedMethodAccessor3663.invoke(Unknown Source)
...
```
```
2020-04-23 16:41:39,792 ERROR USERNAME d.s.sormas.ui.SormasErrorHandler - null
java.lang.NullPointerException: null
at de.symeda.sormas.ui.UserProvider.getUserName(UserProvider.java:86)
at de.symeda.sormas.ui.Menu.<init>(Menu.java:126)
at de.symeda.sormas.ui.MainScreen.<init>(MainScreen.java:120)
at de.symeda.sormas.ui.SormasUI.initMainScreen(SormasUI.java:74)
at de.symeda.sormas.ui.SormasUI.init(SormasUI.java:69)
at com.vaadin.ui.UI.doInit(UI.java:776)
```
```
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.disease.DiseaseConfigurationFacadeEjb.getAllDiseases(DiseaseConfigurationFacadeEjb.java:81)
at sun.reflect.GeneratedMethodAccessor1078.invoke(Unknown Source)
```
```
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.login.LoginHelper.login(LoginHelper.java:65)
at de.symeda.sormas.ui.login.LoginScreen.login(LoginScreen.java:296)
at de.symeda.sormas.ui.login.LoginScreen.lambda$buildLoginForm$c0970e2a$1(LoginScreen.java:190)
```
### Steps to Reproduce
unknown

### System Details
* SORMAS version: 1.39.x, 1.38.x

### Additional Information
Happened on Nigerian server, usernames ended often with "_SSO" (might be a coincidence).

**Comment by StefanKock** [comment]
@HolgerReiseVSys can you have a look on this defect?

**Comment by HolgerReiseVSys** [comment]
The last stack trace (LoginHelper) seems to suggest that even though the login has succeded, the user with the given user name cannot be found in the DB.
@MateStrysewskeSym Are there users with _SSO suffix in the DB? Is, besides SormasIdentityStore, an additional mechanism active?

**Comment by MateStrysewskeSym** [comment]
@HolgerReiseVSys Yes, there are 36 of those. Concerning your second question, I don't know exactly. Maybe @MartinWahnschaffeSymeda knows more.

**Comment by MateStrysewskeSym** [comment]
@StefanKock Do we still get error logs like these?

**Comment by StefanKock** [comment]
I happened last with `LoginHelper.login` on 2020-07-05 I think.

**Comment by MateStrysewske** [comment]
@StefanKock Do you know whether this happened again in the last months?

**Comment by StefanKock** [comment]
No exception data since 1,5 months, so I do not know.
