### ISSUE TITLE
DashboardMapComponent.showEventMarkers: NPE 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2113]
### Bug Description
Happened today morning on DEMO
```
2020-05-15 09:57:39,258 ERROR USERNAME d.s.sormas.ui.SormasErrorHandler - Unable to invoke
method poll in com.vaadin.shared.ui.ui.UIServerRpc
...
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.showEventMarkers(DashboardMapComponent.java:1284)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.refreshMap(DashboardMapComponent.java:249)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.refresh(SurveillanceDiseaseCarouselLayout.java:230)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.changeSelectedDisease(SurveillanceDiseaseCarouselLayout.java:184)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.setActiveDisease(SurveillanceDiseaseCarouselLayout.java:179)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.lambda$changeAutoSlideOption$971318fd$1(SurveillanceDiseaseCarouselLayout.java:214)
at sun.reflect.GeneratedMethodAccessor9464.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
### Steps to Reproduce
unknown

### System Details
* SORMAS version: 1.40.0

**Comment by StefanKock** [comment]
@MateStrysewskeSym: Looks similar to #2074

**Comment by MartinWahnschaffeSymeda** [comment]
I'm reviewing this. Currently waiting for a reply by Ghazzali.
