### ISSUE TITLE
Trying to export a reordered Grid: ClassCastException: GridSortOrder cannot be cast to QuerySortOrder

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2129]
### Bug Description
When trying a simple export on a list view (which uses `com.vaadin.ui.Grid`), there happens this exception:
```
2020-05-18 09:19:45,589 ERROR SurvSup  d.s.sormas.ui.SormasErrorHandler -
com.vaadin.data.provider.GridSortOrder cannot be cast to
com.vaadin.data.provider.QuerySortOrder
java.lang.ClassCastException: com.vaadin.data.provider.GridSortOrder cannot be cast to
com.vaadin.data.provider.QuerySortOrder
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at de.symeda.sormas.ui.caze.AbstractCaseGrid.lambda$setLazyDataProvider$7f6cf0df$1(AbstractCaseGrid.java:189)
at com.vaadin.data.provider.CallbackDataProvider.fetchFromBackEnd(CallbackDataProvider.java:137)
at com.vaadin.data.provider.AbstractBackEndDataProvider.fetch(AbstractBackEndDataProvider.java:61)
at com.vaadin.data.provider.DataProviderWrapper.fetch(DataProviderWrapper.java:91)
at de.symeda.sormas.ui.utils.GridExportStreamResource$1.getStream(GridExportStreamResource.java:84)
at com.vaadin.server.StreamResource.getStream(StreamResource.java:143)
at com.vaadin.server.FileDownloader.handleConnectorRequest(FileDownloader.java:167)
at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:90)
at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
...
```
There are StackTraces concerning: `CaseGrid`/`AbstractCaseGrid`, `EventGrid`, `FacilitiesGrid`. I assume there is a pattern with this combination of grid and export, that is making a problem.

### Steps to Reproduce
1. Log in and open cases list
2. Sort by disease (hit twice the header)
3. Try to Export -> Simple Export: Results in Exception

### Expected Behavior
Do not run into this ClassCastException. I do not know if the sorting of the grid can be kept for the export.

### System Details
* SORMAS version: 1.40.1, happened also on older versions

**Comment by StefanKock** [comment]
Address in next sprint please

**Comment by ChristopherRiedelSymeda** [comment]
@StefanKock I can't reproduce this behavior.

**Comment by StefanKock** [comment]
@ChristopherRiedelSymeda I did reproduce it on sormas.symeda.de as described above a minute ago.
