### ISSUE TITLE
CommitDiscardWrapperComponent: format confirmationDeleteEntity: IllegalFormatConversionException: d != java.lang.String 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2139]
### Bug Description
This exception happened yesterday several times:

```
2020-05-18 14:47:07,309 ERROR USERNAME d.s.sormas.ui.SormasErrorHandler - Unable to invoke
method click in com.vaadin.shared.ui.button.ButtonServerRpc
...
Caused by: java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
at java.util.Formatter.format(Formatter.java:2520)
at java.util.Formatter.format(Formatter.java:2455)
at java.lang.String.format(String.java:2940)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$3.buttonClick(CommitDiscardWrapperComponent.java:279)
at sun.reflect.GeneratedMethodAccessor14412.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```

It happened on this:
```
VaadinUiUtil.showDeleteConfirmationWindow(String.format(I18nProperties.getString(Strings.confirmationDeleteEntity), entityName)
```

Research in code shows, that `confirmationDeleteEntity` in `strings_fr-FR.properties` contains a `%d` instead `%s`.

### Steps to Reproduce
1. Try deleting something with french language chosen.

### System Details
* SORMAS version: 1.40.1

**Comment by StefanKock** [comment]
I fixed this problem with delete button, it was only wrong in fr-FR.

**Comment by StefanKock** [comment]
@bernardsilenou if you have problems with exception when trying to delete something, please do not use french language until next release.
