### ISSUE TITLE
PersonEditForm.fillDeathAndBurialFields: NPE 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2148]
### Bug Description
```
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.person.PersonEditForm.fillDeathAndBurialFields(PersonEditForm.java:669)
at de.symeda.sormas.ui.person.PersonEditForm.lambda$addFields$7ed4534$1(PersonEditForm.java:342)
at sun.reflect.GeneratedMethodAccessor812.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 108 common frames omitted
```
### Expected Behavior
Wrong: `burialPlaceDesc.getValue() == null || deathPlaceDesc.getValue().isEmpty()`
Correct `StringUtils.isBlank(burialPlaceDesc.getValue())`

### System Details
* SORMAS version: 1.40.x and older

### Additional Information
Two problems:
1. Check `burialPlaceDesc`, not `deathPlaceDesc`
2. Use StringUtils instead of null and empty check

**Comment by StefanKock** [comment]
@MateStrysewskeSym please review
