### ISSUE TITLE
CasesView.updateFilterComponents: DateHelper.getEpiWeek: Calendar.setTime: NPE

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2149]
### Bug Description
```
2020-05-17 12:55:17,317 ERROR USERNAME d.s.sormas.ui.SormasErrorHandler - null
java.lang.NullPointerException: null
at java.util.Calendar.setTime(Calendar.java:1770)
at de.symeda.sormas.api.utils.DateHelper.getEpiWeek(DateHelper.java:487)
at de.symeda.sormas.ui.caze.CasesView.updateFilterComponents(CasesView.java:1029)
at de.symeda.sormas.ui.caze.CasesView.enter(CasesView.java:953)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:726)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
at com.vaadin.ui.UI.doInit(UI.java:781)
```
### Steps to Reproduce
1. Go to cases view
2. Select filter option epi week (but no date/week values)
3. Hit apply date filter -> URL gets changed to dateFilterOption=EPI_WEEK
4. Leave the view
5. Return to the view

### Expected Behavior
Avoid the filtering when not all required values are present.

### System Details
* SORMAS version: 1.40.x

### Additional Information
Look around for the same pattern, at least for Case and Contact.

**Comment by StefanKock** [comment]
It happened when converting `newCaseDateFrom` to the EpiWeek for `weekAndDateFilter`.

```
		Date newCaseDateFrom = criteria.getNewCaseDateFrom();
		Date newCaseDateTo = criteria.getNewCaseDateTo();
		if (DateFilterOption.EPI_WEEK.equals(criteria.getDateFilterOption())) {
// 1029 -> NPE //	weekAndDateFilter.getWeekFromFilter().setValue(DateHelper.getEpiWeek(newCaseDateFrom));
			weekAndDateFilter.getWeekToFilter().setValue(DateHelper.getEpiWeek(newCaseDateTo));
		} else {
			weekAndDateFilter.getDateFromFilter().setValue(criteria.getNewCaseDateFrom());
			weekAndDateFilter.getDateToFilter().setValue(criteria.getNewCaseDateTo());
		}
```

I did reproduce this problem (1.40.x on DEMO): https://sormas.symeda.de/sormas-ui/#!cases/?dateFilterOption=EPI_WEEK&newCaseDateType=MOST_RELEVANT

- When I don't select both Epi Week fields, I get a warning and no exception happens.
![grafik](https://user-images.githubusercontent.com/24678567/82439935-c9889000-9a9b-11ea-9bc3-06a9cead2af8.png)
- I was not able to deselect date a value.
- When setting the filter option to EpiWeek and select no interval but hit apply date filter, then the EpiWeek param is set into the URL, but does not cause a problem. The exception happens when returning to it after other views were visited.

**Comment by StefanKock** [comment]
After reproducing it I think this bug is not too urgent to fix.
