### ISSUE TITLE
SampleService.getNewTestResultCountByResultType: PSQLException: Connection has been closed (too many values for IN clause) 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2150]
### Bug Description
```
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.sample.__SampleFacade_Remote_DynamicStub.getNewTestResultCountByResultType(de/symeda/sormas/api/sample/__SampleFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.sample._SampleFacade_Wrapper.getNewTestResultCountByResultType(de/symeda/sormas/api/sample/_SampleFacade_Wrapper.java)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.refreshDataForSelectedDisease(DashboardDataProvider.java:105)
at de.symeda.sormas.ui.dashboard.DashboardDataProvider.setDisease(DashboardDataProvider.java:263)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.changeSelectedDisease(SurveillanceDiseaseCarouselLayout.java:183)
at de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout.lambda$createCarouselMenuLayout$e1bd2c16$1(SurveillanceDiseaseCarouselLayout.java:105)
at sun.reflect.GeneratedMethodAccessor5277.invoke(Unknown Source)
...
at com.sun.proxy.$Proxy422.getNewTestResultCountByResultType(Unknown Source)
at de.symeda.sormas.backend.sample.__EJB31_Generated__SampleService__Intf____Bean__.getNewTestResultCountByResultType(Unknown
Source)
at de.symeda.sormas.backend.sample.SampleFacadeEjb.getNewTestResultCountByResultType(SampleFacadeEjb.java:523)
at sun.reflect.GeneratedMethodAccessor3845.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 142 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.gjc.spi.JdbcObjectsFactory$1.invoke(JdbcObjectsFactory.java:143)
... 193 more
Caused by: org.postgresql.util.PSQLException: Connection has been closed.
at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:315)
at com.sun.proxy.$Proxy311.getWarnings(Unknown Source)
... 197 more
```
From PSQL-Log: `incomplete message from client`

36k cases > short max value = 32,767. Having less entries works (31.000 caseIds returns in about 10s). Possible workaround: 

### Steps to Reproduce
1. Dashboard with COVID and see whole year 2020 with about 36K cases in scope. This exceptions happens immediately. 

### Expected Behavior
Batch query if larger than short.maxValue and join results afterwards by Java.

### System Details
* SORMAS version: 1.40.x

### Additional Information
This pattern might exist at several points and run into problems when having too much values for an IN clause.
Findings online:
- https://stackoverflow.com/questions/41204543/java-postgresql-error-on-large-query-an-i-o-error-occurred-while-sending-to-the
- https://stackoverflow.com/questions/1009706/postgresql-max-number-of-parameters-in-in-clause
- https://github.com/jOOQ/jOOQ/issues/5701

**Comment by StefanKock** [comment]
I did reproduce this with 100 000 caseids: `FacadeProvider.getSampleFacade().getNewTestResultCountByResultType(LongStream.rangeClosed(1, 100_000).boxed().collect(Collectors.toList()));` (but not in unit test, since it uses H2 database instead of PostgreSQL JDBC driver).

I ran into this also with postgresql 42.2.12 (latest).

**Comment by StefanKock** [comment]
My bugfix does a String concatenation into the query instead of setting a parameter for each member of the IN clause. I also avoided errors with 0 members.
A run by sormas-ui with 100 000 caseIds (1 to 100_000) took about 450ms.

**Comment by StefanKock** [comment]
Please note: The problem is only fixed for this query. There might be other queries running into this parameter limit soon.
