### ISSUE TITLE
NullPointerException in VisitDao.getByContact

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#2165]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.symeda.sormas.app.backend.common.AbstractDomainObject.isSnapshot()' on a null object reference
       at de.symeda.sormas.app.backend.visit.VisitDao.getByContact(VisitDao.java:63)
       at de.symeda.sormas.app.visit.list.VisitListViewModel$LoadVisitsTask.doInBackground(VisitListViewModel.java:61)
       at de.symeda.sormas.app.visit.list.VisitListViewModel$LoadVisitsTask.doInBackground(VisitListViewModel.java:52)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske I assume this can be closed?
