### ISSUE TITLE
Export statistics with rows = state and columns = district results throws PSQLException

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2173]
### Bug Description
When trying to generate statistics with _rows = state_ and _columns = district_ this exception happens.

SQL-Message:
```
2020-05-26 09:21:22 CEST [9615-1] sormas_user@sormas_db ERROR:  missing FROM-clause entry for table "region" at character 32
2020-05-26 09:21:22 CEST [9615-2] sormas_user@sormas_db STATEMENT:  SELECT COUNT(*) AS casecount , region.id AS groupA, district.id AS groupB FROM cases LEFT JOIN district ON cases.district_id = district.id WHERE (cases.deleted = false OR cases.deleted IS NULL ) GROUP BY groupA,groupB ORDER BY groupA NULLS LAST,groupB NULLS LAST
```
StackTrace:
```
...
at org.hibernate.query.Query.getResultStream(Query.java:1140)
at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:100)
at sun.reflect.GeneratedMethodAccessor6751.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 110 more
Caused by: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table
"region"
  Position: 32
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
...
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
... 150 more
```
### Steps to Reproduce
1. Configure export as in the screenshot and hit generate.

### Expected Behavior
Avoid non-sensibel combinations of rows and columns?

### Screenshots
![grafik](https://user-images.githubusercontent.com/24678567/82872954-105f0580-9f34-11ea-9e85-92dede065c57.png)

### System Details
* SORMAS version: 1.40.x

**Comment by StefanKock** [comment]
It seems that #2174 also fixed this issue.
