### ISSUE TITLE
Export statistics with no group rows and columns = district results throws PSQLException

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2174]
### Bug Description
Similar to #2173: When trying to generate statistics with rows = state and columns = district this exception happens.

SQL-Message:
```
2020-05-26 09:52:02 CEST [9615-3] sormas_user@sormas_db ERROR:  syntax error at or near "," at character 206
2020-05-26 09:52:02 CEST [9615-4] sormas_user@sormas_db STATEMENT:  SELECT COUNT(*) AS casecount , null::text AS groupA, district.id AS groupB FROM cases LEFT JOIN district ON cases.district_id = district.id WHERE (cases.deleted = false OR cases.deleted IS NULL ) GROUP BY ,groupB ORDER BY groupB NULLS LAST
```
```
...
at org.hibernate.query.Query.getResultStream(Query.java:1140)
at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:100)
at sun.reflect.GeneratedMethodAccessor29689.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 110 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ","
  Position: 206
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
...
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
...
```
### Steps to Reproduce
1. See selected fields in screenshots and try to generate statistics.

### Screenshots
![grafik](https://user-images.githubusercontent.com/24678567/82875037-25896380-9f37-11ea-9b93-72f7cbd9eb82.png)

### System Details
* SORMAS version: 1.40.x

### Additional Information
This issue happens quite often.

**Comment by StefanKock** [comment]
The exception is not reproducable on my system, but I will check this on TEST stage.

**Comment by StefanKock** [comment]
When selecting columns = communities I run into this problem:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at de.symeda.sormas.ui.statistics.StatisticsCaseGrid.<init>(StatisticsCaseGrid.java:230)
	at de.symeda.sormas.ui.statistics.StatisticsView.generateTable(StatisticsView.java:425)
	at de.symeda.sormas.ui.statistics.StatisticsView.lambda$6(StatisticsView.java:353)
	at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
	... 86 common frames omitted
```
I am not sure it is due to malformed backend response or an independent defect.

**Comment by MateStrysewskeSym** [comment]
@StefanKock I'll have a look at it

**Comment by StefanKock** [comment]
Tested on my DEV system, no errors when grouping jursitiction levels in rows and/or columns.
