### ISSUE TITLE
Increase JDBC connection pool size [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2203]
### Feature Description
SORMAS uses JDBC connection pooling with a limit of concurrent connections. 

- [x] Documentation what happens (risk) with increasing the pool size
- [x] Make the JDBC connections (concurrent) configurable

### Problem Description
These exceptions occured the last days. It seems that the connection pool limit is reached or `max_prepared_transactions` of PostgreSQL makes problems.

```
... 148 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 207 more
Caused by: javax.persistence.PersistenceException:
org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 205 more
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
...
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
... 251 more
Caused by: java.sql.SQLException: Error in allocating a connection. Cause: In-use
connections equal max-pool-size and expired max-wait-time. Cannot allocate more
connections.
at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:119)
at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
... 271 more
Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a
connection. Cause: In-use connections equal max-pool-size and expired max-wait-time.
Cannot allocate more connections.
at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
... 274 more
Caused by: com.sun.appserv.connectors.internal.api.PoolingException: In-use connections
equal max-pool-size and expired max-wait-time. Cannot allocate more connections.
at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:423)
at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
... 278 more
```
### Proposed Change
1. Increase size of all JDBC connection pools in setup.
2. Increase `max_prepared_transactions` for PostgreSQL server in documentation and in `StartupShutdownService.checkDatabaseConfig`.
3. Document update commands for existing instances within this ticket.

### Possible Alternatives
Avoid long running transactions (usually inperformant SELECT statements).

### Additional Information
Uncertain where or what limit causes the problem.
This overlaps with #1768

**Comment by Chinedar** [comment]
@StefanKock I think we can fix this alongside the hotfix that will take care of the bug that crashes the app. This is challenge for us. Every time the connection limit is maxed out, the server forcefully restarts and stays inactive.

**Comment by HolgerReiseVSys** [comment]
This may also be connected to #1759.
There we had to make sure that the vaadin session will not be blocked while creating large exports.
Two db connections (sormas and auditlog), however, will still be in use.

Also, connections will probably not be returned before the download has finished, which is due to the SessionFilters mechanism.

There might also be isues with ejb methodes requiring new transactions (`@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)`).

Sidenote: Some methods are annotated with `@Transactional(value = Transactional.TxType.REQUIRES_NEW)`, which might not have the desired effect.

**Comment by StefanKock** [comment]
I checked the settings in my DEV system (which will likely be all setup defaults):
![grafik](https://user-images.githubusercontent.com/24678567/83624656-2ce1ea00-a593-11ea-9c1e-a89a29776319.png)

@HolgerReiseVSys pointed out that the allocation of stateless EJBs can be the next bottleneck. Also Thread Pools might also be a problem.

![grafik](https://user-images.githubusercontent.com/24678567/83625985-176dbf80-a595-11ea-89d3-aec2cc53a9c3.png)

**Comment by StefanKock** [comment]
I think we should apply default max pool sizes from the payara production domain (see https://docs.payara.fish/docs/5.201/documentation/payara-server/production-ready-domain.html)
1. EJB container max-pool-size = 128
2. JDBC `max-pool-size`s = 128
3. PostgreSQL `max_prepared_transactions` = 256

Increasing thread pool params should be considered to be addressed in a new ticket or in #1768.

**Comment by StefanKock** [comment]
Maybe also increase other postgres settings, see https://support.microfocus.com/kb/doc.php?id=7024137 to avoid `PSQLException: remaining connection slots are reserved for non-replication superuser connections`

**Comment by StefanKock** [comment]
Hint by @HolgerReiseVSys: The payara provides a recorder to plot out admin commands when configuring in the admin UI

**Comment by StefanKock** [comment]
Discussed with @HolgerReiseVSys: It is not quite sure, when an connection limit increase will run into CPU, RAM or IO problem.
Solution: We make this configurable and increase the default value to 64 (instead of 128 as suggested on 2020-06-03).
1. EJB `max-pool-size` = 64
2. JDBC `max-pool-size`s = 64
3. PostgreSQL `max_connections` = 128+32
4. PostgreSQL `max_prepared_transactions` = 128

**Comment by StefanKock** [comment]
Found an old documentation how to configure this via `asadmin`: https://docs.oracle.com/cd/E26576_01/doc.312/e24938/create-jdbc-connection-pool.htm#GSRFM00036

**Comment by StefanKock** [comment]
EJB container `max-pool-size` = 128 will be done by #2453 with the `production` template.

**Comment by StefanKock** [comment]
Waiting for start of 1.45

**Comment by StefanKock** [comment]
risk with too much connections: Not enough CPU/RAM or other limits like thread pools. 128 for connection pools combined with settings of `production` templates looks reasonable.

**Comment by obinna-h-n** [comment]
@StefanKock , I totally agree with tuning the domain following the payara production template. But maybe we can create a guide for country admins to perform tests that simulate their peculiar users, etc and gradually tune settings optimally. A fixed set of settings may not be optimal for all deployments.

**Comment by StefanKock** [comment]
Merged to development and tested on Windows and Linux machine.
