### ISSUE TITLE
ContactsDashboardView.lambda$createMapLayout: NPE

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2204]
### Bug Description
```
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
buttonClick in
de.symeda.sormas.ui.dashboard.map.DashboardMapComponent$$Lambda$748/1929297014 failed.
...
at com.vaadin.ui.Button.fireClick(Button.java:384)
at com.vaadin.ui.Button$1.click(Button.java:57)
... 81 common frames omitted
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.lambda$createMapLayout$8(ContactsDashboardView.java:319)
at de.symeda.sormas.ui.dashboard.map.DashboardMapComponent.lambda$createHeader$dfdd7593$1(DashboardMapComponent.java:299)
at sun.reflect.GeneratedMethodAccessor2060.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
### Steps to Reproduce
NPE is thown in `networkDiagramRowLayout.setVisible(!expanded);`. Where exactly the call to `createHeader` and triggering the `ExpandListener ` happens is yet unknown.

### System Details
* SORMAS version: 1.40.x

### Additional information
This happened only once until now, on 2020-05-26.

**Comment by MateStrysewskeSym** [comment]
This has already been fixed in a past version.
