### ISSUE TITLE
SamplesView.enter SampleGridComponent.updateStatusButtons: Exception in query: NPE

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2213]
### Bug Description
```
2020-05-28 19:50:33,296 ERROR NatUser  d.s.sormas.ui.SormasErrorHandler - Unable to invoke
method click in com.vaadin.shared.ui.button.ButtonServerRpc
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.sample.__SampleFacade_Remote_DynamicStub.count(de/symeda/sormas/api/sample/__SampleFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.sample._SampleFacade_Wrapper.count(de/symeda/sormas/api/sample/_SampleFacade_Wrapper.java)
at de.symeda.sormas.ui.samples.SampleGrid.lambda$setLazyDataProvider$b88b9d74$1(SampleGrid.java:144)
at com.vaadin.data.provider.CallbackDataProvider.sizeInBackEnd(CallbackDataProvider.java:142)
at com.vaadin.data.provider.AbstractBackEndDataProvider.size(AbstractBackEndDataProvider.java:66)
at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
at de.symeda.sormas.ui.utils.FilteredGrid.getItemCount(FilteredGrid.java:67)
at de.symeda.sormas.ui.samples.SampleGridComponent.updateStatusButtons(SampleGridComponent.java:301)
at de.symeda.sormas.ui.samples.SampleGridComponent.updateFilterComponents(SampleGridComponent.java:235)
at de.symeda.sormas.ui.samples.SampleGridComponent.reload(SampleGridComponent.java:216)
at de.symeda.sormas.ui.samples.SamplesView.enter(SamplesView.java:140)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
at com.vaadin.navigator.View.beforeLeave(View.java:79)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
at de.symeda.sormas.ui.MainScreen$2.beforeViewChange(MainScreen.java:209)
at com.vaadin.navigator.Navigator.fireBeforeViewChange(Navigator.java:883)
at com.vaadin.navigator.Navigator.beforeViewChange(Navigator.java:796)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:762)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
at com.vaadin.navigator.View.beforeLeave(View.java:79)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
at de.symeda.sormas.ui.Menu.lambda$createViewButton$f7d2215a$1(Menu.java:187)
at sun.reflect.GeneratedMethodAccessor47879.invoke(Unknown Source)
...
at com.sun.proxy.$Proxy1083.buildCriteriaFilter(Unknown Source)
at de.symeda.sormas.backend.sample.__EJB31_Generated__SampleService__Intf____Bean__.buildCriteriaFilter(Unknown
Source)
at de.symeda.sormas.backend.sample.SampleFacadeEjb.count(SampleFacadeEjb.java:554)
at sun.reflect.GeneratedMethodAccessor51065.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 134 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 168 more
Caused by: java.lang.NullPointerException
at org.hibernate.query.criteria.internal.predicate.ComparisonPredicate.<init>(ComparisonPredicate.java:52)
at org.hibernate.query.criteria.internal.CriteriaBuilderImpl.equal(CriteriaBuilderImpl.java:369)
at de.symeda.sormas.backend.sample.SampleService.buildCriteriaFilter(SampleService.java:372)
at sun.reflect.GeneratedMethodAccessor50411.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 166 more
```
### Steps to Reproduce
Unknown, watch the selected user on DEMO

### System Details
* SORMAS version: 1.41.0

**Comment by StefanKock** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym Many exceptions about this, looks like a hotfix candidate

**Comment by MateStrysewskeSym** [comment]
The SampleService.buildCriteriaFilter method was missing expressions needed for the new QueryContext. Filtering the sample index list by disease, region or district therefore resulted in an error. @BarnaBartha
