### ISSUE TITLE
SampleService.createUserFilterWithoutCase: NPE 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2216]
### Bug Description
```
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.caze.__CaseFacade_Remote_DynamicStub.count(de/symeda/sormas/api/caze/__CaseFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.caze._CaseFacade_Wrapper.count(de/symeda/sormas/api/caze/_CaseFacade_Wrapper.java)
at de.symeda.sormas.ui.caze.AbstractCaseGrid.lambda$setLazyDataProvider$b88b9d74$1(AbstractCaseGrid.java:190)
at com.vaadin.data.provider.CallbackDataProvider.sizeInBackEnd(CallbackDataProvider.java:142)
at com.vaadin.data.provider.AbstractBackEndDataProvider.size(AbstractBackEndDataProvider.java:66)
at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
at de.symeda.sormas.ui.utils.FilteredGrid.getItemCount(FilteredGrid.java:67)
at de.symeda.sormas.ui.caze.CasesView.updateStatusButtons(CasesView.java:562)
at de.symeda.sormas.ui.caze.CasesView.updateFilterComponents(CasesView.java:541)
at de.symeda.sormas.ui.caze.CasesView.enter(CasesView.java:534)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
...
at com.sun.proxy.$Proxy410.createUserFilterWithoutCase(Unknown Source)
at de.symeda.sormas.backend.sample.__EJB31_Generated__SampleService__Intf____Bean__.createUserFilterWithoutCase(Unknown
Source)
at de.symeda.sormas.backend.caze.CaseService.createUserFilter(CaseService.java:783)
at de.symeda.sormas.backend.caze.CaseService.createUserFilter(CaseService.java:828)
at sun.reflect.GeneratedMethodAccessor829.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 137 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 172 more
Caused by: java.lang.NullPointerException
at de.symeda.sormas.backend.sample.SampleService.createUserFilterWithoutCase(SampleService.java:298)
...
at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
... 170 more
```
### Steps to Reproduce
Unknown

### System Details
* SORMAS version: 1.41.0

### Additional Information
Maybe related to #2213

**Comment by MateStrysewskeSym** [comment]
The SampleService.createUserFilterWithoutCase method was missing joins needed for the new QueryContext when called from CaseService.createUserFilter. This resulted in an error when entering the case directory as a lab officer with a limited disease set. @BarnaBartha
