### ISSUE TITLE
Edit an item shown in a Grid: NPE

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2240]
### Bug Description
It seems that there is a pattern that on at least two Grid views there somtimes happen NPEs concerning the edit column (it seems that the item is `null`):
```
addEditColumn(e -> ControllerProvider.getSampleController().navigateToData(e.getItem().getUuid()));
```
Problem seen in: `SampleGrid`, `AbstractCaseGrid`, `ContactGrid`.
```
2020-05-28 15:32:25,079 
...
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method itemClick
in de.symeda.sormas.ui.utils.FilteredGrid$$Lambda$877/715074584 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.ui.Grid.access$500(Grid.java:144)
at com.vaadin.ui.Grid$GridServerRpcImpl.itemClick(Grid.java:645)
... 81 common frames omitted
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.samples.SampleGrid.lambda$new$0(SampleGrid.java:68)
at de.symeda.sormas.ui.utils.FilteredGrid.lambda$addEditColumn$c8bc760a$1(FilteredGrid.java:82)
at sun.reflect.GeneratedMethodAccessor3535.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
```
2020-06-02 10:47:12,843 
...
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.caze.AbstractCaseGrid.lambda$new$e40c2ffe$1(AbstractCaseGrid.java:82)
at sun.reflect.GeneratedMethodAccessor2826.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
```
2020-04-24 13:34:19,296
...
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.contact.ContactGrid.lambda$new$ec88c40e$1(ContactGrid.java:127)
at sun.reflect.GeneratedMethodAccessor2607.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
### Steps to Reproduce
Unknown. Maybe it is a double-click problem.

### Expected Behavior
Do not fail when selecting none line or deselect a line.

### System Details
* SORMAS version: 1.39.x, 1.40.x, 1.41.x (and also older versions of mid 2019)

### Additional information
Maybe there is more event handling / item click handling needed in `FilteredGrid.addEditColumn` before triggering the `handler`.

**Comment by StefanKock** [comment]
I was not able to reproduce the NPE, but refactored all `ItemClickListener`s to the new `ShowDetailsListener` which does not execute the `itemHandler` if `event.getItem() == null`.

**Comment by StefanKock** [comment]
Merge request is open, review by @BarnaBartha requested.
