### ISSUE TITLE
ContactFacadeEjb.getNonSourceCaseCountForDashboard: PSQLException: Connection has been closed (too many values for IN clause)

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2253]
### Bug Description
Sibling to #2150, but this time on (luckily simple) Criteria Query.
```
2020-06-03 09:32:42,677
...
at de.symeda.sormas.api.contact.__ContactFacade_Remote_DynamicStub.getNonSourceCaseCountForDashboard(de/symeda/sormas/api/contact/__ContactFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.contact._ContactFacade_Wrapper.getNonSourceCaseCountForDashboard(de/symeda/sormas/api/contact/_ContactFacade_Wrapper.java)
at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.updateCaseCountsAndSourceCasesLabels(ContactsDashboardView.java:193)
at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.refreshDashboard(ContactsDashboardView.java:365)
at de.symeda.sormas.ui.dashboard.DashboardFilterLayout.lambda$createDateFilterButtonsLayout$b4b594c5$5(DashboardFilterLayout.java:258)
at sun.reflect.GeneratedMethodAccessor1385.invoke(Unknown Source)
...
Caused by: java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy309.getWarnings(Unknown Source)
at com.sun.gjc.spi.base.ConnectionHolder.getWarnings(ConnectionHolder.java:405)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:290)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:269)
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.releaseConnection(LogicalConnectionManagedImpl.java:194)
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.afterStatement(LogicalConnectionManagedImpl.java:149)
at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.afterStatementExecution(JdbcCoordinatorImpl.java:279)
at org.hibernate.loader.Loader.getResultSet(Loader.java:2177)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1934)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896)
at org.hibernate.loader.Loader.doQuery(Loader.java:936)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:339)
at org.hibernate.loader.Loader.doList(Loader.java:2693)
at org.hibernate.loader.Loader.doList(Loader.java:2676)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2510)
at org.hibernate.loader.Loader.list(Loader.java:2505)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1537)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1561)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1577)
at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
at de.symeda.sormas.backend.contact.ContactFacadeEjb.getNonSourceCaseCountForDashboard(ContactFacadeEjb.java:690)
at sun.reflect.GeneratedMethodAccessor6064.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 110 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.sun.gjc.spi.JdbcObjectsFactory$1.invoke(JdbcObjectsFactory.java:143)
... 163 more
Caused by: org.postgresql.util.PSQLException: Connection has been closed.
at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:315)
at com.sun.proxy.$Proxy307.getWarnings(Unknown Source)
... 167 more
```
Aus PSQL log:  `incomplete message from client`

### Expected Behavior
Rewrite as native query and change to String concatenation like in #2150. Watch it that uuids (String) need proper encapsulation by '.

### System Details
* SORMAS version: 1.41

### Additional Information
Discussed this with @MartinWahnschaffeSymeda to solve this quickly aside to #2193.

**Comment by StefanKock** [comment]
The query is the same as before, but now native. I tested this also with 100_000 values as a call by the UI against a real PostgreSQL server -> worked.

@MartinWahnschaffeSymeda please review.

**Comment by MartinWahnschaffeSymeda** [comment]
Can be merged. We are not sure yet whether it would be better to keep the criteria query and batch it instead (having max ~32000 uuids in the query). This should be decided in #2193
