### ISSUE TITLE
CaseStatisticsFacadeEjb.queryCaseCount: PSQLException: time zone displacement out of range: "-2020-12-31" 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2275]
### Bug Description
```
2020-06-08 13:19:09,952
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.caze.__CaseStatisticsFacade_Remote_DynamicStub.queryCaseCount(de/symeda/sormas/api/caze/__CaseStatisticsFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.caze._CaseStatisticsFacade_Wrapper.queryCaseCount(de/symeda/sormas/api/caze/_CaseStatisticsFacade_Wrapper.java)
at de.symeda.sormas.ui.statistics.StatisticsView.generateStatistics(StatisticsView.java:938)
at de.symeda.sormas.ui.statistics.StatisticsView.generateChart(StatisticsView.java:407)
at de.symeda.sormas.ui.statistics.StatisticsView.lambda$addGenerateButton$eb13574f$1(StatisticsView.java:348)
at sun.reflect.GeneratedMethodAccessor1787.invoke(Unknown Source)
...
Caused by: org.hibernate.exception.DataException: could not extract ResultSet
at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
at org.hibernate.loader.Loader.getResultSet(Loader.java:2171)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1934)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896)
at org.hibernate.loader.Loader.scroll(Loader.java:2769)
at org.hibernate.loader.custom.CustomLoader.scroll(CustomLoader.java:383)
at org.hibernate.internal.SessionImpl.scrollCustomQuery(SessionImpl.java:2237)
at org.hibernate.internal.AbstractSharedSessionContract.scroll(AbstractSharedSessionContract.java:1074)
at org.hibernate.query.internal.NativeQueryImpl.doScroll(NativeQueryImpl.java:220)
at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1486)
at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1510)
at org.hibernate.query.Query.getResultStream(Query.java:1140)
at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:100)
at sun.reflect.GeneratedMethodAccessor4869.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 110 more
Caused by: org.postgresql.util.PSQLException: ERROR: time zone displacement out of range:
"-2020-12-31"
  Where: PL/pgSQL function epi_week(timestamp without time zone) line 13 at assignment
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
...
```
### Steps to Reproduce
Unknown

### System Details
* SORMAS version: 1.41

**Comment by StefanKock** [comment]
@MateStrysewskeSym look for PSQL log with this timestamp: `2020-06-13 11:19:15,823`

**Comment by StefanKock** [comment]
Reproducing the exception directly in SQL:
```
SELECT * FROM epi_week('-2020-12-31');

ERROR:  FEHLER:  Zeitzonenunterschied ist außerhalb des gültigen Bereichs: »-2020-12-31«
LINE 1: SELECT * FROM epi_week('-2020-12-31');
```

**Comment by StefanKock** [comment]
This issue happened in `1.42.3` on `caseCountQuery.getResultStream()` in line 124. 

As far as I see the value is always coming into the `epi_week(timestamp indate)` from an attribute join (`tablename.attributeName`). Conclusion: Can it be that there is an invalid value within the following columns `Symptoms.ONSET_DATE`, `Case.REPORT_DATE`)?

**Comment by StefanKock** [comment]
I tried to persist a negative value with pgadmin, but that failed:
```
UPDATE cases set reportdate = '-2020-06-20' WHERE reportdate = '2020-06-20'; 

ERROR:  FEHLER:  Zeitzonenunterschied ist außerhalb des gültigen Bereichs: »-2020-06-20«
LINE 2: UPDATE cases set reportdate = '-2020-06-20' WHERE reportdate...
                                      ^
SQL state: 22009
Character: 32
```

Nevertheless: To check whether there is data with negative value, one could try these statements:
```
SELECT uuid, reportdate FROM cases WHERE reportdate < '0001-01-01';
SELECT uuid, onsetdate FROM symptoms WHERE onsetdate < '0001-01-01';
```

**Comment by MateStrysewskeSym** [comment]
#2455 will probably make sure that this doesn't happen again

**Comment by StefanKock** [comment]
But corrupt data already in the database needs to be handled too.
