### ISSUE TITLE
FacilityFacadeEjb.hasArchivedParentInfrastructure: PSQLException: syntax error

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2291]
### Bug Description
```
2020-06-09 23:50:22,645 ...
at de.symeda.sormas.api.facility._FacilityFacade_Wrapper.hasArchivedParentInfrastructure(de/symeda/sormas/api/facility/_FacilityFacade_Wrapper.java)
at de.symeda.sormas.ui.configuration.infrastructure.InfrastructureController.archiveOrDearchiveAllSelectedItems(InfrastructureController.java:450)
at de.symeda.sormas.ui.configuration.infrastructure.AbstractFacilitiesView.lambda$createFilterBar$308851b6$1(AbstractFacilitiesView.java:267)
at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:210)
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.facility.__FacilityFacade_Remote_DynamicStub.hasArchivedParentInfrastructure(de/symeda/sormas/api/facility/__FacilityFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.facility._FacilityFacade_Wrapper.hasArchivedParentInfrastructure(de/symeda/sormas/api/facility/_FacilityFacade_Wrapper.java)
at de.symeda.sormas.ui.configuration.infrastructure.InfrastructureController.archiveOrDearchiveAllSelectedItems(InfrastructureController.java:450)
at de.symeda.sormas.ui.configuration.infrastructure.AbstractFacilitiesView.lambda$createFilterBar$308851b6$1(AbstractFacilitiesView.java:267)
at com.vaadin.ui.MenuBar.changeVariables(MenuBar.java:210)
...
Caused by: javax.persistence.PersistenceException:
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1538)
at org.hibernate.query.Query.getResultList(Query.java:165)
at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
at de.symeda.sormas.backend.facility.FacilityFacadeEjb.hasArchivedParentInfrastructure(FacilityFacadeEjb.java:237)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 98 more
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
at org.hibernate.loader.Loader.getResultSet(Loader.java:2171)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1934)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896)
at org.hibernate.loader.Loader.doQuery(Loader.java:936)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:339)
at org.hibernate.loader.Loader.doList(Loader.java:2693)
at org.hibernate.loader.Loader.doList(Loader.java:2676)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2510)
at org.hibernate.loader.Loader.list(Loader.java:2505)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1537)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1561)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
... 130 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 381
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
...
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
... 145 more
```
PSQL-Log:
```
2020-06-09 23:50:22 UTC [23331-13] sormas_user@sormas_db ERROR:  syntax error at or near ")" at character 381

2020-06-09 23:50:22 UTC [23331-14] sormas_user@sormas_db STATEMENT:  select facility0_.id as col_0_0_ from Facility facility0_ inner join Community community1_ on facility0_.community_id=community1_.id inner join District district2_ on facility0_.district_id=district2_.id inner join Region region3_ on facility0_.region_id=region3_.id where (community1_.archived=true or district2_.archived=true or region3_.archived=true) and (facility0_.uuid in ()) limit $1
```
### Steps to Reproduce
Unknown

### System Details
* SORMAS version: 1.41

**Comment by StefanKock** [comment]
I tried to avoid this problem by updating to `org.hibernate:hibernate-core:5.4.17.Final` as @HolgerReiseVSys suggested but it did not help. So I took the usual approach and handle an empty collection separate instead of running a pointless query.

**Comment by StefanKock** [comment]
I noticed that this problem applies also to some other sibling functions. Maybe it is better to avoid bulk action on archiving/dearchiving with an empty selection.

**Comment by StefanKock** [comment]
I pulled the check for empty bulk action to the beginning to fix this problem for all infrastructure types in `InfrastructureController`. I assigned the pull request to @MateStrysewskeSym
