### ISSUE TITLE
CaseFacadeEjb.doesEpidNumberExist: Integer.parseInt: NumberFormatException: For input string: "080349ddddd"

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2312]
### Bug Description
```
2020-06-11 09:38:41,301 ERROR
...
at de.symeda.sormas.api.caze.__CaseFacade_Remote_DynamicStub.doesEpidNumberExist(de/symeda/sormas/api/caze/__CaseFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.caze._CaseFacade_Wrapper.doesEpidNumberExist(de/symeda/sormas/api/caze/_CaseFacade_Wrapper.java)
at de.symeda.sormas.ui.caze.CaseDataForm.setEpidNumberError(CaseDataForm.java:581)
at de.symeda.sormas.ui.caze.CaseDataForm.lambda$addFields$c5e6f215$1(CaseDataForm.java:469)
at sun.reflect.GeneratedMethodAccessor766.invoke(Unknown Source)
...
at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:427)
at de.symeda.sormas.ui.utils.AbstractEditForm.setValue(AbstractEditForm.java:96)
at de.symeda.sormas.ui.caze.CaseController.getCaseDataEditComponent(CaseController.java:479)
at de.symeda.sormas.ui.caze.CaseDataView.initView(CaseDataView.java:87)
at de.symeda.sormas.ui.caze.AbstractCaseView.enter(AbstractCaseView.java:192)
at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
at com.vaadin.navigator.View.beforeLeave(View.java:79)
at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
at de.symeda.sormas.ui.SormasUI.refreshView(SormasUI.java:99)
at de.symeda.sormas.ui.caze.CaseController.saveCase(CaseController.java:253)
at de.symeda.sormas.ui.caze.CaseController.access$100(CaseController.java:99)
at de.symeda.sormas.ui.caze.CaseController$2.lambda$onCommit$0(CaseController.java:358)
at de.symeda.sormas.ui.caze.CaseController.selectOrCreate(CaseController.java:432)
at de.symeda.sormas.ui.caze.CaseController$2.onCommit(CaseController.java:343)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:476)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:344)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:366)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:244)
at sun.reflect.GeneratedMethodAccessor1787.invoke(Unknown Source)
...
at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown
Source)
at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:68)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
...
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 143 more
Caused by: java.lang.NumberFormatException: For input string: "080349ddddd"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:583)
at java.lang.Integer.parseInt(Integer.java:615)
at de.symeda.sormas.backend.caze.CaseFacadeEjb.doesEpidNumberExist(CaseFacadeEjb.java:1959)
at sun.reflect.GeneratedMethodAccessor1797.invoke(Unknown Source)
...
at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
... 141 more
```
### Steps to Reproduce
Try a large Epid number.

### Expected Behavior
Are Epid Ids larger than MAXINT supposed to be supported?

### System Details
* SORMAS version: 1.41

### Additional Information
Explicit number is known, but last five digits are here replaced by ddddd.

**Comment by StefanKock** [comment]
I confirmed that too large epid numbers (after last "-") run into this problem. Maybe it was a user typo but should nevertheless not result into a RuntimeException.

Possible options:

- Allow larger values with parsing to `Long`.
- Handle `NumberFormatException` appropriate with meaningful error message for the user (maybe also for inputs larger than `Long`).

**Comment by StefanKock** [comment]
Proposed by @MateStrysewskeSym: More than 9 digits should not be relevant, so catch NumberFormatException and throw meaningful error.

**Comment by MateStrysewskeSym** [comment]
@StefanKock I've decided to add a length limit for now that will make sure that we don't run into this error anymore. We can think about a more sophisticated solution some time in the future.
