### ISSUE TITLE
LocationEditForm.addFields: AbstractEditForm.initializeAccessAndAllowedAccesses: RuntimeException: Access checker is not set!

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2317]
### Bug Description
```
2020-06-13 10:27:43,061 ERROR
...
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method
buttonClick in de.symeda.sormas.ui.caze.AbstractTableField$$Lambda$999/1633259292 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.ui.Button.fireClick(Button.java:384)
at com.vaadin.ui.Button$1.click(Button.java:57)
... 81 common frames omitted
Caused by: java.lang.RuntimeException: Access checker is not set!
at de.symeda.sormas.ui.utils.AbstractEditForm.initializeAccessAndAllowedAccesses(AbstractEditForm.java:440)
at de.symeda.sormas.ui.location.LocationEditForm.addFields(LocationEditForm.java:132)
at de.symeda.sormas.ui.utils.AbstractEditForm.<init>(AbstractEditForm.java:84)
at de.symeda.sormas.ui.location.LocationEditForm.<init>(LocationEditForm.java:86)
at de.symeda.sormas.ui.utils.SormasFieldGroupFieldFactory.createField(SormasFieldGroupFieldFactory.java:93)
at com.vaadin.v7.data.fieldgroup.FieldGroup.build(FieldGroup.java:1240)
at com.vaadin.v7.data.fieldgroup.FieldGroup.buildAndBind(FieldGroup.java:1214)
at com.vaadin.v7.data.fieldgroup.BeanFieldGroup.buildAndBind(BeanFieldGroup.java:170)
at de.symeda.sormas.ui.utils.AbstractForm.addField(AbstractForm.java:210)
at de.symeda.sormas.ui.utils.AbstractForm.addField(AbstractForm.java:203)
at de.symeda.sormas.ui.epidata.EpiDataGatheringEditForm.addFields(EpiDataGatheringEditForm.java:49)
at de.symeda.sormas.ui.utils.AbstractEditForm.<init>(AbstractEditForm.java:84)
at de.symeda.sormas.ui.utils.AbstractEditForm.<init>(AbstractEditForm.java:66)
at de.symeda.sormas.ui.epidata.EpiDataGatheringEditForm.<init>(EpiDataGatheringEditForm.java:40)
at de.symeda.sormas.ui.epidata.EpiDataGatheringsField.editEntry(EpiDataGatheringsField.java:127)
at de.symeda.sormas.ui.epidata.EpiDataGatheringsField.editEntry(EpiDataGatheringsField.java:40)
at de.symeda.sormas.ui.caze.AbstractTableField.addEntry(AbstractTableField.java:245)
at de.symeda.sormas.ui.caze.AbstractTableField.lambda$createAddButton$833dd281$1(AbstractTableField.java:234)
at sun.reflect.GeneratedMethodAccessor1502.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 86 common frames omitted
```
### Steps to Reproduce
Unknown

### System Details
* SORMAS version: 1.42x?

**Comment by leventegal-she** [comment]
Review: OK
