### ISSUE TITLE
Error message after create/edit event participant

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2389]
### Bug Description
Event participants can be created but error occur at the second stage  of collecting  detailed information  about the associated person of the event participant. In addition, you can't save data on event participants. 

### Steps to Reproduce
1. Create an event participant on the web
2.

### Expected Behavior
The method that link event participants to persons should create a new person in the db (duplicate search fro person is not needed here for now). Link this created person to the event participant entity.
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/85753461-91b0e000-b70c-11ea-83b5-0eb4ac17fe28.png)

### System Details
* Device: web
* SORMAS version: 1.43.0

### Additional Information
Corresponding StackTrace (added by @StefanKock)
```
Caused by: java.lang.NullPointerException: null
at de.symeda.sormas.ui.utils.AbstractSubNavigationView.enter(AbstractSubNavigationView.java:87)
at de.symeda.sormas.ui.events.AbstractEventView.enter(AbstractEventView.java:45)
at de.symeda.sormas.ui.events.EventParticipantsController.refreshView(EventParticipantsController.java:144)
at de.symeda.sormas.ui.events.EventParticipantsController.access$200(EventParticipantsController.java:49)
at de.symeda.sormas.ui.events.EventParticipantsController$2.onCommit(EventParticipantsController.java:126)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:480)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:348)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:369)
at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:243)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
... 87 common frames omitted
```

**Comment by StefanKock** [comment]
Happens because of #2065 and calling `EventParticipantsView.enter(null)`

**Comment by StefanKock** [comment]
Consequence of this defect: EventParticipant is persisted, but the dialog is not closed and the view not properly refreshed.

**Comment by StefanKock** [comment]
Discussed with @MateStrysewskeSym: Since only the view refresh is broken, this will not be hotfixed asap. But if there might be a hotfix urgently needed in the next days, this will be included.

**Comment by bernardsilenou** [comment]
I suggest we do not  deploy on production server that uses the event section of SROMAS. I have no urgent need from the user to upgrade now.

**Comment by StefanKock** [comment]
> I suggest we do not deploy on production server that uses the event section of SROMAS. I have no urgent need from the user to upgrade now.

I disagree, a lot of bugfixes including fixing event creation (#2317) need to be deployed. There is usually no option/reason than to update asap.
