### ISSUE TITLE
CaseStatisticsFacadeEjb.queryCaseCount: IllegalArgumentException: Reporting user role 

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2449]
### Bug Description
```
2020-07-03 17:15:26,897 
...
at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
at de.symeda.sormas.api.caze.__CaseStatisticsFacade_Remote_DynamicStub.queryCaseCount(de/symeda/sormas/api/caze/__CaseStatisticsFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.caze._CaseStatisticsFacade_Wrapper.queryCaseCount(de/symeda/sormas/api/caze/_CaseStatisticsFacade_Wrapper.java)
at de.symeda.sormas.ui.statistics.StatisticsView.generateStatistics(StatisticsView.java:1063)
at de.symeda.sormas.ui.statistics.StatisticsView.generateChart(StatisticsView.java:443)
at de.symeda.sormas.ui.statistics.StatisticsView.lambda$addGenerateButton$eb13574f$1(StatisticsView.java:359)
at sun.reflect.GeneratedMethodAccessor1849.invoke(Unknown Source)
...
Caused by: java.lang.IllegalArgumentException: Reporting user role
at de.symeda.sormas.api.statistics.StatisticsHelper.getAttributeGroupingKeys(StatisticsHelper.java:338)
at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:153)
at sun.reflect.GeneratedMethodAccessor5513.invoke(Unknown Source)
...
```
### Steps to Reproduce
1. Open `StatisticsView`
2. Configure `rows = Reporting user role` and `Show zero values`
3. Hit `Generate` button.

![grafik](https://user-images.githubusercontent.com/24678567/87938851-7466fb80-ca97-11ea-92fc-d4f24054b2f6.png)

### System Details
* SORMAS version: 1.42.3

### Additional Information
Happened sometimes over the last weeks.

**Comment by StefanKock** [comment]
@MateStrysewskeSym is `StatisticsCaseAttribute.REPORTING_USER_ROLE` a legitimite selectable option and if yes what is `StatisticsHelper.getAttributeGroupingKeys` supposed to reply?

**Comment by MateStrysewskeSym** [comment]
@StefanKock Yes, and the keys should be all user roles in the system.

**Comment by StefanKock** [comment]
I submitted a pull request to be reviewed by @MateStrysewskeSym .
