### ISSUE TITLE
Can't create sample

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#3221]
### Steps to Reproduce
1. Open test.sormas.netzlink.com
2. Open a case
3. Click on *New Sample* to create a new sample
=> Error notification is displayed: "An error has occurred...."

### Expected Behavior
The Pop-up window for the creation of a new Sample should be displayed

### Screenshots
![image](https://user-images.githubusercontent.com/62599627/96452451-b5e77e00-1221-11eb-8b18-ffae39b3f706.png)

### Stacktrace
```
Caused by: java.lang.ClassCastException: class com.vaadin.v7.ui.ComboBox cannot be cast to class de.symeda.sormas.ui.utils.NullableOptionGroup (com.vaadin.v7.ui.ComboBox and de.symeda.sormas.ui.utils.NullableOptionGroup are in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @488b1445)
	at de.symeda.sormas.ui.samples.SampleCreateForm.addFields(SampleCreateForm.java:45)
	at de.symeda.sormas.ui.utils.AbstractEditForm.<init>(AbstractEditForm.java:83)
	at de.symeda.sormas.ui.utils.AbstractEditForm.<init>(AbstractEditForm.java:57)
	at de.symeda.sormas.ui.samples.AbstractSampleForm.<init>(AbstractSampleForm.java:106)
	at de.symeda.sormas.ui.samples.SampleCreateForm.<init>(SampleCreateForm.java:35)
	at de.symeda.sormas.ui.samples.SampleController.createSample(SampleController.java:100)
	at de.symeda.sormas.ui.samples.SampleController.create(SampleController.java:88)
	at de.symeda.sormas.ui.samples.sampleLink.SampleListComponent.lambda$new$6aa13890$1(SampleListComponent.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
	... 87 common frames omitted
```

### System Details
* Device:
* SORMAS version: 
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NatUser

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
