### ISSUE TITLE
Case | Changing the exisiting Place of Stay for an already created Case causes an error message

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3258]
### Steps to Reproduce
1. Create a Case and Select a Place of stay
2. Reopen the case after some Data has been set for that specific Case
3. Try and Change the Place of Stay

### Expected Behavior
The Change should be allowed without any error messages

### Part of the server log file 

[2020-10-22T15:54:21.470+0300] [Payara 5.194] [INFO] [] [] [tid: _ThreadID=36 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1603371261470] [levelValue: 800] [[
  E155421.467|     > class de.symeda.sormas.api.event.TypeOfPlace cannot be cast to class java.util.Set (de.symeda.sormas.api.event.TypeOfPlace is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @49140ec2; java.util.Set is in module java.base of loader 'bootstrap') (de.symeda.sormas.ui.SormasErrorHandler.java:78)
com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in de.symeda.sormas.ui.caze.CaseDataForm$$Lambda$1472/0x0000000802032840 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
	at com.vaadin.v7.ui.AbstractField.fireValueChange(AbstractField.java:1134)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:545)
	at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:742)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:442)
	at com.vaadin.v7.ui.OptionGroup.setValue(OptionGroup.java:163)
	at com.vaadin.v7.ui.AbstractSelect.changeVariables(AbstractSelect.java:550)
	at com.vaadin.v7.ui.OptionGroup.changeVariables(OptionGroup.java:94)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:625)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:471)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:414)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
### System Details
* Device:
* SORMAS version: SORMAS Version: 1.51.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: NatUser

**Comment by MateStrysewske** [comment]
This is exactly what I documented in #2963
