### ISSUE TITLE
Improve performance by using parameters in queries [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3915]
### Problem Description

I have noticed that in `PersonService::buildSimilarityCriteriaFilter` `cb.literal(name)` is set directly, not a parameter.
Same goes for the other filters. 
Having a reusable query definition could be beneficial to improve performance.

_Originally posted by @HolgerReiseVSys in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3598#issuecomment-735841830_

Finding in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3915#issuecomment-1234240264 : The current approaches with literals use parameter bindings except for number values.

### Proposed Change

~~Replace all usages of `cb.literal(name)` by using a parameter, as explained here: https://www.baeldung.com/jpa-query-parameters#criteria-query-parameters.
The only exception to this are constants - e.g. "configuration" values of psql functions that are called like `cb.literal("[^0-9]")`.~~

- Use `<property name="hibernate.criteria.literal_handling_mode" value="bind" />` to force alywas binding.

### Acceptance Criteria

- [x] Make sure that by default bind mode is used.

**Comment by JonasCir** [comment]
Just for understanding: Does this internally make use of psql [PREPARE](https://www.postgresql.org/docs/9.3/sql-prepare.html) or does `parameter` means something different here?

**Comment by MartinWahnschaffe** [comment]
> Just for understanding: Does this internally make use of psql [PREPARE](https://www.postgresql.org/docs/9.3/sql-prepare.html) or does `parameter` means something different here?

[This](https://www.baeldung.com/jpa-query-parameters#Why-Should-We-Use-Query-Parameters) sums it up quite good:

- Embedding parameters introduce a security risk, making us vulnerable to [JPQL injection attacks](https://www.baeldung.com/sql-injection). Instead of the expected value, an attacker may inject any unexpected and possibly dangerous JPQL expression.
- Depending on the JPA implementation we use, and the heuristics of our application, the query cache may get exhausted. A new query may get built, compiled, and cached each time we use it with each new value/parameter. At a minimum, it won't be efficient, and it may also lead to an unexpected OutOfMemoryError.

**Comment by MartinWahnschaffe** [comment]
Looks like security is not a topic here. Usage of literal is internally still creating a parameter in the SQL query, as explained here:
https://vladmihalcea.com/how-does-hibernate-handle-jpa-criteria-api-literals/

**Comment by StefanKock** [comment]
Handover with @BarnaBartha: Latest commit 2a42c5e6b00a3b6ae189b2aa74b0dbe50763fd8c is WIP and not compiling due to API changes in `CriteriaBuilderHelper`. I will continue there

**Comment by StefanKock** [comment]
> Looks like security is not a topic here. Usage of literal is internally still creating a parameter in the SQL query, as explained here: https://vladmihalcea.com/how-does-hibernate-handle-jpa-criteria-api-literals/

The current approach is very tedious and judging from @MartinWahnschaffe's comment it's probably sufficient to change the `LiteralBindingMode` and check that we don't use inline parameters in SQL queries or JQL queries (if used anywhere).
```xml
<!-- add to every persistence.xml -->
<property name="hibernate.criteria.literal_handling_mode" value="bind" />
```

**Comment by StefanKock** [comment]
I confirmed with @MartinWahnschaffe that just toggling to BIND mode fulfills what we wanted to achieve in this ticket.

**Comment by StefanKock** [comment]
While implementing this ticket we noticed that the approach to bind parameters was mostly already done, but could be configured with Hibernate more strict (84fc827). In consequence the parameter binding validation kicked in and showed some incompatible parameters where the data types needed to be fixed (3fae598). 

There is a risk that in some edge case usages without unit test coverage a parameter binding is still type-incompatible and will fail, resulting for example in such stack traces.

```bash
java.lang.IllegalArgumentException: Parameter value [2592000] did not match expected type [java.lang.Double (n/a)]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)

java.lang.IllegalArgumentException: Parameter value [97] did not match expected type [de.symeda.sormas.backend.person.Person (n/a)]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
```
There was no attempt done to measure the performance impact, we went by the book to better reuse precompiled queries. The effect can be seen in executed queries where now also number parameters are bound instead of placed inline.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(9f50300).

**Comment by StefanKock** [comment]
One collateral finding on test-de from now:
```bash
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.IllegalArgumentException: Parameter value [251119] did not match expected type [de.symeda.sormas.backend.caze.Case (n/a)]
        at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
        ... 112 more
Caused by: java.lang.IllegalArgumentException: Parameter value [251119] did not match expected type [de.symeda.sormas.backend.caze.Case (n/a)]
        at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
        at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
        at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
        at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
        at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:501)
        at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:122)
        at org.hibernate.query.criteria.internal.compile.CriteriaCompiler$1$1.bind(CriteriaCompiler.java:135)
        at org.hibernate.query.criteria.internal.CriteriaQueryImpl$1.buildCompiledQuery(CriteriaQueryImpl.java:364)
        at org.hibernate.query.criteria.internal.compile.CriteriaCompiler.compile(CriteriaCompiler.java:165)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:774)
        at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:498)
        at de.symeda.sormas.backend.contact.ContactFacadeEjb.getContactCountsByCasesForDashboard(ContactFacadeEjb.java:1302)
...
        at de.symeda.sormas.api.contact.__ContactFacade_Remote_DynamicStub.getContactCountsByCasesForDashboard(de/symeda/sormas/api/contact/__ContactFacade_Remote_DynamicStub.java)
        at de.symeda.sormas.api.contact._ContactFacade_Wrapper.getContactCountsByCasesForDashboard(de/symeda/sormas/api/contact/_ContactFacade_Wrapper.java)
        at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.updateCaseCountsAndSourceCasesLabels(ContactsDashboardView.java:269)
        at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.refreshDashboard(ContactsDashboardView.java:475)
        at de.symeda.sormas.ui.dashboard.contacts.ContactsDashboardView.enter(ContactsDashboardView.java:144)
```

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(5111f71).
