### ISSUE TITLE
Creating a positive pathogen test for an event participant whose event has no disease produces an error

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#4545]
### Bug Description
Creating a positive pathogen test for an event participant whose event has no disease produces an error (NullPointer)

### System Details
* Device: PC
* SORMAS version: 1.58.0-SNAPSHOT

### Additional Information
`Caused by: java.lang.NullPointerException: null
	at de.symeda.sormas.ui.samples.PathogenTestController.showConvertEventParticipantToCaseDialog(PathogenTestController.java:231)
	at de.symeda.sormas.ui.samples.PathogenTestController.lambda$savePathogenTest$9(PathogenTestController.java:217)
	at de.symeda.sormas.ui.samples.PathogenTestController.lambda$savePathogenTest$10(PathogenTestController.java:222)
	at de.symeda.sormas.ui.samples.SampleDataView.lambda$initView$1(SampleDataView.java:159)
	at de.symeda.sormas.ui.samples.PathogenTestController.savePathogenTest(PathogenTestController.java:222)
	at de.symeda.sormas.ui.samples.PathogenTestController.lambda$getPathogenTestCreateComponent$0(PathogenTestController.java:96)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:525)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:392)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:412)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:285)
	at jdk.internal.reflect.GeneratedMethodAccessor780.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:712)
	... 87 common frames omitted
]]`

**Comment by bernardsilenou** [comment]
I think we should not allow the creating of pathogen test if event has no disease in the first place an d keep the followup logic as it is? Add a warning message for users to assign disease to event first.
Reason being that after the creation of each test, there is  a comparison of the disease of pathogen test and that of event in deciding the next step to take: converting ep to a case or create a new case of another disease and link to the same person of the ep.

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou I was wondering if it does not make sense to make all desease-fields mandatory with the option to select "not clear" or "not definded yet" or similar else. I've read many times that not selecting the desease can cause errors and that could be th easiest way to solve it.

To have the option, that it is not clear which desease is affected could be only shown if for the instance are more then one deseases are selected. In Germany Sormas is only used for Covid19, so all persons in it are either cases, contacts or ep for this desease. Maybe the other option is to set it by default to Covid19 if only these desease is active for the instance.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 

> @bernardsilenou I was wondering if it does not make sense to make all disease-fields mandatory with the option to select "not clear" or "not definded yet" or similar else. I've read many times that not selecting the disease can cause errors and that could be th easiest way to solve it.
> 
If this is about the disease of the event, then you are absolutely right. You can have an event and you do not know the disease involved, just as you can have a sick person and do not know the disease but still want to notify this situation before getting results from the lab.
If you do not restrict your SORMAS instance to only one disease, eg COVID-19, then there are addition two options just as you mentioned: Not yet defined ("not definded yet") and Other epidemic diseases ("not clear")
You can activate these 2 options on your system.

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou But then it would make sense to make this field either pre-filled  or mandatory if only one desease is handled (Covid19) in Sormas. Otherwise you have events without an desease, which causes problems.

**Comment by AndyBakcsy-she** [comment]
@ChristopherRiedel  The NullPointer error is not displayed anymore but I am receiving a different type of error in this case. Please check the attached serve_log file :
[server_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6077890/server_log.txt)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas version 1.58.0-snapshot on test.sormas.netzlink.com
