### ISSUE TITLE
Saving a case does not work for current snapshot

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4721]
### Bug Description
The current build from `development` does not allow to save a case.

### Steps to Reproduce
1. git fetch and build
2. Login and create a case
3. :boom: 

### Expected Behavior
Case is saved

### Screenshots
![error](https://user-images.githubusercontent.com/20031875/110763406-22572e00-8252-11eb-87c8-c3a9a414b8c9.png)

### Stacktrace

<details><summary>details</summary>
<p>

```

Caused by: java.lang.NullPointerException
	at de.symeda.sormas.ui.caze.CaseDataForm.addFields(CaseDataForm.java:415)
	at de.symeda.sormas.ui.caze.CaseDataForm.<init>(CaseDataForm.java:273)
	at de.symeda.sormas.ui.caze.CaseController.getCaseDataEditComponent(CaseController.java:656)
	at de.symeda.sormas.ui.caze.CaseDataView.initView(CaseDataView.java:109)
	at de.symeda.sormas.ui.caze.AbstractCaseView.enter(AbstractCaseView.java:216)
	at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
	at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
	at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
	at com.vaadin.navigator.View.beforeLeave(View.java:79)
	at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
	at de.symeda.sormas.ui.caze.CaseController.navigateToView(CaseController.java:273)
	at de.symeda.sormas.ui.caze.CaseController.navigateToView(CaseController.java:259)
	at de.symeda.sormas.ui.caze.CaseController.lambda$getCaseCreateComponent$4(CaseController.java:548)
	at de.symeda.sormas.ui.caze.CaseController.selectOrCreateCase(CaseController.java:606)
	at de.symeda.sormas.ui.caze.CaseController.lambda$getCaseCreateComponent$5(CaseController.java:544)
	at de.symeda.sormas.ui.person.PersonController.selectOrCreatePerson(PersonController.java:142)
	at de.symeda.sormas.ui.caze.CaseController.lambda$getCaseCreateComponent$6(CaseController.java:541)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:502)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:368)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:388)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:712)
	... 88 more

```
</p>
</details>

### System Details
* SORMAS version: recent SNAPSHOT
* User Role: admin, reported for other roles as well

**Comment by JonasCir** [comment]
`DiseaseConfigurationDto.getExtendedClassification()` returns `null` which fails [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java#L415).

**Comment by JonasCir** [comment]
The problem is that `DiseaseConfigurationService.getDiseaseConfiguration()` is queried with `disease='COVID-19'`, however, in the `diseaseconfiguration` DB there is only `CORONAVIRUS`.

**Comment by JonasCir** [comment]
Ok problem is that the columns added in https://github.com/hzi-braunschweig/SORMAS-Project/pull/4692 are `null` if you do a fresh start with an empty DB. They should be filled though :D
This causes the bug :beetle:

**Comment by MateStrysewske** [comment]
@JonasCir Thanks a lot for investigating! I'll fix it in #4692 and close this issue.

**Comment by JonasCir** [comment]
`diseaseConfiguration.getExtendedClassification()` still returns `null` b/c the associated table columns is empty
![error](https://user-images.githubusercontent.com/20031875/110957540-fcae4f80-834b-11eb-8f04-c4b37c62e5ec.png)

**Comment by JonasCir** [comment]
Ok here is what's happening:
The database is setup correct (I guess), however, `StartupShutdownService.createMissingDiseaseConfigurations` overwrites `extendedclassification` column with null

**Comment by JonasCir** [comment]
I got a fix up soon
