### ISSUE TITLE
Error saving person

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#5492]
### Bug Description

Saving persons on systems without external journal results in error on UI.

### Expected Behavior
No error

### Screenshots
![image](https://user-images.githubusercontent.com/8166805/118937616-63587680-b956-11eb-8f02-74b53e4db212.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
Caused by: java.lang.NullPointerException: null
	at de.symeda.sormas.ui.person.PersonController.savePerson(PersonController.java:242)
	at de.symeda.sormas.ui.person.PersonController.lambda$getPersonEditComponent$2(PersonController.java:167)

**Comment by BarnaBartha** [comment]
was fixed in the meantime with corresponding feature ticket!
