### ISSUE TITLE
[S2S] Cases > `Revoke Share` results in error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5887]
### Bug Description

Cases > When sharing a case with another SORMAS instance, but revoking the share at a later stage results in an error message appearing, and the data not being revoked.

### Steps to Reproduce

1. de2 Cases > Share > Share with GA (no values selected in pop-up) > Share successful (data shows up on de1 instance)
2. After a few minutes, choose `Revoke` in de2 > Prompt to confirm revocation > Select Yes > Error message (partially in German, despite English setting of server - separate issue?)
3. Data still visible on de1 instance

### Expected Behavior

Revoke should withdraw the data from the other instance (de1), not produce an error message.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/122778720-83f55280-d2ad-11eb-9ef4-5e8aefd2d304.png)

### System Details

* Device: 
* SORMAS version: 1.61 Snapshot
* Android version/Browser: Chrome
* Server URL: https://test-de2.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

https://test-de2.sormas.netzlink.com/sormas-ui/#!cases/data/T4CSKZ-KRPXUP-NOEEVF-QNPV2HSU

**Comment by JonasCir** [comment]
```
ERROR de.symeda.sormas.backend.sormastosormas.SormasToSormasEncryptionService - Could not decrypt and verify data
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (byte[])"["URUTHY-ZSFP4I-LWL7SO-JQRMSGEI"]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:714)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3266)
	at de.symeda.sormas.backend.sormastosormas.SormasToSormasEncryptionService.decryptAndVerify(SormasToSormasEncryptionService.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.61.0-SNAPSHOT using test-de1 and test-de2 environments
