### ISSUE TITLE
Endpoint for case creation is no longer working after the last deployment

### ISSUE THREAD

**Issue by Mihai-Bota** [hzi-braunschweig/SORMAS-Project#5989]
Bug Description

This issue occurs in the https://test-performance.sormas.netzlink.com environment
Steps to Reproduce (easiest way):
1. Use the testing automation project https://github.com/hzi-braunschweig/SORMAS-Project/tree/development/sormas-e2e-tests
2. Run the test from: sormas-e2e-tests/src/test/resources/features/sanity/api/Api.feature
3. Check the console:
Expected result:
For the case creation endpoint an: [
    "OK"
] message shall be returned.
Actual result:
For the case creation endpoint an: [
    "ERROR"
] message is returned.
Attachment: 
![image](https://user-images.githubusercontent.com/46056983/123765685-a3543700-d8ce-11eb-8618-582eb4e6becb.png)
Note: question - is this a bug or an intended change? It occurs after the deployment from 2 pm CET on 28.06.2021.

**Comment by StefanKock** [comment]
We found this in the log files:
```
You have to specify a valid responsible region (de.symeda.sormas.rest.EntityDtoResource.java:40)
de.symeda.sormas.api.utils.ValidationRuntimeException: You have to specify a valid responsible region
```

```
[2021-06-29T16:27:52.073+0200] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=74 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1624976872073] [levelValue: 800] [[
  E162752.072|     > CaseDataDto 1fd7443b-22ff-413c-8a7b-7921ddf5dd33
Sie müssen ein gültiges zuständiges Bundesland angeben (de.symeda.sormas.rest.EntityDtoResource.java:40)
de.symeda.sormas.api.utils.ValidationRuntimeException: Sie müssen ein gültiges zuständiges Bundesland angeben
        at de.symeda.sormas.backend.caze.CaseFacadeEjb.validate(CaseFacadeEjb.java:1602)
        at de.symeda.sormas.backend.caze.CaseFacadeEjb.caseSave(CaseFacadeEjb.java:1508)
        at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1500)
        at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:1383)
        at jdk.internal.reflect.GeneratedMethodAccessor2891.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4796)
```

**Comment by StefanKock** [comment]
Suspect that might have changed and causes this problem: #5852

**Comment by VGitVlad** [comment]
Fixed and merged.
