### ISSUE TITLE
Importing default (sub)continent and country data via UI Button errors and fails to write error log

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#6558]
### Bug Description
When starting a fresh system (latest `development`), the import of standard continent, subcontinent, and country data fails.

``` ERROR de.symeda.sormas.ui.importer.InfrastructureImporter - /opt/sormas/temp/sormas_temp_error_report_WNF4FJ_2021-08-31.csv (No such file or directory)
2021-08-31T12:41:31.208710417Z java.io.FileNotFoundException: /opt/sormas/temp/sormas_temp_error_report_WNF4FJ_2021-08-31.csv (No such file or directory)
2021-08-31T12:41:31.208713964Z 	at java.base/java.io.FileOutputStream.open0(Native Method)
2021-08-31T12:41:31.208716789Z 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
2021-08-31T12:41:31.208719437Z 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
2021-08-31T12:41:31.208722547Z 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
2021-08-31T12:41:31.208725795Z 	at java.base/java.io.FileWriter.<init>(FileWriter.java:66)
2021-08-31T12:41:31.208729256Z 	at de.symeda.sormas.ui.importer.DataImporter.createErrorReportWriter(DataImporter.java:305)
2021-08-31T12:41:31.208732438Z 	at de.symeda.sormas.ui.importer.DataImporter.runImport(DataImporter.java:229)
2021-08-31T12:41:31.208755327Z 	at de.symeda.sormas.ui.importer.DataImporter.lambda$startImport$3(DataImporter.java:159)
2021-08-31T12:41:31.208758484Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-08-31T12:41:31.208762016Z 
```

### Steps to Reproduce
1. Clean `development` build and empty DB
2. Login as admin
3. Go to settings, continents, and then select the import default data button

### Expected Behavior

- The data is successfully imported and no error is thrown
- In case of error, print the log file and advise user how to resolve the problem

### System Details
* Device: Linux
* SORMAS version: latest development
* User Role: admin

**Comment by JonasCir** [comment]
@AndyBakcsy-she 
This now gives me:
```
ERROR de.symeda.sormas.ui.SormasErrorHandler - Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
2021-09-03T09:50:09.004258764Z com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
2021-09-03T09:50:09.004260496Z 	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
2021-09-03T09:50:09.004262124Z 	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
2021-09-03T09:50:09.004263732Z 	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442)
2021-09-03T09:50:09.004265422Z 	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407)
2021-09-03T09:50:09.004267003Z 	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
2021-09-03T09:50:09.004268570Z 	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
2021-09-03T09:50:09.004270198Z 	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
2021-09-03T09:50:09.004271753Z 	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1608)
2021-09-03T09:50:09.004279569Z 	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)
2021-09-03T09:50:09.004281398Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
2021-09-03T09:50:09.004282929Z 	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
2021-09-03T09:50:09.004284604Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
2021-09-03T09:50:09.004286216Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
2021-09-03T09:50:09.004288081Z 	at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
2021-09-03T09:50:09.004289722Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
2021-09-03T09:50:09.004291298Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
2021-09-03T09:50:09.004292823Z 	at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:72)
2021-09-03T09:50:09.004295039Z 	at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
2021-09-03T09:50:09.004296667Z 	at jdk.internal.reflect.GeneratedMethodAccessor514.invoke(Unknown Source)
2021-09-03T09:50:09.004298316Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-03T09:50:09.004299983Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-03T09:50:09.004301565Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
2021-09-03T09:50:09.004303165Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
2021-09-03T09:50:09.004304779Z 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
2021-09-03T09:50:09.004306307Z 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
2021-09-03T09:50:09.004307810Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
2021-09-03T09:50:09.004309419Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-09-03T09:50:09.004311049Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
2021-09-03T09:50:09.004312663Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
2021-09-03T09:50:09.004314270Z 	at jdk.internal.reflect.GeneratedMethodAccessor217.invoke(Unknown Source)
2021-09-03T09:50:09.004315862Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-03T09:50:09.004317426Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-03T09:50:09.004318934Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-09-03T09:50:09.004322232Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-09-03T09:50:09.004323899Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-09-03T09:50:09.004325543Z 	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
2021-09-03T09:50:09.004327240Z 	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
2021-09-03T09:50:09.004328844Z 	at jdk.internal.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)
2021-09-03T09:50:09.004330443Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-03T09:50:09.004332018Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-03T09:50:09.004333675Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-09-03T09:50:09.004335326Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-09-03T09:50:09.004336884Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
2021-09-03T09:50:09.004338553Z 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
2021-09-03T09:50:09.004340131Z 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
2021-09-03T09:50:09.004341708Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
2021-09-03T09:50:09.004343318Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
2021-09-03T09:50:09.004344885Z 	at com.sun.proxy.$Proxy779.doFilter(Unknown Source)
2021-09-03T09:50:09.004346394Z 	at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
2021-09-03T09:50:09.004347931Z 	at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:65)
2021-09-03T09:50:09.004349444Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
2021-09-03T09:50:09.004351103Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
2021-09-03T09:50:09.004352731Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
2021-09-03T09:50:09.004354315Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
2021-09-03T09:50:09.004355884Z 	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
2021-09-03T09:50:09.004357407Z 	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
2021-09-03T09:50:09.004358923Z 	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
2021-09-03T09:50:09.004360411Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
2021-09-03T09:50:09.004363418Z 	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
2021-09-03T09:50:09.004365178Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
2021-09-03T09:50:09.004366856Z 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
2021-09-03T09:50:09.004368510Z 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
2021-09-03T09:50:09.004370119Z 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
2021-09-03T09:50:09.004371960Z 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
2021-09-03T09:50:09.004373568Z 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
2021-09-03T09:50:09.004375126Z 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
2021-09-03T09:50:09.004376708Z 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
2021-09-03T09:50:09.004378369Z 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
2021-09-03T09:50:09.004379972Z 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
2021-09-03T09:50:09.004381571Z 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
2021-09-03T09:50:09.004383166Z 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
2021-09-03T09:50:09.004384672Z 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
2021-09-03T09:50:09.004386240Z 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
2021-09-03T09:50:09.004387796Z 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
2021-09-03T09:50:09.004389338Z 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
2021-09-03T09:50:09.004391023Z 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
2021-09-03T09:50:09.004392660Z 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
2021-09-03T09:50:09.004394257Z 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
2021-09-03T09:50:09.004395877Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-09-03T09:50:09.004397379Z Caused by: java.lang.reflect.InvocationTargetException: null
2021-09-03T09:50:09.004398890Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-03T09:50:09.004400424Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-03T09:50:09.004401973Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-03T09:50:09.004405230Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-03T09:50:09.004406856Z 	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
2021-09-03T09:50:09.004408447Z 	... 78 common frames omitted
2021-09-03T09:50:09.004410225Z Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in de.symeda.sormas.ui.configuration.infrastructure.AbstractImportDefaultCsvLayout$$Lambda$2401/0x0000000801dd7840 failed.
2021-09-03T09:50:09.004412064Z 	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:726)
2021-09-03T09:50:09.004413623Z 	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
2021-09-03T09:50:09.004415129Z 	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
2021-09-03T09:50:09.004416626Z 	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190)
2021-09-03T09:50:09.004418289Z 	at com.vaadin.ui.Button.fireClick(Button.java:384)
2021-09-03T09:50:09.004419831Z 	at com.vaadin.ui.Button$1.click(Button.java:57)
2021-09-03T09:50:09.004421396Z 	... 83 common frames omitted
2021-09-03T09:50:09.004422908Z Caused by: java.lang.NullPointerException: null
2021-09-03T09:50:09.004424444Z 	at de.symeda.sormas.ui.configuration.infrastructure.ImportDefaultContinentsLayout.doImport(ImportDefaultContinentsLayout.java:52)
2021-09-03T09:50:09.004426062Z 	at de.symeda.sormas.ui.configuration.infrastructure.AbstractImportDefaultCsvLayout.lambda$new$61446b05$1(AbstractImportDefaultCsvLayout.java:47)
2021-09-03T09:50:09.004427672Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-03T09:50:09.004429194Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-03T09:50:09.004430840Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-03T09:50:09.004432457Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-03T09:50:09.004434034Z 	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
2021-09-03T09:50:09.004435645Z 	... 88 common frames omitted
2021-09-03T09:50:09.004437133Z |#]
2021-09-03T09:50:09.004438608Z 

```

**Comment by vidi42** [comment]
@JonasCir this is already documented in #6605
