### ISSUE TITLE
Default Import for continents / subcontinents and countries is failing

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#6605]
### Bug Description
As a result of #5459 the default import for continents, subcontinents and countries is failing.

```
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.ui.configuration.infrastructure.ImportDefaultContinentsLayout.doImport(ImportDefaultContinentsLayout.java:52)
	at de.symeda.sormas.ui.configuration.infrastructure.AbstractImportDefaultCsvLayout.lambda$new$61446b05$1(AbstractImportDefaultCsvLayout.java:47)
	... 93 more
```

### Steps to Reproduce
1. Login with admin
2. Navigate to continents and do the `Import Default Continents` (with or without override data)
3. The system will then display a generic error message

### Expected Behavior
No generic error message shown and the import runs.

### System Details
* Device:
* SORMAS version: 1.64-SNAPSHOT
* Android version/Browser:
* Server URL: localhost (development branch)
* User Role:

**Comment by vidi42** [comment]
Fixes with #6627
