### ISSUE TITLE
Dashboard | Selecting Show Regions under Map Layers produces server error

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7079]
### Steps to Reproduce

1. Go to Dashboard and select Contacts (upper right side)
2.  Select a Disease and apply filters
3. Go to the Layers section under the Map 
4. Check the Show Regions checkbox 

### Expected Behavior
There should be no server error

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/139110789-6b9a3dd1-1646-4f9c-9112-6d33c41f6a90.png)

[server_error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7427936/server_error.txt)
```
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.lambda$getCaseMeasurePerDistrict$76(CaseFacadeEjb.java:3018)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.getCaseMeasurePerDistrict(CaseFacadeEjb.java:3035)
...
```

### System Details

* Device:
* SORMAS version: 1.65.0-snapshot 
* Android version/Browser: Chrome 
* Server URL: localhost
* User Role: NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
