### ISSUE TITLE
jgitflow: release-finish fails (blocks automatic release process) [?]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7181]
### Bug Description

```
[ERROR] Failed to execute goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish (default-cli) on project sormas-base: Execution default-cli of goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish (default-cli) on project sormas-base: Execution default-cli of goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
...
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-finish failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.atlassian.jgitflow.core.command.AbstractGitFlowCommand.failedResult(AbstractGitFlowCommand.java:133)
	at com.atlassian.jgitflow.core.command.AbstractGitFlowCommand.doPushIfNeeded(AbstractGitFlowCommand.java:104)
	at com.atlassian.jgitflow.core.command.ReleaseFinishCommand.call(ReleaseFinishCommand.java:148)
	at com.atlassian.maven.plugins.jgitflow.manager.DefaultFlowReleaseManager.finish(DefaultFlowReleaseManager.java:99)
	at com.atlassian.maven.plugins.jgitflow.mojo.ReleaseFinishMojo.execute(ReleaseFinishMojo.java:174)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```
### Steps to Reproduce

1. Run Release promotion, `release-finish` fails

### Expected Behavior

Release promotion does not fail.

### Additional Information

- ~~It's likely that #6868 caused this problem.~~
- Here we can look into the source code of the plugin: https://bitbucket.org/atlassian/jgit-flow/src/master/jgit-flow-core/src/main/java/com/atlassian/jgitflow/core/command/AbstractGitFlowCommand.java

<details>
<summary>Workaround with shell access to system host:</summary>

```bash

su jenkins
cd ~/workspace/sormas-Build


# Change version number accordingly to the version that the job failed to push
git push origin development
git checkout master
git push origin master
git push origin v1.65.0
git push origin --delete release-1.65.0
git branch -d release-1.65.0
```
</details>

**Comment by StefanKock** [comment]
The NPE comes when the `ReleaseFinishCommand` tries to push the development branch after all jgitflow magic locally succeeded.

```java
// ReleaseFinishCommand
                {
// l 148              doPushIfNeeded(extension, !noTag, gfConfig.getDevelop(), gfConfig.getMaster(), prefixedBranchName);
                }
```

Since all commits and tags existed locally, it was possible to push the changes and therefore unblock the release of 1.65.0.
The problem is still not solved though.

**Comment by StefanKock** [comment]
Checking git repo on system did not show any hints.

<details>
<summary>Result of: git status / log / config</summary>

```bash

bash-4.2$ git status
# On branch development
# Your branch is ahead of 'origin/development' by 7 commits.
#   (use "git push" to publish your local commits)
#
nothing to commit, working directory clean
```
```bash
bash-4.2$ git log
commit 1cdc596ed197890c16369f927d0726a31047cd7b
Author: jenkins <jenkins@a81-14-202-141.net-htp.de>
Date:   Mon Nov 8 13:53:14 2021 +0100

    [GITFLOW]Updating develop poms back to pre merge state

commit fbe0ac1d078c5e80e8940948d33e1f5d8b824a65
Merge: bcf4b54 23586b9
Author: jenkins <jenkins@a81-14-202-141.net-htp.de>
Date:   Mon Nov 8 13:53:11 2021 +0100

    [GITFLOW]merging 'master' into 'development'

commit bcf4b541fe50156c70f3a9023629031df868da47
Author: jenkins <jenkins@a81-14-202-141.net-htp.de>
Date:   Mon Nov 8 13:53:09 2021 +0100

    [GITFLOW]updating develop poms to master versions to avoid merge conflicts

commit 23586b98c5a55391c2ebd743e6c16835d9b12b73
Merge: 47f3539 30575f3
Author: jenkins <jenkins@a81-14-202-141.net-htp.de>
Date:   Mon Nov 8 13:52:58 2021 +0100

    [GITFLOW]merging 'release-1.65.0' into 'master'

...
```
```bash
bash-4.2$ git config --list
core.autocrlf=false
credential.helper=store --file ~/.my-credentials
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.autocrlf=false
core.eol=lf
remote.origin.url=https://github.com/hzi-braunschweig/SORMAS-Project.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
gitflow.branch.master=master
gitflow.branch.develop=development
branch.development.remote=origin
branch.development.merge=refs/heads/development
gitflow.prefix.feature=feature-
gitflow.prefix.release=release-
gitflow.prefix.hotfix=hotfix-
gitflow.prefix.support=support/
gitflow.prefix.versiontag=v
branch.release-1.65.0.remote=origin
branch.release-1.65.0.merge=refs/heads/release-1.65.0
```

</details>

**Comment by StefanKock** [comment]
My suspicion is that in `org.eclipse.jgit.transport.PushProcess.execute(...)` the call of `prepareRemoteUpdates()` returns no `RemoteRefUpdate` and therefore skips the push (so no result is set as far as I can see), but the afterwards check in `AbstractGitFlowCommand` processes all given `RemoteRefUpdate` objects.

The question is, why the push is skipped. The code freeze was at first not in place (only later), but did not alter the problem.

```java
// PushProcess
				final Map<String, RemoteRefUpdate> preprocessed = prepareRemoteUpdates();
				if (transport.isDryRun())
					modifyUpdatesForDryRun();
				else if (!preprocessed.isEmpty())
					connection.push(monitor, preprocessed, out);
```

**Comment by StefanKock** [comment]
Workaround is now documented in the ticket description.

**Comment by StefanKock** [comment]
New ideas to check:
1. The login credentials might differ in jgitflow from the ones that jenkins user itself uses.
2. I'm wondering if the mergefreeze status check (see #7543) interferes with our release process. We should test it with the next release.

**Comment by StefanKock** [comment]
I now disabled the mergefreeze status check. This was the previous state:
![grafik](https://user-images.githubusercontent.com/24678567/153160742-4f42300b-39b6-40b7-9c84-bac1bee049cc.png)

**Comment by vidi42** [comment]
> I now disabled the mergefreeze status check.
@StefanKock does this mean that the mergefreeze no longer blocks any PR merges when it's active?

**Comment by StefanKock** [comment]
> > I now disabled the mergefreeze status check.
> 
> @StefanKock does this mean that the mergefreeze no longer blocks any PR merges when it's active?

Yes, disabled = not active
