### ISSUE TITLE
[S2S] Enabeled `EDIT_INFRASTRUCTURE_DATA` feature prevents sucessful central sync

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7530]
### Bug Description
Enabeled `EDIT_INFRASTRUCTURE_DATA` feature prevents sucessful central infrastructure sync.

<details>
<summary>Stacktrace</summary>
<br/>

```

ERROR de.symeda.sormas.backend.infrastructure.central.CentralInfraSyncFacade - Could not sync with central: %s
2021-12-15T14:45:56.755235273Z de.symeda.sormas.api.utils.ValidationRuntimeException: Infrastrukturdaten sind gesperrt und können nicht aktualisiert werden
2021-12-15T14:45:56.755239489Z 	at de.symeda.sormas.backend.infrastructure.AbstractInfrastructureEjb.checkInfraDataLocked(AbstractInfrastructureEjb.java:99)
2021-12-15T14:45:56.755243308Z 	at de.symeda.sormas.backend.infrastructure.AbstractInfrastructureEjb.save(AbstractInfrastructureEjb.java:41)
2021-12-15T14:45:56.755246809Z 	at de.symeda.sormas.backend.infrastructure.continent.ContinentFacadeEjb.save(ContinentFacadeEjb.java:169)
2021-12-15T14:45:56.755250407Z 	at de.symeda.sormas.backend.infrastructure.continent.ContinentFacadeEjb$ContinentFacadeEjbLocal.save(ContinentFacadeEjb.java:239)
2021-12-15T14:45:56.755254146Z 	at de.symeda.sormas.backend.common.AbstractBaseEjb.save(AbstractBaseEjb.java:46)
2021-12-15T14:45:56.755257725Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755277253Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755280666Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755284189Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755287543Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
2021-12-15T14:45:56.755290991Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
2021-12-15T14:45:56.755294400Z 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
2021-12-15T14:45:56.755297952Z 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
2021-12-15T14:45:56.755301615Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
2021-12-15T14:45:56.755305081Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755308684Z 	at org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
2021-12-15T14:45:56.755344050Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755348671Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755352403Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755356158Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755359693Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755363105Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755366608Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755390169Z 	at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:30)
2021-12-15T14:45:56.755394119Z 	at jdk.internal.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
2021-12-15T14:45:56.755397833Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755401684Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755405241Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755425320Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755428762Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755432290Z 	at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:47)
2021-12-15T14:45:56.755456303Z 	at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
2021-12-15T14:45:56.755460218Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755464081Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755467853Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755471588Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755475234Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755478993Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
2021-12-15T14:45:56.755482812Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
2021-12-15T14:45:56.755486564Z 	at jdk.internal.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
2021-12-15T14:45:56.755495285Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755515537Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755518792Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755521936Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755525141Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755528543Z 	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
2021-12-15T14:45:56.755550813Z 	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
2021-12-15T14:45:56.755554656Z 	at jdk.internal.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
2021-12-15T14:45:56.755558126Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755561842Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755565637Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755569250Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755572548Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
2021-12-15T14:45:56.755576209Z 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
2021-12-15T14:45:56.755579770Z 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
2021-12-15T14:45:56.755583592Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
2021-12-15T14:45:56.755587313Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
2021-12-15T14:45:56.755591267Z 	at com.sun.proxy.$Proxy541.save(Unknown Source)
2021-12-15T14:45:56.755594899Z 	at de.symeda.sormas.backend.infrastructure.continent.__EJB31_Generated__ContinentFacadeEjb$ContinentFacadeEjbLocal__Intf____Bean__.save(Unknown Source)
2021-12-15T14:45:56.755598812Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-12-15T14:45:56.755603335Z 	at de.symeda.sormas.backend.infrastructure.central.CentralInfraSyncFacade.loadAndStore(CentralInfraSyncFacade.java:104)
2021-12-15T14:45:56.755607241Z 	at de.symeda.sormas.backend.infrastructure.central.CentralInfraSyncFacade.loadAndStoreContinents(CentralInfraSyncFacade.java:137)
2021-12-15T14:45:56.755611068Z 	at de.symeda.sormas.backend.infrastructure.central.CentralInfraSyncFacade.syncAll(CentralInfraSyncFacade.java:118)
2021-12-15T14:45:56.755614926Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755622505Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755626588Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755630403Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755633815Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
2021-12-15T14:45:56.755637483Z 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
2021-12-15T14:45:56.755641107Z 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
2021-12-15T14:45:56.755644676Z 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
2021-12-15T14:45:56.755648495Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
2021-12-15T14:45:56.755652306Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755655966Z 	at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:30)
2021-12-15T14:45:56.755659772Z 	at jdk.internal.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
2021-12-15T14:45:56.755663176Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755666965Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755670825Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755674458Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755678460Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755682271Z 	at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:47)
2021-12-15T14:45:56.755686039Z 	at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
2021-12-15T14:45:56.755690012Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755694090Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755697797Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755701612Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755705368Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755709092Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
2021-12-15T14:45:56.755717240Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
2021-12-15T14:45:56.755721668Z 	at jdk.internal.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
2021-12-15T14:45:56.755725385Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755728872Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755732738Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755736306Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755739578Z 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
2021-12-15T14:45:56.755743572Z 	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
2021-12-15T14:45:56.755747661Z 	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
2021-12-15T14:45:56.755751397Z 	at jdk.internal.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
2021-12-15T14:45:56.755755019Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755758857Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755762438Z 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
2021-12-15T14:45:56.755766450Z 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
2021-12-15T14:45:56.755770207Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
2021-12-15T14:45:56.755774134Z 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
2021-12-15T14:45:56.755778369Z 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
2021-12-15T14:45:56.755781985Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
2021-12-15T14:45:56.755785765Z 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
2021-12-15T14:45:56.755789479Z 	at com.sun.proxy.$Proxy522.syncAll(Unknown Source)
2021-12-15T14:45:56.755793084Z 	at de.symeda.sormas.backend.infrastructure.central.__EJB31_Generated__CentralInfraSyncFacade__Intf____Bean__.syncAll(Unknown Source)
2021-12-15T14:45:56.755797218Z 	at de.symeda.sormas.backend.common.StartupShutdownService.startup(StartupShutdownService.java:226)
2021-12-15T14:45:56.755802162Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755806161Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755816165Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755820672Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755824607Z 	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1022)
2021-12-15T14:45:56.755828633Z 	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
2021-12-15T14:45:56.755832386Z 	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
2021-12-15T14:45:56.755836530Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
2021-12-15T14:45:56.755840413Z 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
2021-12-15T14:45:56.755844343Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755848048Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755851687Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755855435Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755859066Z 	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
2021-12-15T14:45:56.755862897Z 	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
2021-12-15T14:45:56.755867444Z 	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
2021-12-15T14:45:56.755871482Z 	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
2021-12-15T14:45:56.755875472Z 	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
2021-12-15T14:45:56.755879376Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.755883265Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.755887634Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.755891504Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.755895180Z 	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
2021-12-15T14:45:56.755899027Z 	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
2021-12-15T14:45:56.755902696Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:418)
2021-12-15T14:45:56.755906498Z 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:381)
2021-12-15T14:45:56.755913547Z 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2062)
2021-12-15T14:45:56.755917401Z 	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:529)
2021-12-15T14:45:56.755921440Z 	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
2021-12-15T14:45:56.755925092Z 	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:687)
2021-12-15T14:45:56.755928878Z 	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:421)
2021-12-15T14:45:56.755932762Z 	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
2021-12-15T14:45:56.755936464Z 	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
2021-12-15T14:45:56.755940295Z 	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:159)
2021-12-15T14:45:56.755944022Z 	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:171)
2021-12-15T14:45:56.755947655Z 	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
2021-12-15T14:45:56.755951962Z 	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:293)
2021-12-15T14:45:56.755955763Z 	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:364)
2021-12-15T14:45:56.755959362Z 	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
2021-12-15T14:45:56.755963049Z 	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:580)
2021-12-15T14:45:56.755984682Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
2021-12-15T14:45:56.755988177Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
2021-12-15T14:45:56.756010409Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-12-15T14:45:56.756013956Z 	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
2021-12-15T14:45:56.756017409Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
2021-12-15T14:45:56.756021071Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
2021-12-15T14:45:56.756024744Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
2021-12-15T14:45:56.756028430Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-12-15T14:45:56.756032120Z 	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
2021-12-15T14:45:56.756035851Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
2021-12-15T14:45:56.756039672Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
2021-12-15T14:45:56.756046609Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
2021-12-15T14:45:56.756050667Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
2021-12-15T14:45:56.756054375Z 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
2021-12-15T14:45:56.756057941Z 	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:183)
2021-12-15T14:45:56.756061758Z 	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
2021-12-15T14:45:56.756065390Z 	at fish.payara.boot.runtime.BootCommand.execute(BootCommand.java:69)
2021-12-15T14:45:56.756069015Z 	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:136)
2021-12-15T14:45:56.756072604Z 	at fish.payara.boot.runtime.BootCommands.executeCommands(BootCommands.java:130)
2021-12-15T14:45:56.756076375Z 	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:294)
2021-12-15T14:45:56.756080851Z 	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:133)
2021-12-15T14:45:56.756084780Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-15T14:45:56.756088369Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-15T14:45:56.756092175Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-15T14:45:56.756095873Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-15T14:45:56.756099507Z 	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
2021-12-15T14:45:56.756103049Z 	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
```

</details>

### Steps to Reproduce

1. Disbale `EDIT_INFRASTRUCTURE_DATA` in `featureconfiguration`.
1. Set `central.location.sync=true` property.

### Expected Behavior
Both properties can be set and synchronization works.

**Comment by mario-kuehne** [comment]
Successfully tested locally with git commit hash df83656b45be59913465b7429b6d187453da1576 (Version: 1.68.0-SNAPSHOT)

Set EDIT_INFRASTRUCTURE_DATA=false in featureconfiguration database table of Sormas Instance A
Set EDIT_INFRASTRUCTURE_DATA=false in featureconfiguration database table of Sormas Instance B
Set central.location.sync=true property in sormas.properties file of  Sormas Instance A
Set central.location.sync=true property in sormas.properties file of  Sormas Instance B
Build and Start both instances with above mentioned configurations

Expected:
No error shown 'Could not sync with central' in application log files of both instances
database table 'systemevent' has current entry for type 'CENTRAL_SYNC_INFRA' and status 'SUCCESS' in both instances

Actual: 
No error shown 'Could not sync with central' in application log files of both instances
database table 'systemevent' has current entry for type 'CENTRAL_SYNC_INFRA' and status 'SUCCESS' in both instances
