### ISSUE TITLE
Move functional information from toString to getCaption methods [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8314]
### Feature Description

Many `toString` methods contain functional information, e.g. first and last name, disease, classification, etc.

### Problem Description

`toString` methods can be (automatically) used in places where we don't want them to be used. Because of that, it would be better to split the functional information and move them to a different method.

### Proposed Change

- Add `getCaption` methods to all DTOs and entities that have custom `toString` methods (probably makes sense to add them to the superclasses if possible, e.g. EntityDto and AbstractDomainObject, and override them in child classes; default implementation should simply call the `toString` method)
- Fill the `getCaption` methods of all affected classes with the content of the respective `toString` method (if implemented; otherwise no need to override it)
- Replace all custom `toString` methods: Return a string containing the entity type + UUID in parentheses (e.g. "Case (XXXXX-XXXXX-XXXXXX-XXXXX)
- Replace all usages of the `toString` method in the UI with the new `getCaption` method, and also all implicit `toString` usages (e.g. in string format methods)

**Comment by StefanKock** [comment]
We found that `PerformanceLoggingInterceptor` on `TRACE` can run into exception when trying toString() on some DTOs. So this ticket will also mitigate that problem. Related Stacktrace:
```
[2022-06-21T12:00:52.566+0200] [Payara 5.2021.10] [SEVERE] [] [] [tid: _ThreadID=76 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1655805652566] [levelValue: 1000] [[
  java.lang.NullPointerException
        at de.symeda.sormas.api.contact.ContactReferenceDto$PersonName.access$000(ContactReferenceDto.java:133)
        at de.symeda.sormas.api.contact.ContactReferenceDto.getCaption(ContactReferenceDto.java:68)
        at de.symeda.sormas.api.ReferenceDto.toString(ReferenceDto.java:72)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
        at org.slf4j.helpers.MessageFormatter.objectArrayAppend(MessageFormatter.java:292)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:270)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
        at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
        at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
        at ch.qos.logback.classic.Logger.trace(Logger.java:433)
        at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:42)
        at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
...
```

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because I downloaded an User Roles Export and I noticed that the names of the User Roles have been replaced withUserRoleDto and the uuid. 

![image](https://user-images.githubusercontent.com/89522688/177286861-c7188727-2c85-428c-aa0b-de3e937b4039.png)

**Comment by StefanKock** [comment]
> I'm reopening the ticket because I downloaded an User Roles Export and I noticed that the names of the User Roles have been replaced withUserRoleDto and the uuid.

Is now fixed.

**Comment by StefanKock** [comment]
Additional finding: `ReferenceDto.toString()` still prints `getCaption`, that's why other columns in user directory still get formatted values.

**Comment by StefanKock** [comment]
> Reopening because the following captions aren't properly shown:
>     * Location in user directory (web)
>     * User role in mobile app in the side menu
@MateStrysewske will fix this and check if `LocationDto` used also somewhere else where a formatting needs to be defined.

> Additional finding: `ReferenceDto.toString()` still prints `getCaption`, that's why other columns in user directory still get formatted values.
I will create a follow-up ticket for this because it's too late in the sprint to change ReferenceDtos and take care of a lot of formatting at least in the vaadin-app: #9759

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(0a3c144).
