### ISSUE TITLE
Don't hide exception if error message formatting fails

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8548]
### Bug Description
Originally reported by @SahaLinaPrueger  to NL support: 

Testing of S2S on the release candidates `release-sormas-x.sormas.netzlink.com` and `release-de.sormas.netzlink.com`. Sharing a  case (`X7YD2V`) did not work as the target system (`release-de`) refused to accept the share.

Logs indicate that the share logic successfully caught  an exception, however, while rendering the user facing representation, an other exception occurred, interrupting the error handling and therefore hiding the root cause.

See the truncated log:

```
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
at java.base/java.util.Formatter.format(Formatter.java:2672)
at java.base/java.util.Formatter.format(Formatter.java:2609)
at java.base/java.lang.String.format(String.java:2897)
at de.symeda.sormas.api.i18n.I18nProperties.getValidationError(I18nProperties.java:275)
at de.symeda.sormas.api.sormastosormas.validation.ValidationErrorMessage.getHumanMessage(ValidationErrorMessage.java:69)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.lambda$formatSubGroupErrors$16(SormasToSormasController.java:255)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.formatSubGroupErrors(SormasToSormasController.java:262)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.lambda$buildShareErrorMessage$14(SormasToSormasController.java:228)
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.buildShareErrorMessage(SormasToSormasController.java:239)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.handleSormasToSormasRequest(SormasToSormasController.java:207)
at de.symeda.sormas.ui.sormastosormas.SormasToSormasController.acceptShareRequest(SormasToSormasController.java:141)
at de.symeda.sormas.ui.sormastosormas.ShareRequestGrid.lambda$createActionButtons$8e7d2d69$1(ShareRequestGrid.java:110)
at jdk.internal.reflect.GeneratedMethodAccessor2937.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
``` 
 

### Steps to Reproduce
TBD, I exported the case and somehow try to import it locally

### Expected Behavior
Error handling logic does not blow up itself

### System Details
* SORMAS version: 1.69.1

**Comment by JonasCir** [comment]
This one is very tricky to debug, as the error happens when accepting the case on the remote, after it has been successfully shared. That's quite odd.

**Comment by mario-kuehne** [comment]
Retested on local machine (branch: hotfix-1.70.1; commit hash [ab25a874](ab25a874ec27bf226f590ba25ce919bb6becbe7e))

- Manipulated manually from `sormasToSormasRegion = Unmatched region: %s`  to `sormasToSormasRegion = Unmatched region: %s %s` in validations.properties
- User Settings -> Language: English
- Created Region `RegionA` in instance A
- Created District `DistrictA` that belongs to `RegionA` in instance A
- Created Case C with Responsible Region `RegionA` & Responsible District `DistrictA`
- Shared Case C from Instance A to Instance B

![error-sharing-case-8548](https://user-images.githubusercontent.com/95228108/160802147-078a741e-648d-481f-ba64-fed7bbf1f7fe.PNG)

<details>

```
[#|2022-03-30T11:30:07.119+0200|INFO|Payara 5.2021.10||_ThreadID=85;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1648632607119;_LevelValue=800;|
2022-03-30T09:30:07.119660200Z   11:30:07.119 [http-thread-pool::http-listener-1(2)] ERROR de.symeda.sormas.api.sormastosormas.validation.ValidationErrorMessage - Formatting the human readable message failed. I18nTag: sormasToSormasRegion, arguments: [RegionA]
2022-03-30T09:30:07.119664200Z |#] 
```
</details>
