### ISSUE TITLE
Permission refactoring broke S2S

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8586]
### Bug Description
It appears that S2S is not working anymore due to the refactor of user roles and rights. I can confirm that 1.70 is affected by this.

Sharing a case triggers a bunch of exceptions on the receiving instance.

Most important part seems to be 
```
JACC Policy Provider: Failed Permission Check, context(sormas-ear/sormas-backend_jar)- permission(("javax.security.jacc.EJBMethodPermission" "CaseFacadeEjbLocal" "toDto,Local,de.symeda.sormas.backend.caze.Case"))|#]
 

A system exception occurred during an invocation on EJB CaseFacadeEjbLocal,
method: public de.symeda.sormas.api.caze.CaseDataDto
de.symeda.sormas.backend.caze.CaseFacadeEjb.toDto(de.symeda.sormas.backend.caze.Case)|#]
 

   javax.ejb.AccessLocalException: Client not authorized for this invocation
```

Please note that due to a case not beeing accepted on one of the test instances I was able to verify that  accepting a share is also broken. To properly fix this the accept/reject feature must be working as well.

### Steps to Reproduce
Spin up an S2S environment and share a case

### Expected Behavior
Case can be shared on no error is thrown, both for normal S2S and accept/reject feature.

### Additional Information

<details>
  <summary>See full stack trace (quite messy)</summary>

 
   JACC Policy Provider: Failed Permission Check, context(sormas-ear/sormas-backend_jar)- permission(("javax.security.jacc.EJBMethodPermission" "CaseFacadeEjbLocal" "toDto,Local,de.symeda.sormas.backend.caze.Case"))|#]
 

   A system exception occurred during an invocation on EJB CaseFacadeEjbLocal, method: public de.symeda.sormas.api.caze.CaseDataDto de.symeda.sormas.backend.caze.CaseFacadeEjb.toDto(de.symeda.sormas.backend.caze.Case)|#]
 

   javax.ejb.AccessLocalException: Client not authorized for this invocation
 	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2013)
 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
 	at com.sun.proxy.$Proxy664.toDto(Unknown Source)
 	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:63)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:40)
 	at de.symeda.sormas.backend.sormastosormas.data.received.ReceivedDataProcessor.processReceivedData(ReceivedDataProcessor.java:64)
 	at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:34)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.__EJB31_Generated__ReceivedCaseProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.lambda$processReceivedData$0(ReceivedEntitiesProcessor.java:84)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(ReceivedEntitiesProcessor.java:83)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at com.sun.proxy.$Proxy639.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.__EJB31_Generated__ReceivedEntitiesProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.perisist(AbstractSormasToSormasInterface.java:410)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.decryptAndPersist(AbstractSormasToSormasInterface.java:405)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.saveSharedEntities(AbstractSormasToSormasInterface.java:335)
 	at de.symeda.sormas.api.sormastosormas.caze.__SormasToSormasCaseFacade_Remote_DynamicStub.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/__SormasToSormasCaseFacade_Remote_DynamicStub.java)
 	at de.symeda.sormas.api.sormastosormas.caze._SormasToSormasCaseFacade_Wrapper.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/_SormasToSormasCaseFacade_Wrapper.java)
 	at de.symeda.sormas.rest.SormasToSormasResource.lambda$saveSharedCase$2(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource.handleVoidRequest(SormasToSormasResource.java:186)
 	at de.symeda.sormas.rest.SormasToSormasResource.saveSharedCase(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase$$super(Unknown Source)
 

   17:32:55.524 [http-thread-pool::http-listener-1(2)] DEBUG de.symeda.sormas.backend.util.PerformanceLoggingInterceptor - Finished in 22 ms: ReceivedCaseProcessor.processReceivedData

   A system exception occurred during an invocation on EJB ReceivedCaseProcessor, method: public de.symeda.sormas.api.sormastosormas.validation.ValidationErrors de.symeda.sormas.backend.sormastosormas.data.received.ReceivedDataProcessor.processReceivedData(de.symeda.sormas.api.sormastosormas.SormasToSormasEntityDto,de.symeda.sormas.backend.sormastosormas.entities.SormasToSormasShareable)|#]
 
   javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
e.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
 	at com.sun.proxy.$Proxy615.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.__EJB31_Generated__ReceivedCaseProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.lambda$processReceivedData$0(ReceivedEntitiesProcessor.java:84)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(ReceivedEntitiesProcessor.java:83)
 	at de.symeda.sormas.backend.sormastosormas.entities.__EJB31_Generated__ReceivedEntitiesProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.perisist(AbstractSormasToSormasInterface.java:410)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.decryptAndPersist(AbstractSormasToSormasInterface.java:405)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.saveSharedEntities(AbstractSormasToSormasInterface.java:335)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at de.symeda.sormas.api.sormastosormas.caze.__SormasToSormasCaseFacade_Remote_DynamicStub.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/__SormasToSormasCaseFacade_Remote_DynamicStub.java)
 	at de.symeda.sormas.api.sormastosormas.caze._SormasToSormasCaseFacade_Wrapper.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/_SormasToSormasCaseFacade_Wrapper.java)
 	at de.symeda.sormas.rest.SormasToSormasResource.lambda$saveSharedCase$2(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource.handleVoidRequest(SormasToSormasResource.java:186)
 	at de.symeda.sormas.rest.SormasToSormasResource.saveSharedCase(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase$$super(Unknown Source)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:63)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:40)
 	at de.symeda.sormas.backend.sormastosormas.data.received.ReceivedDataProcessor.processReceivedData(ReceivedDataProcessor.java:64)
 Caused by: javax.ejb.AccessLocalException: Client not authorized for this invocation
 	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2013)
 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
 	... 306 more

 

   17:32:55.526 [http-thread-pool::http-listener-1(2)] DEBUG de.symeda.sormas.backend.util.PerformanceLoggingInterceptor - Finished in 36 ms: ReceivedEntitiesProcessor.processReceivedData

   A system exception occurred during an invocation on EJB ReceivedEntitiesProcessor, method: public java.util.List de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(de.symeda.sormas.api.sormastosormas.SormasToSormasDto,de.symeda.sormas.backend.sormastosormas.entities.ShareDataExistingEntities)|#]
 
   javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.__EJB31_Generated__ReceivedEntitiesProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.perisist(AbstractSormasToSormasInterface.java:410)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.decryptAndPersist(AbstractSormasToSormasInterface.java:405)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.saveSharedEntities(AbstractSormasToSormasInterface.java:335)
 	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
 	at de.symeda.sormas.api.sormastosormas.caze.__SormasToSormasCaseFacade_Remote_DynamicStub.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/__SormasToSormasCaseFacade_Remote_DynamicStub.java)
 	at de.symeda.sormas.api.sormastosormas.caze._SormasToSormasCaseFacade_Wrapper.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/_SormasToSormasCaseFacade_Wrapper.java)
 	at de.symeda.sormas.rest.SormasToSormasResource.lambda$saveSharedCase$2(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource.handleVoidRequest(SormasToSormasResource.java:186)
 	at de.symeda.sormas.rest.SormasToSormasResource.saveSharedCase(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase$$super(Unknown Source)
 Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.__EJB31_Generated__ReceivedCaseProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.lambda$processReceivedData$0(ReceivedEntitiesProcessor.java:84)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(ReceivedEntitiesProcessor.java:83)
 Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
 	... 252 more
 Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:63)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:40)
 	at de.symeda.sormas.backend.sormastosormas.data.received.ReceivedDataProcessor.processReceivedData(ReceivedDataProcessor.java:64)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 
 [#|2022-03-28T17:32:55.528+0200|INFO|Payara 5.2021.10||_ThreadID=139;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1648481575528;_LevelValue=800;|
   17:32:55.528 [http-thread-pool::http-listener-1(2)] DEBUG de.symeda.sormas.backend.util.PerformanceLoggingInterceptor - Finished in 1522 ms: SormasToSormasCaseFacadeEjb.saveSharedEntities
 |#]
 
 [#|2022-03-28T17:32:55.528+0200|WARNING|Payara 5.2021.10|javax.enterprise.ejb.container|_ThreadID=139;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1648481575528;_LevelValue=900;_MessageID=AS-EJB-00056;|
   A system exception occurred during an invocation on EJB SormasToSormasCaseFacade, method: public void de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.saveSharedEntities(de.symeda.sormas.api.sormastosormas.SormasToSormasEncryptedDataDto) throws de.symeda.sormas.api.sormastosormas.SormasToSormasException,de.symeda.sormas.api.sormastosormas.validation.SormasToSormasValidationException|#]
 
 [#|2022-03-28T17:32:55.528+0200|WARNING|Payara 5.2021.10|javax.enterprise.ejb.container|_ThreadID=139;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1648481575528;_LevelValue=900;|
   javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.proxy.$Proxy402.saveSharedEntities(Unknown Source)
 	at de.symeda.sormas.api.sormastosormas.caze.__SormasToSormasCaseFacade_Remote_DynamicStub.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/__SormasToSormasCaseFacade_Remote_DynamicStub.java)
 	at de.symeda.sormas.api.sormastosormas.caze._SormasToSormasCaseFacade_Wrapper.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/_SormasToSormasCaseFacade_Wrapper.java)
 	at de.symeda.sormas.rest.SormasToSormasResource.lambda$saveSharedCase$2(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource.handleVoidRequest(SormasToSormasResource.java:186)
 	at de.symeda.sormas.rest.SormasToSormasResource.saveSharedCase(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase$$super(Unknown Source)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase(Unknown Source)
 	
 Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.__EJB31_Generated__ReceivedEntitiesProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.perisist(AbstractSormasToSormasInterface.java:410)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.decryptAndPersist(AbstractSormasToSormasInterface.java:405)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.__EJB31_Generated__ReceivedCaseProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.lambda$processReceivedData$0(ReceivedEntitiesProcessor.java:84)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(ReceivedEntitiesProcessor.java:83)
 	
 Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
 	... 252 more
 Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.proxy.$Proxy664.toDto(Unknown Source)
 	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:63)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:40)
 	at de.symeda.sormas.backend.sormastosormas.data.received.ReceivedDataProcessor.processReceivedData(ReceivedDataProcessor.java:64)
 	
 Caused by: javax.ejb.AccessLocalException: Client not authorized for this invocation
 	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2013)
 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
 	... 306 more
 |#]
 
 [#|2022-03-28T17:32:55.556+0200|WARNING|Payara 5.2021.10|javax.enterprise.web|_ThreadID=139;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1648481575556;_LevelValue=900;|
   StandardWrapperValve[de.symeda.sormas.rest.RestConfig]: Servlet.service() for servlet de.symeda.sormas.rest.RestConfig threw exception
 org.omg.CORBA.TRANSACTION_ROLLEDBACK: ----------BEGIN server-side stack trace----------
 org.omg.CORBA.TRANSACTION_ROLLEDBACK:   vmcid: 0x2000  minor code: 1806 completed: Maybe
 	at org.glassfish.enterprise.iiop.impl.POAProtocolMgr.mapException(POAProtocolMgr.java:356)
 	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2357)
 	at com.sun.ejb.containers.BaseContainer.mapRemoteException(BaseContainer.java:2330)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2173)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
 	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:212)
 	at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
 	at com.sun.proxy.$Proxy402.saveSharedEntities(Unknown Source)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at de.symeda.sormas.rest.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
 Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
 	... 140 more
 Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.__EJB31_Generated__ReceivedEntitiesProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.perisist(AbstractSormasToSormasInterface.java:410)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.decryptAndPersist(AbstractSormasToSormasInterface.java:405)
 	at de.symeda.sormas.backend.sormastosormas.AbstractSormasToSormasInterface.saveSharedEntities(AbstractSormasToSormasInterface.java:335)
 	at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:34)
 	
 Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
 	... 196 more
 Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.__EJB31_Generated__ReceivedCaseProcessor__Intf____Bean__.processReceivedData(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.lambda$processReceivedData$0(ReceivedEntitiesProcessor.java:84)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 	at de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor.processReceivedData(ReceivedEntitiesProcessor.java:83)
 	... 194 more
 Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
 	... 252 more
 Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
 	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:63)
 	at de.symeda.sormas.backend.sormastosormas.entities.caze.ReceivedCaseProcessor.handleReceivedData(ReceivedCaseProcessor.java:40)
 Caused by: javax.ejb.AccessLocalException: Client not authorized for this invocation
 	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2013)
 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
 	... 306 more
 
 ----------END server-side stack trace----------  vmcid: 0x2000  minor code: 1806 completed: Maybe
 	at de.symeda.sormas.api.sormastosormas.caze.__SormasToSormasCaseFacade_Remote_DynamicStub.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/__SormasToSormasCaseFacade_Remote_DynamicStub.java)
 	at de.symeda.sormas.api.sormastosormas.caze._SormasToSormasCaseFacade_Wrapper.saveSharedEntities(de/symeda/sormas/api/sormastosormas/caze/_SormasToSormasCaseFacade_Wrapper.java)
 	at de.symeda.sormas.rest.SormasToSormasResource.lambda$saveSharedCase$2(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource.handleVoidRequest(SormasToSormasResource.java:186)
 	at de.symeda.sormas.rest.SormasToSormasResource.saveSharedCase(SormasToSormasResource.java:71)
 	at de.symeda.sormas.rest.SormasToSormasResource$Proxy$_$$_WeldSubclass.saveSharedCase$$super(Unknown Source)

</details>

**Comment by JonasCir** [comment]
@MateStrysewske @vidi42 It looks like that #8585 somehow caused this. I rebased on latest hotfix where the changes are included an everything seems at least with regard to this ticket seems to work.
