### ISSUE TITLE
Error when navigating to hospitalization view

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#884]
> 2018-11-14 22:48:46,115 ERROR   d.s.sormas.ui.SormasErrorHandler - Invocation of method
> uriFragmentChanged in com.vaadin.navigator.Navigator$UriFragmentManager failed.
> com.vaadin.event.ListenerMethod$MethodException: Invocation of method uriFragmentChanged
> in com.vaadin.navigator.Navigator$UriFragmentManager failed.
> at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:533)
> at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
> at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
> at com.vaadin.server.Page.fireEvent(Page.java:603)
> at com.vaadin.server.Page.updateLocation(Page.java:983)
> at com.vaadin.ui.UI.changeVariables(UI.java:400)
> at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:616)
> at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:463)
> at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:406)
> at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
> at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
> at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
> at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
> at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1606)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:338)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:20)
> at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
> at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
> at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
> at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
> at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
> at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
> at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
> at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
> at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4734)
> at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4722)
> at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
> at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
> at com.sun.proxy.$Proxy414.doFilter(Unknown Source)
> at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown
> Source)
> at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:43)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:250)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
> at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
> at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
> at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
> at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
> at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
> at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
> at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
> at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
> at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
> at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
> at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
> at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
> at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
> at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
> at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: null
> at de.symeda.sormas.ui.hospitalization.CaseHospitalizationForm.addFields(CaseHospitalizationForm.java:55)
> at de.symeda.sormas.ui.hospitalization.CaseHospitalizationForm.<init>(CaseHospitalizationForm.java:45)
> at de.symeda.sormas.ui.caze.CaseController.getCaseHospitalizationComponent(CaseController.java:403)
> at de.symeda.sormas.ui.hospitalization.CaseHospitalizationView.enter(CaseHospitalizationView.java:27)
> at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:625)
> at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:584)
> at com.vaadin.navigator.Navigator$UriFragmentManager.uriFragmentChanged(Navigator.java:146)
> at sun.reflect.GeneratedMethodAccessor1568.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
> ... 79 common frames omitted

**Comment by MartinWahnschaffeSymeda** [comment]
Goes down to #863 
I have fixed the related case RWDALT-JPPE2N-JJDG65-DLLG2ODQ and assigned it to "other health facility"
