### ISSUE TITLE
Can't open campaign in the mobile app

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#9076]
### Steps to Reproduce

1. Login in the mobile app with SurvOff
2. Navigate to Campaigns
3. Try to open a campaign
=> The app crashes and an exception appears in the logs

### Expected Behavior

Campaign data should be show in the app
### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.symeda.sormas.app.debug, PID: 14731
    java.lang.ExceptionInInitializerError
        at org.springframework.core.SpringProperties.getProperty(SpringProperties.java:102)
        at org.springframework.expression.spel.SpelParserConfiguration.<clinit>(SpelParserConfiguration.java:35)
        at org.springframework.expression.spel.standard.SpelExpressionParser.<init>(SpelExpressionParser.java:41)
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadFragment.<init>(CampaignFormDataReadFragment.java:59)
        at java.lang.Class.newInstance(Native Method)
        at de.symeda.sormas.app.BaseFragment.newInstance(BaseFragment.java:51)
        at de.symeda.sormas.app.BaseReadFragment.newInstance(BaseReadFragment.java:60)
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadFragment.newInstance(CampaignFormDataReadFragment.java:63)
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadActivity.buildReadFragment(CampaignFormDataReadActivity.java:50)
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadActivity.buildReadFragment(CampaignFormDataReadActivity.java:32)
        at de.symeda.sormas.app.BaseReadActivity$1.accept(BaseReadActivity.java:113)
        at de.symeda.sormas.app.BaseReadActivity$1.accept(BaseReadActivity.java:109)
        at de.symeda.sormas.app.BaseReadActivity.requestRootData(BaseReadActivity.java:96)
        at de.symeda.sormas.app.BaseReadActivity.onResumeFragments(BaseReadActivity.java:109)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:8154)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/lib/x86, /system/lib, /system_ext/lib]] (Caused by java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/lib/x86, /system/lib, /system_ext/lib]])
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
        at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
        at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at org.springframework.core.SpringProperties.<clinit>(SpringProperties.java:51)
        at org.springframework.core.SpringProperties.getProperty(SpringProperties.java:102) 
        at org.springframework.expression.spel.SpelParserConfiguration.<clinit>(SpelParserConfiguration.java:35) 
        at org.springframework.expression.spel.standard.SpelExpressionParser.<init>(SpelExpressionParser.java:41) 
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadFragment.<init>(CampaignFormDataReadFragment.java:59) 
        at java.lang.Class.newInstance(Native Method) 
        at de.symeda.sormas.app.BaseFragment.newInstance(BaseFragment.java:51) 
        at de.symeda.sormas.app.BaseReadFragment.newInstance(BaseReadFragment.java:60) 
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadFragment.newInstance(CampaignFormDataReadFragment.java:63) 
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadActivity.buildReadFragment(CampaignFormDataReadActivity.java:50) 
        at de.symeda.sormas.app.campaign.read.CampaignFormDataReadActivity.buildReadFragment(CampaignFormDataReadActivity.java:32) 
        at de.symeda.sormas.app.BaseReadActivity$1.accept(BaseReadActivity.java:113) 
        at de.symeda.sormas.app.BaseReadActivity$1.accept(BaseReadActivity.java:109) 
        at de.symeda.sormas.app.BaseReadActivity.requestRootData(BaseReadActivity.java:96) 
        at de.symeda.sormas.app.BaseReadActivity.onResumeFragments(BaseReadActivity.java:109) 
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447) 
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240) 
        at android.app.Activity.performResume(Activity.java:8154) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~n4eUag2y36K5s1FwuJ9VRg==/de.symeda.sormas.app.debug-KaACBNdon1GjLq1cPR_18Q==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
        	... 35 more
V/FA: Connection attempt already in progress
V/FA: Recording user engagement, ms: 895
D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=281818091 in 1000ms(Backend next call timestamp 1651670150693). Attempt 1
I/Process: Sending signal. PID: 14731 SIG: 9
Disconnected from the target VM, address: 'localhost:51919', transport: 'socket'
```

**Comment by MartinWahnschaffe** [comment]
Seems to be related to a missing dependency needed to use the spring expression framework for campaigns.
My guess is that it's like that for a longer time already and is not needed for the in production systems. I'm not a big fan of this, but it shouldn't block the current release.

When this is fixed do the following:

- [ ] Check whether the change done to the campaigns sync logic done in #8989 is working - so whether pushing campaign data from mobile app to server is working.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine - a Surveillance Officer can open the 'Campaigns' directory and the existing campaigns on the mobile app.

Verified ticket using:
Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
SORMAS version: 1.73.0-SNAPSHOT(2b82a3d) 
Android version/Browser: Chrome (vaadin-app); Android 11 (android-app)
Server URL: local machine
User Role: Surveillance Officer
