### ISSUE TITLE
Lab Officer cannot create Cases for Event Participants

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9097]
### Bug Description
Lab Officer is unable to create Cases for Event Participants because the system crashes when he tries to perform the action.

### Steps to Reproduce

1. Log in with an Admin,NatUser;
2. Create an Event and an Event Participant;
3. Add a Sample (pending) for the Event Participant and select the Laboratory that the Lab Officer user is associated to;
4. Log in with the Lab Officer user;
5. Navigate to the Events Directory, open an Event and select the Event Participants tab;
6. Click on the 'Create' button under the Case ID;
7. Fill in the mandatory data from the 'Create new Case' form and Save;

### Actual Behavior
An error message is displayed and the Case is not created;

### Expected Behavior
The Case should get created successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/167099077-7e8877fb-4778-4c16-90f6-34d98f1a1832.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (04faaf1)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Lab Officer

### Additional Information
- This issue was discovered when testing ticket #8820.
- Stacktrace for this issue:
[stacktrace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8638761/stacktrace.txt)
```
2022-05-04T14:40:32.377964200Z 	at de.symeda.sormas.api.event.__EventParticipantFacade_Remote_DynamicStub.getMatchingEventParticipants(de/symeda/sormas/api/event/__EventParticipantFacade_Remote_DynamicStub.java)
2022-05-04T14:40:32.377989800Z 	at de.symeda.sormas.api.event._EventParticipantFacade_Wrapper.getMatchingEventParticipants(de/symeda/sormas/api/event/_EventParticipantFacade_Wrapper.java)
2022-05-04T14:40:32.377999200Z 	at de.symeda.sormas.ui.caze.CaseController.convertSamePersonContactsAndEventparticipants(CaseController.java:312)
2022-05-04T14:40:32.378004400Z 	at de.symeda.sormas.ui.caze.CaseController.lambda$createFromEventParticipant$0(CaseController.java:204)
2022-05-04T14:40:32.378009200Z 	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:672)
2022-05-04T14:40:32.378013600Z 	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.doCommit(CommitDiscardWrapperComponent.java:515)
2022-05-04T14:40:32.378018500Z 	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:450)
2022-05-04T14:40:32.378024100Z 	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:546)
2022-05-04T14:40:32.378029700Z 	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:371)
...
2022-05-04T14:40:32.378943600Z Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
...
2022-05-04T14:40:32.379105800Z Caused by: org.postgresql.util.PSQLException: ERROR: column "eventparti0_.reportinguser_id" must appear in the GROUP BY clause or be used in an aggregate function
2022-05-04T14:40:32.379110500Z   Position: 293
2022-05-04T14:40:32.379114500Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
2022-05-04T14:40:32.379118900Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
2022-05-04T14:40:32.379123300Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
2022-05-04T14:40:32.379127500Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
2022-05-04T14:40:32.379131600Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
2022-05-04T14:40:32.379135600Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
2022-05-04T14:40:32.379140200Z 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
2022-05-04T14:40:32.379144500Z 	at jdk.internal.reflect.GeneratedMethodAccessor283.invoke(Unknown Source)
2022-05-04T14:40:32.379148900Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-04T14:40:32.379153400Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-05-04T14:40:32.379157500Z 	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
2022-05-04T14:40:32.379161800Z 	at com.sun.proxy.$Proxy744.executeQuery(Unknown Source)
2022-05-04T14:40:32.379165900Z 	at com.sun.gjc.spi.jdbc40.PreparedStatementWrapper40.executeQuery(PreparedStatementWrapper40.java:658)
2022-05-04T14:40:32.379170100Z 	at jdk.internal.reflect.GeneratedMethodAccessor283.invoke(Unknown Source)
2022-05-04T14:40:32.379186000Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-04T14:40:32.379193600Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-05-04T14:40:32.379198100Z 	at com.sun.gjc.spi.jdbc40.ProfiledConnectionWrapper40$1.invoke(ProfiledConnectionWrapper40.java:457)
2022-05-04T14:40:32.379202600Z 	at com.sun.proxy.$Proxy745.executeQuery(Unknown Source)
2022-05-04T14:40:32.379207000Z 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
2022-05-04T14:40:32.379211300Z 	... 184 more
```

**Comment by StefanKock** [comment]
This problem seems to exists since at least 1.70 or longer. A small unit test is able to produce the associated query that fails on deployed SORMAS, but not in unit test with h2database. 
I think the `jurisdictionSelector` in select and group by does not work with the sample subquery in PostgreSQL. Maybe it can be avoided with `distinct` instead of `group by`.

<details>
<summary>unit test, generated SQL query</summary>

```java
// EventParticipantFacadeEjbTest

	@Test
	public void testGetMatchingEventParticipants() {

		RDCF rdcf = creator.createRDCF();
		UserDto user = creator.createUser(rdcf, UserRole.LAB_USER);
		user.setLaboratory(rdcf.facility);
		getUserFacade().saveUser(user);
		loginWith(user);

		EventParticipantCriteria criteria = new EventParticipantCriteria();
		List<SimilarEventParticipantDto> result = getEventParticipantFacade().getMatchingEventParticipants(criteria);
		assertThat(result, hasSize(0));
	}
```

```sql

SELECT DISTINCT eventparti0_.uuid AS col_0_0_,
                person1_.firstName AS col_1_0_,
                person1_.lastName AS col_2_0_,
                eventparti0_.involvementDescription AS col_3_0_,
                event2_.uuid AS col_4_0_,
                event2_.eventStatus AS col_5_0_,
                event2_.eventTitle AS col_6_0_,
                event2_.startDate AS col_7_0_,
                CASE
                    WHEN (eventparti0_.reportingUser_id IS NOT NULL)
                         AND eventparti0_.reportingUser_id=64
                         OR EXISTS
                           (SELECT sample7_.id
                            FROM samples sample7_
                            LEFT OUTER JOIN EventParticipant eventparti8_ ON sample7_.associatedEventParticipant_id=eventparti8_.id
                            LEFT OUTER JOIN users user9_ ON sample7_.reportingUser_id=user9_.id
                            LEFT OUTER JOIN Facility facility10_ ON sample7_.lab_id=facility10_.id
                            WHERE eventparti8_.id=eventparti0_.id
                              AND ((user9_.id IS NOT NULL)
                                   AND user9_.id=64
                                   OR facility10_.id=62)) THEN TRUE
                    ELSE FALSE
                END AS col_8_0_
FROM EventParticipant eventparti0_
LEFT OUTER JOIN Person person1_ ON eventparti0_.person_id=person1_.id
LEFT OUTER JOIN EVENTS event2_ ON eventparti0_.event_id=event2_.id
LEFT OUTER JOIN EVENTS event3_ ON eventparti0_.event_id=event3_.id
LEFT OUTER JOIN LOCATION location4_ ON event3_.eventLocation_id=location4_.id
LEFT OUTER JOIN cases case5_ ON eventparti0_.resultingCase_id=case5_.id
LEFT OUTER JOIN contact contacts6_ ON case5_.id=contacts6_.caze_id
WHERE eventparti0_.deleted=FALSE
  AND (EXISTS
         (SELECT sample11_.id
          FROM samples sample11_
          LEFT OUTER JOIN EventParticipant eventparti12_ ON sample11_.associatedEventParticipant_id=eventparti12_.id
          LEFT OUTER JOIN users user13_ ON sample11_.reportingUser_id=user13_.id
          LEFT OUTER JOIN Facility facility14_ ON sample11_.lab_id=facility14_.id
          WHERE eventparti12_.id=eventparti0_.id
            AND ((user13_.id IS NOT NULL)
                 AND user13_.id=64
                 OR facility14_.id=62) )
       OR EXISTS
         (SELECT sample15_.id
          FROM samples sample15_
          LEFT OUTER JOIN cases case16_ ON sample15_.associatedCase_id=case16_.id
          LEFT OUTER JOIN Facility facility17_ ON sample15_.lab_id=facility17_.id
          WHERE case16_.id=case5_.id
            AND facility17_.id=? )
       OR contacts6_.reportingUser_id=?
       OR contacts6_.contactOfficer_id=?
       OR EXISTS
         (SELECT sample18_.id
          FROM samples sample18_
          LEFT OUTER JOIN contact contact19_ ON sample18_.associatedContact_id=contact19_.id
          LEFT OUTER JOIN Facility facility20_ ON sample18_.lab_id=facility20_.id
          WHERE contact19_.id=contacts6_.id
            AND facility20_.id=? )
       OR case5_.sharedToCountry=TRUE
       OR case5_.reportingUser_id=64
       OR case5_.surveillanceOfficer_id=64
       OR case5_.caseOfficer_id=64
       OR location4_.region_id=?
       OR event3_.reportingUser_id=?
       OR event3_.responsibleUser_id=?)
GROUP BY eventparti0_.uuid,
         person1_.firstName,
         person1_.lastName,
         eventparti0_.involvementDescription,
         event2_.uuid,
         event2_.eventStatus,
         event2_.eventTitle,
         event2_.startDate,
         CASE
             WHEN (eventparti0_.reportingUser_id IS NOT NULL)
                  AND eventparti0_.reportingUser_id=64
                  OR EXISTS
                    (SELECT sample21_.id
                     FROM samples sample21_
                     LEFT OUTER JOIN EventParticipant eventparti22_ ON sample21_.associatedEventParticipant_id=eventparti22_.id
                     LEFT OUTER JOIN users user23_ ON sample21_.reportingUser_id=user23_.id
                     LEFT OUTER JOIN Facility facility24_ ON sample21_.lab_id=facility24_.id
                     WHERE eventparti22_.id=eventparti0_.id
                       AND ((user23_.id IS NOT NULL)
                            AND user23_.id=64
                            OR facility24_.id=62)) THEN TRUE
             ELSE FALSE
         END
```

</details>

**Comment by FredrikSchaeferVitagroup** [comment]
Changes for this ticket imported an errorneous test into development, that's why I am reopening it.

**Comment by StefanKock** [comment]
I still think the `group by` is superfluous and should be removed. 'll provide a PR.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.73.0-SNAPSHOT (a69d3d0)
