### ISSUE TITLE
Server failed to start with version > 1.70.0

### ISSUE THREAD

**Issue by GRADeS-Gwen** [hzi-braunschweig/SORMAS-Project#9330]
### Bug Description
I tried to upgrade our sormas version from 1.67.1 to 1.70.3, but the server failed to start after upgrade. I did every version upgrade to see witch one not working and up to 1.70.0 it worked fine. But when I tried to upgrade to 1.70.1, the server failed to start. I also tried to upgrade to 1.70.2 and 1.70.3, but as soon as I trid to get a version greater than 1.70.0, it is impossible to starte th server.
No spectific data in the log file, but the error is visible in the "journalctl" : 
```
mai 25 14:15:23 salk payara-sormas[30713]: Waiting for sormas to start ..Error starting domain sormas.
mai 25 14:15:23 salk payara-sormas[30713]: The server exited prematurely with exit code 1.
mai 25 14:15:23 salk payara-sormas[30713]: Before it died, it produced the following output:
mai 25 14:15:23 salk payara-sormas[30713]: Launching Payara Server on Felix platform
mai 25 14:15:23 salk payara-sormas[30713]: Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@6cb20a2e in service registry.
mai 25 14:15:23 salk payara-sormas[30713]: Completed shutdown of GlassFish runtime
mai 25 14:15:23 salk payara-sormas[30713]: We are in non-embedded mode, so fish.payara.server.internal.core.glassfish [324] has nothing to do.
mai 25 14:15:23 salk payara-sormas[30713]: WARNING: An illegal reflective access operation has occurred
mai 25 14:15:23 salk payara-sormas[30713]: WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/opt/payara5/glassfish/osgi/felix/bin/felix.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
mai 25 14:15:23 salk payara-sormas[30713]: WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
mai 25 14:15:23 salk payara-sormas[30713]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
mai 25 14:15:23 salk payara-sormas[30713]: WARNING: All illegal access operations will be denied in a future release
mai 25 14:15:23 salk payara-sormas[30713]: mai 25, 2022 2:15:22 PM com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
mai 25 14:15:23 salk payara-sormas[30713]: INFOS: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
mai 25 14:15:23 salk payara-sormas[30713]: Exception in thread "main" java.lang.reflect.InvocationTargetException
mai 25 14:15:23 salk payara-sormas[30713]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mai 25 14:15:23 salk payara-sormas[30713]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mai 25 14:15:23 salk payara-sormas[30713]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mai 25 14:15:23 salk payara-sormas[30713]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
mai 25 14:15:23 salk payara-sormas[30713]: Caused by: A MultiException has 2 exceptions.  They are:
mai 25 14:15:23 salk payara-sormas[30713]: 1. com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [77]], State = [NEW]
mai 25 14:15:23 salk payara-sormas[30713]: 2. java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
mai 25 14:15:23 salk payara-sormas[30713]:         implementation=org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector
mai 25 14:15:23 salk payara-sormas[30713]:         name=batch-runtime-configuration
mai 25 14:15:23 salk payara-sormas[30713]:         contracts={org.glassfish.batch.spi.impl.BatchRuntimeConfigurationInjector,org.jvnet.hk2.config.ConfigInjector}
mai 25 14:15:23 salk payara-sormas[30713]:         scope=javax.inject.Singleton
mai 25 14:15:23 salk payara-sormas[30713]:         qualifiers={org.jvnet.hk2.config.InjectionTarget}
mai 25 14:15:23 salk payara-sormas[30713]:         descriptorType=CLASS
mai 25 14:15:23 salk payara-sormas[30713]:         descriptorVisibility=NORMAL
mai 25 14:15:23 salk payara-sormas[30713]:         metadata=@table-suffix={optional,default\:,datatype\:java.lang.String,leaf},@data-source-lookup-name={optional,datatype\:java.lang.String,leaf},@table-prefix={optional,default\:,datatype\:java.lang.String,leaf},@schema-name={optional,default\
mai 25 14:15:23 salk payara-sormas[30713]:         rank=0
mai 25 14:15:23 salk payara-sormas[30713]:         loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [77]], State = [NEW],1885562991)
mai 25 14:15:23 salk payara-sormas[30713]:         proxiable=null
mai 25 14:15:23 salk payara-sormas[30713]:         proxyForSameScope=null
mai 25 14:15:23 salk payara-sormas[30713]:         analysisName=null
mai 25 14:15:23 salk payara-sormas[30713]:         id=172
mai 25 14:15:23 salk payara-sormas[30713]:         locatorId=0
mai 25 14:15:23 salk payara-sormas[30713]:         identityHashCode=204568533
mai 25 14:15:23 salk payara-sormas[30713]:         reified=false)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2246)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:437)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:456)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.DomDocument$InjectionTargetFilter.matches(DomDocument.java:184)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:346)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getDescriptors(ServiceLocatorImpl.java:388)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.getBestDescriptor(ServiceLocatorImpl.java:396)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:135)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigModel.parseValue(ConfigModel.java:959)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigModel.<init>(ConfigModel.java:875)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.DomDocument.buildModel(DomDocument.java:114)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.DomDocument.getModelByElementName(DomDocument.java:162)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigParser.handleElement(ConfigParser.java:165)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:101)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigParser.parse(ConfigParser.java:95)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.glassfish.config.support.DomainXml.parseDomainXml(DomainXml.java:271)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.glassfish.config.support.DomainXml.run(DomainXml.java:121)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.config.ConfigurationPopulator.populateConfig(ConfigurationPopulator.java:58)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.glassfish.hk2.bootstrap.HK2Populator.populateConfig(HK2Populator.java:83)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.populateConfig(AbstractModulesRegistryImpl.java:190)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.module.bootstrap.Main.createServiceLocator(Main.java:249)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.osgiadapter.HK2Main.createServiceLocator(HK2Main.java:95)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime.newGlassFish(EmbeddedOSGiGlassFishRuntime.java:95)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.GlassFishRuntimeDecorator.newGlassFish(GlassFishRuntimeDecorator.java:68)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntime.newGlassFish(OSGiGlassFishRuntime.java:91)
mai 25 14:15:23 salk payara-sormas[30713]:         at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:125)
mai 25 14:15:23 salk payara-sormas[30713]:         ... 6 more
mai 25 14:15:23 salk payara-sormas[30713]: Caused by: com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.server.internal.batch.glassfish-batch-connector [77]], State = [NEW]
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:193)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:54)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2238)
mai 25 14:15:23 salk payara-sormas[30713]:         ... 31 more
mai 25 14:15:23 salk payara-sormas[30713]: Caused by: org.osgi.framework.BundleException: Unable to resolve fish.payara.server.internal.batch.glassfish-batch-connector [77](R 77.0): missing requirement [fish.payara.server.internal.batch.glassfish-batch-connector [77](R 77.0)] osgi.wiring.pack
mai 25 14:15:23 salk payara-sormas[30713]:         at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.startBundle(OSGiModuleImpl.java:227)
mai 25 14:15:23 salk payara-sormas[30713]:         at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:185)
mai 25 14:15:23 salk payara-sormas[30713]:         ... 33 more
mai 25 14:15:23 salk payara-sormas[30713]: Command start-domain failed.
mai 25 14:15:23 salk su[30720]: pam_unix(su:session): session closed for user payara
mai 25 14:15:23 salk systemd[1]: payara-sormas.service: Control process exited, code=exited status=1
mai 25 14:15:23 salk systemd[1]: payara-sormas.service: Failed with result 'exit-code'.
mai 25 14:15:23 salk systemd[1]: Failed to start LSB: Payara-Server SORMAS.
```

### Steps to Reproduce
1. Download release > 1.70.0 (ex: 1.70.3)
2. Update with `server-update.sh`

### Expected Behavior
The server should start after upgrade

### System Details

* Device: Debian buster
* SORMAS version: 1.70.0
* Payara version: 5.2020.2
* OpenJDK version: 11

### Additional Information
I tried the upgrade on two similare installations, and got the same error.

**Comment by MateStrysewske** [comment]
Hey @GRADeS-Gwen. This looks like a payara-related issue to me, there's no reference to anything SORMAS-related in those logs, and I also don't think we've done any version upgrades in one of the 1.70 releases that could cause this. I'll link @StefanKock here, maybe he has an idea.

**Comment by StefanKock** [comment]
Looks like some OSGI caching is causing an issue. Stop the payara domain, remove `osgi-cache/felix` directory within the payara domain and start again.

With 1.70.1 we introduced the patching of a glassfish module (see #7705). Not sure if that ticket causes the problem.

**Comment by GRADeS-Gwen** [comment]
Nervermind, I missed it on the last update. I got the payara to "5.2021.10" and redeployed my domain successfully.
I finally pushed the version 1.70.3 and it worked !

It's my fault to haved missed the payara upgrade in the relase infos.

**Comment by StefanKock** [comment]
I'm glad we were able to help.
