### ISSUE TITLE
Backend validation prevents synchronization

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#963]
> ```
> Caused by: javax.validation.ValidationException: lastContactDate has to be before
> reportDateTime
> at de.symeda.sormas.backend.contact.ContactFacadeEjb.fromDto(ContactFacadeEjb.java:396)
> at de.symeda.sormas.backend.contact.ContactFacadeEjb.saveContact(ContactFacadeEjb.java:185)
> at sun.reflect.GeneratedMethodAccessor4279.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
> at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
> at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
> at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
> at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
> at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
> at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
> at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
> at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
> at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4734)
> at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4722)
> at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)
> ... 77 common frames omitted
> ```

**Comment by MartinWahnschaffeSymeda** [comment]
We decided to deactivate all validation in the backend where we would still be ok with saving the data. This is the case for all date validations.
