### ISSUE TITLE
Sormas-survnet-interface 13.0.0 does not start anymore

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#9756]
### Bug Description
It seems that the latest patch for Java (11.0.15) has some new validation rules for Xpath expression's size.

### Suggested change :
It should be sufficient for now to revert the docker image to java 11.0.14.

In the Dockerfile in the project "FROM openjdk:11-jre-slim" should be replaced with "FROM openjdk:11.0.14-jre-slim"
https://stackoverflow.com/questions/72401149/limit-set-by-feature-secure-processing 

### Expected Behavior
Survnet Converter should start as expected 

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
Stack trace received from Kay:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'survNetService' defined
 in URL [jar:file:/app.jar!/BOOT-INF/classes!/de/symeda/sormas/service/SurvNetService.class]: Unsatisfied dependency exp
ressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyExcep
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at de.symeda.sormas.Application.main(Application.java:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
ERROR:  'JAXP0801002: the compiler encountered an XPath expression containing '120' operators that exceeds the '100' limit set by 'FEATURE_SECURE_PROCESSING'.'
FATAL ERROR:  'JAXP0801003: the compiler encountered XPath expressions with an accumulated '17,513' operators that exceeds the '10,000' limit set by 'FEATURE_SECURE_PROCESSING'.'

**Comment by AndyBakcsy-she** [comment]
Discarding ticket as it was created under the wrong project
