### ISSUE TITLE
Downloading the Data Protection Dictionary results in an error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9879]
### Bug Description

#9600 fixed the download of the general data dictionary by fixing translations which were resulting in errors when generating the files. However, this does not seem to fix the failing download of the Data Protection Dictionary.
### Steps to Reproduce

1. Open the About page
2. Click on the Data Protection Dictionary

### Expected Behavior

The file can be successfully downloaded and opened.

### Screenshots

<img width="556" alt="dataProtectionDictionaryError" src="https://user-images.githubusercontent.com/70317594/179471997-e28a0fbe-ed06-479a-aa88-541131a9f985.PNG">

### System Details

* Device:
* SORMAS version: 1.74.0-SNAPSHOT (3087773)
* Android version/Browser: chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by StefanKock** [comment]
Reproduced with User admin, got this StackTrace in server.log (no logback entries):

<details>
<summary>FilterInputStream.close: NPE</summary>

```bash
[2022-07-19T08:32:45.757+0200] [Payara 5.2021.10] [WARNUNG] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=81 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1658212365757] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB InfoFacade, method: public java.lang.String de.symeda.sormas.backend.info.InfoFacadeEjb.generateDataProtectionDictionary() throws java.io.IOException]]

[2022-07-19T08:32:45.758+0200] [Payara 5.2021.10] [WARNUNG] [] [javax.enterprise.ejb.container] [tid: _ThreadID=81 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1658212365758] [levelValue: 900] [[

javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
        at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
        at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
        at com.sun.proxy.$Proxy701.generateDataProtectionDictionary(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)
        at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)
        at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)
        at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)
        at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)
        at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:128)
        at com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:258)
        at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:188)
        at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)
        at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)
        at de.symeda.sormas.api.info.__InfoFacade_Remote_DynamicStub.generateDataProtectionDictionary(de/symeda/sormas/api/info/__InfoFacade_Remote_DynamicStub.java)
        at de.symeda.sormas.api.info._InfoFacade_Wrapper.generateDataProtectionDictionary(de/symeda/sormas/api/info/_InfoFacade_Wrapper.java)
        at de.symeda.sormas.ui.AboutView.lambda$attachDataProtectionDictionaryDownloader$3(AboutView.java:354)
        at de.symeda.sormas.ui.utils.DownloadUtil$DelayedInputStream.lambda$new$0(DownloadUtil.java:424)
        at de.symeda.sormas.ui.utils.DownloadUtil$DelayedInputStream.ensureInited(DownloadUtil.java:435)
        at de.symeda.sormas.ui.utils.DownloadUtil$DelayedInputStream.read(DownloadUtil.java:448)
        at com.vaadin.server.DownloadStream.writeResponse(DownloadStream.java:306)
        at com.vaadin.server.FileDownloader.handleConnectorRequest(FileDownloader.java:187)
        at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:90)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)
        at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy901.doFilter(Unknown Source)
        at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
        at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
]]

[2022-07-19T08:32:45.761+0200] [Payara 5.2021.10] [INFORMATION] [] [] [tid: _ThreadID=81 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1658212365761] [levelValue: 800] [[
  E083245.760|     > null (de.symeda.sormas.ui.SormasErrorHandler.java:82)
java.lang.NullPointerException: null
        at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
        at com.vaadin.server.DownloadStream.tryToCloseStream(DownloadStream.java:368)
        at com.vaadin.server.DownloadStream.writeResponse(DownloadStream.java:317)
        at com.vaadin.server.FileDownloader.handleConnectorRequest(FileDownloader.java:187)
        at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:90)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)
        at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy901.doFilter(Unknown Source)
        at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
        at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
]]

```

</details>

**Comment by StefanKock** [comment]
I was mostly able to reproduce this exception on DEV 1.74.1-SNAPSHOT if I provide an empty `DataProtectionInfo.xlsx`. Maybe the provided file is incorrect.

```
2022-07-19T10:12:16.403+0200|WARNUNG: A system exception occurred during an invocation on EJB InfoFacade, method: public java.lang.String de.symeda.sormas.backend.info.InfoFacadeEjb.generateDataProtectionDictionary() throws java.io.IOException
2022-07-19T10:12:16.404+0200|WARNUNG: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
...
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.info.InfoFacadeEjb.getDataProtectionColumns(InfoFacadeEjb.java:444)
	at de.symeda.sormas.backend.info.InfoFacadeEjb.generateDataProtectionDictionary(InfoFacadeEjb.java:225)
...
2022-07-19T10:12:16.472+0200|INFORMATION: E101216.471|     > null (de.symeda.sormas.ui.SormasErrorHandler.java:82)
java.lang.NullPointerException: null
	at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
```

**Comment by kwa20** [comment]
@cmeyerhzi Do you by any change have the up to date file and could deposit it here? Maybe that helps.

**Comment by StefanKock** [comment]
I tried this with the file from test-de, and the NPE occured here:
```
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.info.InfoFacadeEjb.getDataProtectionCellData(InfoFacadeEjb.java:428)
	at de.symeda.sormas.backend.info.InfoFacadeEjb.generateDataProtectionDictionary(InfoFacadeEjb.java:226)
```

It appears that there is Excel magic with the data starting in row 55, and does not seem to work with our implementation.

**Comment by StefanKock** [comment]
I tested to disable both existing filters in that first sheet (docked to columns A and H), but the exception was still the same. Additionally, our implementation expects the unique field name in the column A, but it's now in column F. A assume also other column changes happening that don't work with the existing implementation.

**Comment by StefanKock** [comment]
This ticket is now considered as support and therefore "released" with the software

**Comment by carina29** [comment]
Update:
I've moved the data from the received .xlsx file ( 40_SORMAS_Datenfelder._V4-0_220624.xlsx) into the correct .xlsx template.
I also added the missing entities (LabMessages, TestReport) which were added in 40_SORMAS_Datenfelder._V4-0_220624 but were not added in our DataProtectionInfo.xlsx template. 


 40_SORMAS_Datenfelder._V4-0_220624.xlsx was quite different from our DataProtectionInfo.xlsx template.
 The differences were: the orders of the columns, the names of the columns , the content of the columns

With the new Excel the NPE is not thrown anymore and the Data Protection dictionary is downloaded. 

I 'll attach here the template and tomorrow will update the Versionhistorie sheet and some other minor changes should be done. 
I also sent the template for testing to Cristopher Meyer.

[DataProtectionInfo2.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/9151589/DataProtectionInfo2.xlsx)

**Comment by carina29** [comment]
I've added also 2 new columns for version numbers in the DS-Datamodel-Master sheet ( as it was in the received excel sheet) and added all the data in Versionhistorie . 

Cristopher Meyer also received this (the latest DataProtectionInfo,xlsx) for testing. 
If he will confirm that on his side also works fine the new template, I will change the template on our side too.


[DataProtectionInfo.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/9157822/DataProtectionInfo.xlsx)

**Comment by cmeyerhzi** [comment]
the new templates works fine. thank u @carina29

**Comment by carina29** [comment]
Hello all :)
Do we have the final template from the Data Security Team ( the template I've provided with the newly added data from DS Team) which I could merge in development?

If yes, please let me know and attach the completed template :) 


Kind regards,
              Carina

**Comment by abrudanancuta** [comment]
@SORMAS-ChristopherMeyer do we have any updates about more data that needs to be added in the file Data Protection Dictionary?
