### ISSUE TITLE
Initial data sync to android-app fails to process users

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9903]
### Bug Description

Initial data sync to android-app does not work.

### Steps to Reproduce

1. Connect android-app to instance.
2. Data sync fails when processing users on the android-app. StackTrace:
```
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: Error trying to synchronizing data in mode 'CompleteAndRepull'
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: de.symeda.sormas.app.backend.common.DaoException: Transaction callable threw non-SQL exception
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AbstractAdoDao.callBatchTasks(AbstractAdoDao.java:1312)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.handlePulledList(AdoDtoHelper.java:212)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.handlePullResponse(AdoDtoHelper.java:195)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.pullEntities(AdoDtoHelper.java:135)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.rest.SynchronizeDataAsync.pullInitialInfrastructure(SynchronizeDataAsync.java:486)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.rest.SynchronizeDataAsync.pullInfrastructure(SynchronizeDataAsync.java:446)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.rest.SynchronizeDataAsync.doInBackground(SynchronizeDataAsync.java:168)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.rest.SynchronizeDataAsync$1.doInBackground(SynchronizeDataAsync.java:805)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at java.lang.Thread.run(Thread.java:923)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: Caused by: java.sql.SQLException: Transaction callable threw non-SQL exception
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:270)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:636)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:619)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.stmt.StatementExecutor.callBatchTasks(StatementExecutor.java:598)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.dao.BaseDaoImpl.callBatchTasks(BaseDaoImpl.java:724)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AbstractAdoDao.callBatchTasks(AbstractAdoDao.java:1310)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      ... 12 more
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Collection.iterator()' on a null object reference
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.user.UserDao.getJurisdictionLevel(UserDao.java:164)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.user.UserDtoHelper.fillInnerFromDto(UserDtoHelper.java:119)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.user.UserDtoHelper.fillInnerFromDto(UserDtoHelper.java:38)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.fillOrCreateFromDto(AdoDtoHelper.java:360)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.handlePulledDto(AdoDtoHelper.java:238)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.lambda$handlePulledList$0(AdoDtoHelper.java:217)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper.$r8$lambda$hCzJ3sszF_oP3vgBtfucOv2jnwg(Unknown Source:0)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at de.symeda.sormas.app.backend.common.AdoDtoHelper$$ExternalSyntheticLambda0.call(Unknown Source:6)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:237)
07-19 15:37:00.778 30075 31526 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1:      ... 17 more
```

### Expected Behavior

Sync without exception.

### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.73.2
* Android version/Browser: 11
* Server URL: https://congo-staging.sormas.netzlink.com
* User Role: Surveillance officer 

### Additional Information

If a user does not have a UserRole than this would be an expected behaviour. I checked on that instance and did disprove my theory.

```sql
sormas=# SELECT u.username, count(*) AS rolecount FROM users u LEFT JOIN users_userroles uu ON (u.id = uu.user_id)  GROUP BY u.username ORDER BY rolecount ASC;
        username        | rolecount
------------------------+-----------
 TestUser3              |         1
```

I'm also questioning why the `JurisdictionLevel` is calculated on the android-app since it's an attribute in `UserDto`.

**Comment by StefanKock** [comment]
> If a user does not have a UserRole than this would be an expected behaviour. I checked on that instance and did disprove my theory.

It was confirmed by @MartinWahnschaffe that I was correct and users without user roles existed and were fixed before my investigation.

**Comment by StefanKock** [comment]
Avoiding this problem in the future will be dealt with by #9905.
